### ISSUE TITLE
第一次编译时异常

### ISSUE THREAD

**Issue by Vadaski** [AgoraIO-Community/Agora-Flutter-Quickstart#1]
我按照步骤编译，第一次编译时会出现这个异常，第二次就没有了

注: /Users/litavadaski/HOME/src/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-0.9.1/android/src/main/java/ioagora/agorartcengine/AgoraRtcEnginePlugin.java使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

fluter版本号
Flutter 1.0.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5391447fae (2 months ago) • 2018-11-29 19:41:26 -0800
Engine • revision 7375a0f414
Tools • Dart 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

大佬门辛苦啦

**Comment by plutoless** [comment]
@Vadaski  这个应该只是Lint的warning，不影响使用，这个问题我们下个小版本会修复

**Comment by Vadaski** [comment]
好德，谢谢～

**Comment by PRWrl** [comment]
在刚发的 0.9.2 版本里修了些 Android type specifiers 相关的问题，你可以用这个版本试下 @Vadaski

**Comment by Vadaski** [comment]
这个版本可以正常打包
