### ISSUE TITLE
Access denied for camera

### ISSUE THREAD

**Issue by mrcool17** [AgoraIO-Community/Agora-Flutter-Quickstart#100]
i am facing error ...camera is not working and get this error
Access denied finding property "persist.vendor.camera.privapp.list"
E/libc    (10304): Access denied finding property "vendor.camera.aux.packagelist"

please help for this..

**Comment by plutoless** [comment]
https://github.com/flutter/flutter/issues/46952
looks like a device issue. what kind of device are you using? does it work if you change your device to another?

**Comment by mrcool17** [comment]
i am using readmi note 7s

**Comment by mrcool17** [comment]
i am try other device(samsung a50s) also but still same error

**Comment by LichKing-2234** [comment]
@mrcool17 Any detail about your problem? could you pls provide our SDK log?

**Comment by LichKing-2234** [comment]
this error may not the cause of your problem

**Comment by mrcool17** [comment]
my sdk log

W/ning.studantapp(18756): type=1400 audit(0.0:12952): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:18756_7(18756): type=1400 audit(0.0:12953): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "persist.vendor.camera.privapp.list"
W/Thread-529(18756): type=1400 audit(0.0:12954): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
W/Binder:18756_7(18756): type=1400 audit(0.0:12955): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
W/Binder:18756_7(18756): type=1400 audit(0.0:12956): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
W/ning.studantapp(18756): type=1400 audit(0.0:12959): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:18756_2(18756): type=1400 audit(0.0:12960): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:18756_2(18756): type=1400 audit(0.0:12961): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
W/ning.studantapp(18756): type=1400 audit(0.0:12962): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "persist.vendor.camera.privapp.list"
W/Thread-562(18756): type=1400 audit(0.0:12963): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
W/Binder:18756_5(18756): type=1400 audit(0.0:12964): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "persist.vendor.camera.privapp.list"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (18756): Access denied finding property "vendor.camera.aux.packagelist"

**Comment by LichKing-2234** [comment]
by the way, could you pls share your screen capture?

**Comment by LichKing-2234** [comment]
> my sdk log
> 
> W/ning.studantapp(18756): type=1400 audit(0.0:12952): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> W/Binder:18756_7(18756): type=1400 audit(0.0:12953): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "persist.vendor.camera.privapp.list"
> W/Thread-529(18756): type=1400 audit(0.0:12954): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> W/Binder:18756_7(18756): type=1400 audit(0.0:12955): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> W/Binder:18756_7(18756): type=1400 audit(0.0:12956): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> W/ning.studantapp(18756): type=1400 audit(0.0:12959): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> W/Binder:18756_2(18756): type=1400 audit(0.0:12960): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> W/Binder:18756_2(18756): type=1400 audit(0.0:12961): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> W/ning.studantapp(18756): type=1400 audit(0.0:12962): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "persist.vendor.camera.privapp.list"
> W/Thread-562(18756): type=1400 audit(0.0:12963): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> W/Binder:18756_5(18756): type=1400 audit(0.0:12964): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4517 scontext=u:r:untrusted_app:s0:c177,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "persist.vendor.camera.privapp.list"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"
> E/libc (18756): Access denied finding property "vendor.camera.aux.packagelist"

it seem like from logcat, we need our SDK log. you can refer to this.
https://docs.agora.io/en/Voice/API%20Reference/java/v2.9.2/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08

**Comment by mrcool17** [comment]
![Screenshot_1587285601](https://user-images.githubusercontent.com/61824691/79683443-d0777500-8247-11ea-8294-990f4566c430.png)
display only black screen

**Comment by LichKing-2234** [comment]
1、check camera permission
2、refer to our [readme](https://github.com/AgoraIO/Flutter-SDK/blob/master/README.md), see the error handing about black screen
