### ISSUE TITLE
Screen sharing

### ISSUE THREAD

**Issue by saiof95** [AgoraIO-Community/Agora-Flutter-Quickstart#101]
How can we implement the pushExternalVideo frame like in android rtc engine. I need to implement screen sharing in flutter app.

**Comment by LichKing-2234** [comment]
flutter not support it, you can fork our SDK and implement it in Android and iOS code

**Comment by saiof95** [comment]
Can you please provide some hint on how to modify the sdk

**Comment by LichKing-2234** [comment]
@saiof95 you may refer this https://github.com/AgoraIO/Advanced-Video/blob/master/Android/sample-switch-external-video

**Comment by CripyIce** [comment]
Will this feature be available on Flutter? any plans?

**Comment by LichKing-2234** [comment]
@CripyIce Sorry, we have no plan for it now.

**Comment by nemoryoliver** [comment]
Still waiting...

**Comment by yhhCh405** [comment]
Still waiting...

**Comment by mfurkanyuceal** [comment]
I'm waiting too...

**Comment by LichKing-2234** [comment]
We support Screen sharing on the Web and Desktop platforms, you can follow the `dev/flutter2` branch.

For Android, We support it on the next-generation SDK, but because of the system limitations, not support for iOS.
