### ISSUE TITLE
How to Join Channel

### ISSUE THREAD

**Issue by wilsonowilson** [AgoraIO-Community/Agora-Flutter-Quickstart#104]
Hi! In the Agario quickstart, I'm trying to use broadcasting to show the Broadcaster's video. How can I do this?

**Comment by LichKing-2234** [comment]
you can refer these docs.
https://docs.agora.io/en/Interactive%20Broadcast/start_live_android?platform=Android#5-set-the-channel-profile
https://docs.agora.io/en/Interactive%20Broadcast/start_live_android?platform=Android#6-set-the-user-role

**Comment by LichKing-2234** [comment]
The new quickstart is for live broadcasting
