### ISSUE TITLE
No video on iOS

### ISSUE THREAD

**Issue by CripyIce** [AgoraIO-Community/Agora-Flutter-Quickstart#105]
Hi there,
I've just made a new project and copy-paste the example code for testing (https://pub.dev/packages/agora_rtc_engine#-example-tab-).
On Android everything works great and on iOS everything works except the video widgets.
![IMG_DE5D9C23D721-1](https://user-images.githubusercontent.com/26387823/80315454-507d7c00-8800-11ea-9fc2-726104008f96.jpeg)

flutter doctor:
```
[✓] Flutter (Channel beta, v1.17.0-3.2.pre, on Mac OS X 10.15.4 19E287, locale
    en-IL)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.44.2)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (5 available)
```

**Comment by LichKing-2234** [comment]
you may forget to add `io.flutter.embedded_views_preview` to `info.plist`

**Comment by CripyIce** [comment]
@LichKing-2234 Yes that was it! Thanks!
