### ISSUE TITLE
Important and easy to fix : Missing permission in Agora Rtc Engine pub page !

### ISSUE THREAD

**Issue by EArminjon** [AgoraIO-Community/Agora-Flutter-Quickstart#107]
Hello,

I've deploy an app using agora_rtc_engine on ios. I got a black because of the following missing permission in my info.plist :
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```

Without i got the following error : 

```
 [VERBOSE-2:platform_view_layer.cc(22)] Trying to embed a platform view but the PrerollContext does not support embedding
```

**Comment by LichKing-2234** [comment]
We have added it to our demo. Is it just a suggestion to update the readme?

**Comment by EArminjon** [comment]
This page should be updated : https://pub.dev/packages/agora_rtc_engine

**Comment by LichKing-2234** [comment]
Thanks for your reminding, We will update later.

**Comment by LichKing-2234** [comment]
updated in 1.0.11
