### ISSUE TITLE
Integrate web SDK in flutter web app

### ISSUE THREAD

**Issue by Vasantika20** [AgoraIO-Community/Agora-Flutter-Quickstart#109]
How to integrate agora web SDK into the flutter web app? I want to implement it for both mobile app & web app in flutter. I have integrated for mobile app & its working fine.

**Comment by plutoless** [comment]
for web we are still working on the investigation

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Flutter-SDK/issues/63#issuecomment-625779802
please trace this ticket instead.
