### ISSUE TITLE
Agora Test Example fail to run

### ISSUE THREAD

**Issue by anraiki** [AgoraIO-Community/Agora-Flutter-Quickstart#11]
I've inserted the app id into the settings and try to run the app on debug which failed to run. 

Was there any other instruction needed or did I have to build more on top to get the app to run?

**Comment by plutoless** [comment]
What exactly is the issue you are having with? When you say it failed to run, what do you see? Have you executed flutter doctor to ensure all flutter environment is properly setup?

**Comment by anraiki** [comment]
`Flutter Doctor`

Android license needed to be renewed but everything check off green.

`Flutter Run`

App is installed on device but crashes immediately when ran showing: "agora_flutter_quickstart has stopped."

With the option to "Close App"

**Comment by plutoless** [comment]
which platform are you running this with? ios or android?

**Comment by anraiki** [comment]
Android Version 8.0

Samsung-SM-G930A

or Samsung Galaxy S7

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Flutter-SDK/issues/7#issuecomment-483915983
maybe this is the same issue?

**Comment by anraiki** [comment]
Strangely 

`    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.agoraflutterquickstart"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        // Use code below for production build
        // For debug mode you need to comment above lines of code
        // Issue with 'libflutter.so'
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
    }`

I follow the thread there and tried their solution to no avail. Adding x86 did nothing as well. I will poke around for another device to test on.

**Comment by anraiki** [comment]
Okay. 

Removing 

```
        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }
```

Allowed me to run the app perfectly fine.

**Comment by anraiki** [comment]
```
        // Use code below for production build
        // For debug mode you need to comment above lines of code
        // Issue with 'libflutter.so'
        // ndk {
        //     abiFilters 'armeabi-v7a', 'x86'
        // }
```

I believe wording is a bit off on the comment here.

It should be 
`// For debug mode you need to comment below lines of code`

**Comment by vaibhavmali123** [comment]
and what about phone over heating my handset overheats whenever i makes vieocall
