### ISSUE TITLE
is:issue is:open if we remove GeneratedPluginRegistrant.registerWith(flutterEngine); then razorpay will not work! but need both of them

### ISSUE THREAD

**Issue by zubierj13** [AgoraIO-Community/Agora-Flutter-Quickstart#110]
is:issue is:open if we remove GeneratedPluginRegistrant.registerWith(flutterEngine); then razorpay will not work! but need both of them

**Comment by LichKing-2234** [comment]
pls refer to our new readme
https://github.com/AgoraIO/Flutter-SDK#android-black-screen

**Comment by zubierj13** [comment]
thank you,  but i also noticed that there is big issue in size , before
agora package , apk release size is 11MB and after adding agora it go to
34MB

is that also solving in other channels ?

regards,
zubier

**Comment by LichKing-2234** [comment]
you can refer to this doc
https://developer.android.com/studio/projects/gradle-external-native-builds#specify-abi

**Comment by zubierj13** [comment]
thanks , i am doing that ,

i am releasing in this method , separating by ABI. but still  getting high
size change.

flutter build apk --target-platform android-arm64

**Comment by LichKing-2234** [comment]
you can unzip the apk, and check the assets

**Comment by zubierj13** [comment]
assets are not big .it is only happeing when agora package is added !

do you notice size when you try ?

**Comment by LichKing-2234** [comment]
@zubierj13 Sorry, check the lib dir

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/81055378-252f1700-8efb-11ea-9475-4361fe78202b.png)

**Comment by zubierj13** [comment]
there is just .so files

**Comment by LichKing-2234** [comment]
.so files are too large, you can add this to remove x86 .so
```
        ndk {
            abiFilters "arm64-v8a", "armeabi-v7a"
        }
```

**Comment by zubierj13** [comment]
added , but still getting high size

**Comment by LichKing-2234** [comment]
could you pls share the screen capture about your lib dir?

**Comment by zubierj13** [comment]
[image: Screenshot 2020-05-05 at 4.04.40 PM.png]

**Comment by LichKing-2234** [comment]
I cant see the image, my network problem?

**Comment by zubierj13** [comment]
changed to dev channel , still same size

**Comment by zubierj13** [comment]
arm64-v8a
armeabi-v7a
x86
x86_64

these are the fiels in lib folder

**Comment by LichKing-2234** [comment]
so your apk contains all of the .so files, maybe your configuration is not worked, could you pls share your configuration?

**Comment by zubierj13** [comment]
gridle ?

**Comment by LichKing-2234** [comment]
Yes, gradle configuration

**Comment by zubierj13** [comment]
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location
with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 29

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID
(https://developer.android.com/studio/build/application-id.html).
        applicationId "xxxxxxxxxxxxxx"
        minSdkVersion 19
        targetSdkVersion 29
        multiDexEnabled true
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            abiFilters 'x86', 'x86_64', 'armeabi', 'armeabi-v7a',
                    'arm64-v8a'
        }

    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run
--release` works.
            signingConfig signingConfigs.debug
            useProguard true
            proguardFiles
getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'com.android.support:multidex:1.0.3'
}
apply plugin: 'com.google.gms.google-services'

**Comment by LichKing-2234** [comment]
just keep 'armeabi-v7a' and 'arm64-v8a'
```
ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            abiFilters  'armeabi-v7a', 'arm64-v8a'
        }
```

**Comment by zubierj13** [comment]
thanks ,  i am getting lower ,but still

 if i keep one of these , size if very good , but then it will not
open in some devices

**Comment by zubierj13** [comment]
and if i keep both , it will be 21MB .

21 mb is still big size to go up suddenly from 11-12 mb to 21 mb

**Comment by LichKing-2234** [comment]
@zubierj13 Maybe you can only support v7a

**Comment by zubierj13** [comment]
thanks you , it is for now , i wish package get updates soon

**Comment by LichKing-2234** [comment]
what means package get updates

**Comment by zubierj13** [comment]
agora_rtc_engine

flutter library. i mean this

**Comment by LichKing-2234** [comment]
our SDK must support all of the ABI, you can use abiFilters to choose the ABI which you need. I don't think we need to update.

**Comment by zubierj13** [comment]
ok thank you anyway .

**Comment by zubierj13** [comment]
hi sorry , i wanted to know about implementing video recording api in
flutter !

**Comment by plutoless** [comment]
we have provided server side cloud recording
https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms

**Comment by zubierj13** [comment]
ok thank you

**Comment by zubierj13** [comment]
hello !
we got new issue ,
now our app is live in google play , and agora video call are fine in all
other devices yet.
recently one of our client having OnePlus 7t device can not join the
channel . so he is not getting video or audio from other end , but he can
see himself.
please help with us with this issue

regards,
zubier

**Comment by LichKing-2234** [comment]
@zubierj13 could you provide the SDK log?

**Comment by zubierj13** [comment]
where can i get sdk log ?

**Comment by LichKing-2234** [comment]
you can search `setLogFile` from our API DOC
