### ISSUE TITLE
The camera switch doesn't work on Ios

### ISSUE THREAD

**Issue by Hard3333** [AgoraIO-Community/Agora-Flutter-Quickstart#111]
In my app the camera switch feature doesn't work on Ios, on Android works fine.
The library doesn't throw any exception, apparently there was no problem.

How can I solve this problem?
Thanks!

**Comment by LichKing-2234** [comment]
is our demo worked?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
