### ISSUE TITLE
可以实现直播的效果吗？

### ISSUE THREAD

**Issue by leielyq** [AgoraIO-Community/Agora-Flutter-Quickstart#116]
就是一个人拍自己，其他人只能进入频道看着。这样的效果可以吗？像直播带货那样的

**Comment by plutoless** [comment]
可以的

**Comment by LichKing-2234** [comment]
可以参考下原生SDK的调用方式。
https://docs.agora.io/cn/Interactive%20Broadcast/start_live_android?platform=Android#5-设置频道场景

**Comment by leielyq** [comment]
@LichKing-2234 

`
   await AgoraRtcEngine.enableVideo();
    if (MineManager().isMe(widget.chatRoomId)) {

      await  AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    } else {
//      await AgoraRtcEngine.muteLocalVideoStream(true);
//      await AgoraRtcEngine.muteLocalAudioStream(true);
      await AgoraRtcEngine.setClientRole(ClientRole.Audience);
    }

`

这样实现的话 ，听众可以发出声音，不知道为啥，只有调用muteLocalAudioStream才行，但是我总感觉我这样写的话是不合逻辑的。

**Comment by plutoless** [comment]
可以打断点看一下是否成功设置为观众了

**Comment by leielyq** [comment]
@plutoless  请问在哪个文件断点可以看到ClientRole的值

**Comment by LichKing-2234** [comment]
@leielyq 如果解决变更成功会触发onClientRoleChanged。还有有设置直播模式么，貌似没看到调用

**Comment by leielyq** [comment]
@LichKing-2234 没有设置直播模式，我看漏了文档，我再去试试

**Comment by leielyq** [comment]
可以了  谢谢
