### ISSUE TITLE
Is it possible to have both live broadcast and video calling In One App.

### ISSUE THREAD

**Issue by EricRootLee** [AgoraIO-Community/Agora-Flutter-Quickstart#119]
After editing the setChannelprofile i cant seem to place video calls i have to edit it back to normal source code.

Is there a way i ca have both ways using the same rtc engine code?

**Comment by plutoless** [comment]
what do you mean by "cannot place video calls?"

**Comment by EricRootLee** [comment]
I was finding it had to create a instance for both a broadcast and a peer to peer call.
But I fixed it.

**Comment by EricRootLee** [comment]
But I have 3 more question,
1. how do I enable live chat among viewers while the live stream is on.
2.How do u let the viewers to know a live stream has ended. Because once the broadcast ends the video just pause on the last frame in the audience side.
3.and is there a way of getting the stream time. (the length of a stream)

**Comment by plutoless** [comment]
1. you mean text chat?
2. there will be a user offline event which you can listen to
3. unfortunately no for the moment

**Comment by EricRootLee** [comment]
Yes text chat.

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Flutter-RTM you may use this to send text message.

**Comment by plutoless** [comment]
or build a socket server yourself

**Comment by EricRootLee** [comment]
Ooh great. I think I should close the issue.
