### ISSUE TITLE
install fail on virtual device

### ISSUE THREAD

**Issue by Purelightme** [AgoraIO-Community/Agora-Flutter-Quickstart#12]
克隆master分支下来后，按文档操作后，最后一步flutter run失败：
```$ flutter run
Using hardware rendering with device Android SDK built for x86. If you get graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on Android SDK built for x86 in debug mode...
Initializing gradle...                                             78.1s
Resolving dependencies...                                          20.6s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        57.5s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         2.0s
Error: ADB exited with exit code 1
adb: failed to install /Users/purelightme/Desktop/flutter/Agora-Flutter-Quickstart/build/app/outputs/apk/app.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native
libraries, res=-113]
Error launching application on Android SDK built for x86.```

**Comment by Purelightme** [comment]
为什么关了？
我自己平时写app都是可以跑得，这个quikstart跑不起来，模拟器和安卓真机都是无法安装，提示报错已经贴出来了，能帮忙看下吗？

**Comment by PRWrl** [comment]
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/commit/e658b7b160a760296ac0ff16ee0b9401a7e67bdf

这个提交自动关的issue.

flutter的库libflutter.so没有提供arm64，但 Agora SDK 提供了arm64，所以默认情况编的release包在arm64的真机上会因为找到了agora sdk 的 arm64 而被当成 64位运行，然后找不到 64位的libflutter.so 而编不过。

为了解决这个问题，https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/commit/d78e94fc024d483eb0f6a61cb8c8dd8e83177fb0 这个提交在gradle里加了 abiFilters 指定只编 armeabi-v7a 版本。 这样会导致 x86 的模拟器编不过，虽然上面添加了注释说明。

所以 https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/commit/e658b7b160a760296ac0ff16ee0b9401a7e67bdf 在abiFilters里额外添加了 x86，这样大部分x86模拟器都在默认下可以运行。

你可以用最新的试下，不行的话可能你的模拟器不是x86，试下把整个 abiFilters 都删掉。但要编 release 一定要加上 abiFilters

**Comment by Purelightme** [comment]
谢谢解答，加上ndk abiFilters之后模拟器可以装上了，但是真机（1+5手机 krait）还是装不上。
```
ndk {
 47 //            abiFilters 'armeabi-v7a'
 48             abiFilters 'armeabi-v7a', 'x86', 'armeabi', 'arm64-v8a', 'mips', 'mips64', 'x86_64'
 49         }
```
安装过程记录
``
# purelightme @ purelightmedeMacBook-Pro in ~/Desktop/flutter/Agora-Flutter-Quickstart on git:master x [9:12:36]
$ flutter run
Launching lib/main.dart on ONEPLUS A5000 in debug mode...
Initializing gradle...                                             67.6s
Resolving dependencies...                                          86.6s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                       105.7s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         9.4s
```
一直卡在这里，手机上没有反应，应用没有安装上，不清楚是什么原因呢

**Comment by PRWrl** [comment]
没有报错信息看不出来原因
试试 abiFilters 里只保留 'armeabi-v7a' 和 'x86'，因为flutter还没有提供 arm64-v8a 之类的包

**Comment by Purelightme** [comment]
[install.log](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/3110271/install.log)

最后几句提示：
```
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.agoraflutterquickstart/.MainActivity (has extras) }

           Error type 3
           Error: Activity class {com.example.agoraflutterquickstart/com.example.agoraflutterquickstart.MainActivity} does not exist.
[        ] Waiting for observatory port to be available...
```
