### ISSUE TITLE
How to scale down/up video quality on network change?

### ISSUE THREAD

**Issue by saurabh-vlub** [AgoraIO-Community/Agora-Flutter-Quickstart#121]
Is there any way to scale down or up the video quality of the video if network bandwidth changes?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/cn/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ac8c08e79844a4e62e0670553484cbe90
