### ISSUE TITLE
excessive battery consumption(Android/iOs)

### ISSUE THREAD

**Issue by wesleytoshio** [AgoraIO-Community/Agora-Flutter-Quickstart#123]
I've been repairing the high battery consumption on android and iOs in the last few days, do you have any solution to this? I did a test with one-to-one call only 1 camera on, and even then I get the notification of high battery consumption

`agora_rtc_engine: ^1.0.12`
`flutter channel v1.12.13+hotfix.9`

**Comment by plutoless** [comment]
what kind of battery consumption notification? any screenshots?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
