### ISSUE TITLE
Flutter Error Code 110

### ISSUE THREAD

**Issue by cabudies** [AgoraIO-Community/Agora-Flutter-Quickstart#124]
I'm making a flutter app using the intro app given for flutter. However, I'm receiving the error code 110 could you please help me out with this.

Token, APP_ID (already generated and tested).

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler_1_1_error_code.html#a94a5ecb66b36aa87d3fda2be933c33f3

**Comment by plutoless** [comment]
it's recommended to use int uid
