### ISSUE TITLE
How can I set one for broadcaster and the others for audiences like live broadcasting?

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Community/Agora-Flutter-Quickstart#125]
Hi,

If this supports for live broadcasting properly, is it possible to set one side for broadcaster role and all the others for audiences?

How can I set them according to their role? which souce file and which part and where?

**Comment by LichKing-2234** [comment]
you can set client role to the broadcaster to one of them, and set others to audience

**Comment by LichKing-2234** [comment]
The new quickstart is for live broadcasting
