### ISSUE TITLE
Flutter Error Code 1012

### ISSUE THREAD

**Issue by Abosrie** [AgoraIO-Community/Agora-Flutter-Quickstart#126]
I am getting **Error 1012** 
When I checked the documentation it refers to "_1012: Audio Device Module: An error occurs in starting the recording device._"

But actually I am using the recording method at all! Any Idea how can I handle this error?

**Comment by LichKing-2234** [comment]
has it got the record permission?

**Comment by Abosrie** [comment]
@LichKing-2234 - Yes! I make sure that the cam & mic permissions are granted before I open the channel.

**Comment by plutoless** [comment]
@Abosrie the recording device here is referring to your mic. could you pls double check to see if your mic is working properly? we will use your mic by default unless you disable audio module so you don't need to call any recording method for this.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
