### ISSUE TITLE
How many video Sessions can It handle?

### ISSUE THREAD

**Issue by HassamTalha** [AgoraIO-Community/Agora-Flutter-Quickstart#127]
In the example viewRows() shows that it can display 4 video sessions. So I wanted to know that is it possible to manage more than 4? If yes how many? If not then How can I make it possible in the flutter. 

Basically, I wanted to know that this example seems to be for the group call. Can it be used for a Conference call where we manage multiple users?

**Comment by plutoless** [comment]
you can define this all by yourself. but usually you should limit your mobile screen to not display too many videos.

**Comment by HassamTalha** [comment]
Basically, I want to change this sample app to live broadcasting app. Where only one person will be the host. And he will control the audio and video of the audience. I don't want videos for every person connected to the channel. 

Let's think about the classroom example. So is it possible with this example? And where should I begin? Any help will be Appreciated. Thanks

**Comment by plutoless** [comment]
we have setClientRole api which you can set host/audience (note you will need to use live broadcasting mode via setChannelProfile). An audience will not have its video/audio on when joining channel.

**Comment by HassamTalha** [comment]
Thank you So much for your response. Can you share a code snippet or demo code as an example to get me started?

**Comment by HassamTalha** [comment]
I mean, Anything as an example for live broadcasting.

**Comment by plutoless** [comment]
@HassamTalha just use this demo, and add an extra option in index page to indicate if you want to join as a host or audience. just call setClientRole api depending on the option picked by the user. you may join one host, while the rest audience. You can join as many as audience as you wish.

**Comment by HassamTalha** [comment]
How can host remove an audience from the Channel?

**Comment by LichKing-2234** [comment]
> How can host remove an audience from the Channel?

you can use our RTM SDK to send peer msg, then audience leaves channel when received the msg.

**Comment by HassamTalha** [comment]
@LichKing-2234  Can you please share a link where I can get started. An example that how it works with flutter or any resource?
Thank you

**Comment by plutoless** [comment]
@HassamTalha there is an easier approach if you want just to ban a user, we have provided restful api for this
https://docs.agora.io/en/Agora%20Platform/dashboard_restful_communication#ban-users-at-the-server

**Comment by LichKing-2234** [comment]
> I mean, Anything as an example for live broadcasting.

The new quickstart is for live broadcasting.
