### ISSUE TITLE
Could you please support a sample live broadcasting app using Flutter?

### ISSUE THREAD

**Issue by wann2** [AgoraIO-Community/Agora-Flutter-Quickstart#128]
Could you please support a sample live broadcasting app using Flutter?
It is so so hard to change this sample into live broadcasting app.

**Comment by plutoless** [comment]
@wann2 for which part you are feeling difficulties? if you can clarify that maybe we can help.

**Comment by dhruvrawat18** [comment]
For the broadcasting side app, I added 
`AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);`
inside the _initAgoraRtcEngine() async{} method.

For the audience side app,  I added

`AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    AgoraRtcEngine.setClientRole(ClientRole.Audience);`

inside the _initAgoraRtcEngine() async{} method  and also updated the getRenderViews() as follows-

```
List<Widget> _getRenderViews() {
    List<AgoraRenderWidget> list = List();
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
  }

```

But still on the audience side app, I am getting a black screen. Can you please help with detailed instructions as to how to fix this and make broadcasting work!

**Comment by LichKing-2234** [comment]
have you tried our demo? maybe you can check the value of the `_users` array.

**Comment by dhruvrawat18** [comment]
> have you tried our demo? maybe you can check the value of the `_users` array.

Yeah I am using this demo only.


Do you think it can be because of the

GeneratedPluginRegistrant.registerWith(this);

Do we need to remove this line?

**Comment by LichKing-2234** [comment]
@dhruvrawat18 you can refer to:
[Android black screen](https://github.com/AgoraIO/Flutter-SDK#android-black-screen)
[iOS black screen](https://github.com/AgoraIO/Flutter-SDK#ios-black-screen)

**Comment by dhruvrawat18** [comment]
Hey I am not getting black screen on broadcasting side, black screen is only on audience side so maybe something else is not working. 

Also can you tell me how to make the mainActivity changes more specifically. I am new to flutter. Here is my mainActivity


```
package com.example.agoraflutterquickstart;

import android.os.Bundle;

import io.flutter.app.FlutterActivity;
import io.flutter.plugins.GeneratedPluginRegistrant;

public class MainActivity extends FlutterActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        GeneratedPluginRegistrant.registerWith(this);
    }
}

```

**Comment by LichKing-2234** [comment]
Hey I am not getting black screen on broadcasting side, black screen is only on audience side so maybe something else is not working.

As you say, it may cause by other reason, pls debug or print log to check the value of `_users`.

**Comment by dhruvrawat18** [comment]
Okay so I ran the broadcaster app on my physical device 1 and then joined a channel from it.  After that I ran the audience app on my physical device 2 and added a print statement  `print(_users)`

and it is just empty `I/flutter (29728): []`

**Comment by LichKing-2234** [comment]
could you share your code?

**Comment by dhruvrawat18** [comment]
https://gist.github.com/dhruvrawat18/ba6b6b1a072e96ee698843bda042cb08

**Comment by LichKing-2234** [comment]
have `onUserJoined` be called?

**Comment by dhruvrawat18** [comment]
Oh right it hasn't been called. Where should it be called and with what arguments?

**Comment by LichKing-2234** [comment]
pls join a channel with a special name, then provide the name to help me check the service log.

**Comment by dhruvrawat18** [comment]
> pls join a channel with a special name, then provide the name to help me check the service log.
Ok I am joining the channel name 'testing' as a broadcaster. Do you also need the app ID?

**Comment by LichKing-2234** [comment]
not special, please join `dsjdhsjhdjashjdsd` both broadcaster and audience

**Comment by dhruvrawat18** [comment]
ok i just did

**Comment by LichKing-2234** [comment]
have you joined? I can not found this channel.

**Comment by dhruvrawat18** [comment]
Yes I have joined from two devices

**Comment by LichKing-2234** [comment]
pls provide the SDK log

**Comment by LichKing-2234** [comment]
make sure it has permission to write storage.
https://docs.agora.io/en/Voice/API%20Reference/java/v2.9.2/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08

**Comment by dhruvrawat18** [comment]
Do you want the log from console?

`W/IInputConnectionWrapper(32003): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(32003): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(32003): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(32003): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(32003): endBatchEdit on inactive InputConnection
W/Settings(32003): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
I/AudioManager(32003): In isBluetoothScoOn(), calling application: com.example.agoraflutterquickstart
D/BluetoothHeadset(32003): Binding service...
E/libc    (32003): Access denied finding property "net.dns1"
E/libc    (32003): Access denied finding property "net.dns2"
E/libc    (32003): Access denied finding property "net.dns3"
E/libc    (32003): Access denied finding property "net.dns4"
E/libc    (32003): Access denied finding property "net.dns1"
E/libc    (32003): Access denied finding property "net.dns2"
E/libc    (32003): Access denied finding property "net.dns3"
E/libc    (32003): Access denied finding property "net.dns4"
D/BluetoothHeadset(32003): Proxy object connected
E/SensorManager(32003): registerListenerImpl sensorName:lsm6ds3c Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.example.agoraflutterquickstart,callingPid:32003,callingUid:10094
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In setSpeakerphoneOn(), on: false, calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In setSpeakerphoneOn(), on: true, calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart
E/libc    (32003): Access denied finding property "net.dns1"
E/libc    (32003): Access denied finding property "net.dns2"
E/libc    (32003): Access denied finding property "net.dns3"
E/libc    (32003): Access denied finding property "net.dns4"
I/flutter (32003): []
D/*WEBRTCN*(32003): SetRenderAndroidVM
W/VideoCapabilities(32003): Unsupported mime image/vnd.android.heic
W/VideoCapabilities(32003): Unsupported mime video/divx
W/VideoCapabilities(32003): Unsupported mime video/divx4
W/VideoCapabilities(32003): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(32003): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(32003): Unsupported mime video/x-ms-wmv
E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
I/chatty  (32003): uid=10094(com.example.agoraflutterquickstart) Thread-72 identical 2 lines
E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference`

**Comment by dhruvrawat18** [comment]
Do you have like a working example of broadcasting somewhere so I can check to run that itself?

**Comment by LichKing-2234** [comment]
> Do you want the log from console?
> 
> `W/IInputConnectionWrapper(32003): getTextBeforeCursor on inactive InputConnection W/IInputConnectionWrapper(32003): getSelectedText on inactive InputConnection W/IInputConnectionWrapper(32003): getTextAfterCursor on inactive InputConnection W/IInputConnectionWrapper(32003): beginBatchEdit on inactive InputConnection W/IInputConnectionWrapper(32003): endBatchEdit on inactive InputConnection W/Settings(32003): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value. I/AudioManager(32003): In isBluetoothScoOn(), calling application: com.example.agoraflutterquickstart D/BluetoothHeadset(32003): Binding service... E/libc (32003): Access denied finding property "net.dns1" E/libc (32003): Access denied finding property "net.dns2" E/libc (32003): Access denied finding property "net.dns3" E/libc (32003): Access denied finding property "net.dns4" E/libc (32003): Access denied finding property "net.dns1" E/libc (32003): Access denied finding property "net.dns2" E/libc (32003): Access denied finding property "net.dns3" E/libc (32003): Access denied finding property "net.dns4" D/BluetoothHeadset(32003): Proxy object connected E/SensorManager(32003): registerListenerImpl sensorName:lsm6ds3c Accelerometer Non-wakeup,isWakeUpSensor:false,callingApp: com.example.agoraflutterquickstart,callingPid:32003,callingUid:10094 I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In setSpeakerphoneOn(), on: false, calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In setSpeakerphoneOn(), on: true, calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart I/AudioManager(32003): In isSpeakerphoneOn(), calling application: com.example.agoraflutterquickstart E/libc (32003): Access denied finding property "net.dns1" E/libc (32003): Access denied finding property "net.dns2" E/libc (32003): Access denied finding property "net.dns3" E/libc (32003): Access denied finding property "net.dns4" I/flutter (32003): [] D/*WEBRTCN*(32003): SetRenderAndroidVM W/VideoCapabilities(32003): Unsupported mime image/vnd.android.heic W/VideoCapabilities(32003): Unsupported mime video/divx W/VideoCapabilities(32003): Unsupported mime video/divx4 W/VideoCapabilities(32003): Unrecognized profile/level 0/3 for video/mpeg2 W/VideoCapabilities(32003): Unrecognized profile/level 0/3 for video/mpeg2 W/VideoCapabilities(32003): Unsupported mime video/x-ms-wmv E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference I/chatty (32003): uid=10094(com.example.agoraflutterquickstart) Thread-72 identical 2 lines E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference E/RtcEngine(32003): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference`

I need the SDK log file, not from console.

**Comment by dhruvrawat18** [comment]
Yeah I got that, I was having troubles with SDK log file so it would be great if you have a demo of the working broadcasting app

**Comment by LichKing-2234** [comment]
just add these

**Comment by LichKing-2234** [comment]
you can try to add to after `enableVideo`

**Comment by dhruvrawat18** [comment]
Q1. In both broadcaster and audience?

Q2. In audience should I change the code for getRenderViews List list or not

**Comment by LichKing-2234** [comment]
Q1: yes, the audience just keeps ClientRole.Audience
Q2: I think you do not need to change the code

by the way, provide the SDK log is the best way to solve your problem.

**Comment by dhruvrawat18** [comment]
By not changing the code in getRenderViews, now even audience is showing feed from its own camera only

**Comment by LichKing-2234** [comment]
@dhruvrawat18 
I have modified the quickstart to LiveBroadcasting, you can refer to it.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/pull/133

**Comment by dhruvrawat18** [comment]
Thank you so much for adding this man but still I am getting black screen only on audience side

**Comment by LichKing-2234** [comment]
1.you may join diffrent channel
2.you may use same uid
3.you may use diffrent appid

**Comment by LichKing-2234** [comment]
The new quickstart works fine, im sure

**Comment by dhruvrawat18** [comment]
Hey thank you so much man. Changing the appId did it.
