### ISSUE TITLE
Audio call (using agora.io) disconnects after sometime(roughly one min) when my flutter app is in background

### ISSUE THREAD

**Issue by malkeet-bst** [AgoraIO-Community/Agora-Flutter-Quickstart#129]
<img width="1324" alt="Screenshot 2020-05-24 at 11 45 31 PM" src="https://user-images.githubusercontent.com/39695647/82761512-aaca2680-9e18-11ea-81d9-a589ba5fdebb.png">

**Comment by plutoless** [comment]
you have to use foreground service if you want to keep it working when in background.
