### ISSUE TITLE
android 闪退

### ISSUE THREAD

**Issue by snglw07** [AgoraIO-Community/Agora-Flutter-Quickstart#13]
能在x86Android上正常运行，但 在 MI8,vivo Y67上无法正常运行，一打开，就闪退了

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/11 应该是一个问题 这边看一下logcat看是不是提示没找到flutter.so

**Comment by snglw07** [comment]
是的 04-24 17:19:01.696 20034 20034 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.agora.agorartcengineexample-1/base.apk"],nativeLibraryDirectories=[/data/app/io.agora.agorartcengineexample-1/lib/arm, /data/app/io.agora.agorartcengineexample-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libflutter.so"
但是 加了 abiFilters 'armeabi-v7a' 后 再 flutter build apk --target-platform=android-arm64 打包
lib 目录下 libflutter.so也没打进去，怎么弄呢

**Comment by snglw07** [comment]
解决了
  ndk{
                abiFilters "armeabi-v7a"
            }

flutter build --release 
谢谢

**Comment by koudle** [comment]
@plutoless 

https://github.com/flutter/flutter/issues/18494#issuecomment-477502287

这个问题在 Flutter 上也有 issue ，应该是 Flutter 在打包的时候，32位、64位钟只会有一个打进去，按道理来说，如果只是本地debug，不管你是模拟器，还是32位的手机，还是64位的手机，Flutter 会根据你打包时选择的机器的类型来打包，所以本地debug应该不会有这个问题，只有打release才有这样的问题。

* 所以一种解决办法就是：
把 `ndk{abiFilters "armeabi-v7a",'x86',}` 这样的配置删掉，这个debug肯定没有问题
* 另一种解决办法是：
把ndk的配置补充全，把64位的也加上，就是`ndk {abiFilters 'armeabi-v7a', 'x86','arm64-v8a' }`

**Comment by plutoless** [comment]
@koudle 多谢分析，可以麻烦帮忙提一个pr吗？

**Comment by guohai** [comment]
感觉如果 flutter 不修复的话，应用只能是些 workaround，比如可以使用 `buildTypes` 来设置不同的打包架构(但应该也没有根本的办法解决问题)

`        
debug {
    minifyEnabled false
}
`

`        
release {
    minifyEnabled false
    ndk {
        abiFilters 'arm64-v8a'
    }
}
`

正式的发版的话，现在看起来都是使用 spilt apks，可能目前没有考虑到部分国内独特的发布方式(直接 apk 发布)

**Comment by koudle** [comment]
@guohai 对，但这个应该只有在打 release 包的时候才会有这样的问题，用debug是不会有问题的
