### ISSUE TITLE
videosession.dart File is missing under Util folder

### ISSUE THREAD

**Issue by ssssureshkumar** [AgoraIO-Community/Agora-Flutter-Quickstart#130]
I am trying to make video call by using this github project but the videosession.dart file is missing please can you provide the videosession.dart file as soon as possible. Herewith i have attached screenshot. Please check the attachment for confirmation.
![complaint](https://user-images.githubusercontent.com/65996499/82979891-ccd4cc00-a005-11ea-8735-6d52ce9649f4.jpg)

**Comment by HassamTalha** [comment]
None of the files is missing. This error shows that the build was successful. You need not worry about that. Just upgrade your dependencies.

**Comment by plutoless** [comment]
as @HassamTalha commented i'm not seeing any issues, please maybe reclone the project and try again. you may reopen if the problem still exists.
