### ISSUE TITLE
How can audience switch on and off audio in Live Stream ?

### ISSUE THREAD

**Issue by HassamTalha** [AgoraIO-Community/Agora-Flutter-Quickstart#135]
I am using this example as a live stream. But on joining audience video/audio is off. Is there any way to switch it on? For example, a person from the audience wants to ask something then he/she can switch on the audio and ask.

**Comment by LichKing-2234** [comment]
you should set client role to the broadcaster on the audience client

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
