### ISSUE TITLE
How to maintain a call video into a small window top, and can switch to other pages without interrupting the video

### ISSUE THREAD

**Issue by ArthurKnight** [AgoraIO-Community/Agora-Flutter-Quickstart#136]
How to maintain a call video into a small window top, and can switch to other pages without interrupting the video？

**Comment by ArthurKnight** [comment]
Because the example is the video in the page, but the actual application is that after the video call, you can jump to another page without interrupting the video, I want to know how to implement this.Thank you very much

**Comment by ArthurKnight** [comment]
就是想问一下，怎样在flutter实现视频/音频通话最小化，在视频通话页面怎样做到把视频流保存成小窗口，然后一直置顶在所有页面上，同时你可以跳转到其他页面做任何操作。

**Comment by LichKing-2234** [comment]
这个要在原生做，用windowmanager，flutter有没有类似全局浮层控件不清楚

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
