### ISSUE TITLE
官网上我怎么没有看到相关文档说明？

### ISSUE THREAD

**Issue by SundyHu** [AgoraIO-Community/Agora-Flutter-Quickstart#137]
官网上没看到相关文档说明？debug模式，进入以后屏幕显示：onError:110，打正式签名包，直接闪退！基于Flutter 1.17.0

**Comment by LichKing-2234** [comment]
Flutter SDK目前是社区版，有用我们demo测试么

**Comment by SundyHu** [comment]
打签名包，输入ChannelName以后，直接闪退

**Comment by LichKing-2234** [comment]
crash log是什么，是打包的我们的demo么

**Comment by plutoless** [comment]
@SundyHu 110是token错误的意思，需要在加频道的时候提供正确的token

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
