### ISSUE TITLE
"getUserInfoByUid" invokes "getUserInfoByUserAccount"

### ISSUE THREAD

**Issue by saraeng** [AgoraIO-Community/Agora-Flutter-Quickstart#138]
copied from "agora_rtc_engine-1.0.12\lib\agora_rtc_engine.dart":

```

  /// registerLocalUserAccount
  ///
  /// Gets the user information by passing in the uid.
  static Future<AgoraUserInfo> getUserInfoByUid(int uid) async {
    final AgoraUserInfo result = AgoraUserInfo.fromJson(
        await _channel.invokeMethod('getUserInfoByUserAccount', {"uid": uid}));
    return result;
  }
```

Correct me if I'm wrong' but it looks like the "getUserInfoByUid" function invoke the "getUserInfoByUserAccount" Method instead of "getUserInfoByUid" by mistake. 
that's what probably causes the error:
`PlatformException(getUserInfoByUserAccountError, get user info failed, -134)`
when calling:
`await AgoraRtcEngine.getUserInfoByUid(uid)`

**Comment by LichKing-2234** [comment]
fixed by https://github.com/AgoraIO/Flutter-SDK/pull/144
