### ISSUE TITLE
phone overheats after 1 minute of call

### ISSUE THREAD

**Issue by vaibhavmali123** [AgoraIO-Community/Agora-Flutter-Quickstart#139]
phone overheats after 1 minute of call  on flutter agora SDK

**Comment by LichKing-2234** [comment]
we need more info about your phone. maybe you can reduce video quality?

**Comment by vaibhavmali123** [comment]
I tested it on samsung m20s it's heating

**How I can reduce video quality**

**another one issue:
![IMG-20200623-WA0012](https://user-images.githubusercontent.com/58940316/85410062-3ce25d80-b584-11ea-9785-1aeb809c1607.jpg)
**
whenever i add following code for reducing app size then
I am facing blur or white screen issue
ndk {
             abiFilters 'armeabi-v7a'
        }

**Comment by plutoless** [comment]
you are limiting the cpu arch via abi filter. your app will crash if your phone is not that arch model

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
