### ISSUE TITLE
Calling disableVideo() keeps showing last frame sent instead of show a proper no video screen

### ISSUE THREAD

**Issue by Jeangovti** [AgoraIO-Community/Agora-Flutter-Quickstart#140]
Hi, 

Have a way to swap the last screen sent of local streaming after disable local video, a black screen with VideoOFF icon maybe?

When the user press to disable de local video keeps showing the last frame sent.

**Comment by LichKing-2234** [comment]
You can remove the render weidget from screen.

**Comment by BradyEdgar94** [comment]
How do you listen for the remote user to disable their video and hide screen?

**Comment by LichKing-2234** [comment]
@BradyEdgar94 listen to the userOffline

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
