### ISSUE TITLE
找不到底层函数

### ISSUE THREAD

**Issue by jiangqianghua** [AgoraIO-Community/Agora-Flutter-Quickstart#142]
flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
E/flutter (32520): 	at io.agora.rtc.internal.RtcEngineImpl.nativeLog(Native Method)
E/flutter (32520): 	at io.agora.rtc.internal.Logging.log(Logging.java:25)
E/flutter (32520): 	at io.agora.rtc.internal.Logging.i(Logging.java:49)
E/flutter (32520): 	at io.agora.rtc.internal.RtcEngineImpl.checkIfInUIThread(RtcEngineImpl.java:155)

**Comment by LichKing-2234** [comment]
you may use render widget before the engine created.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
