### ISSUE TITLE
Android 10 Memory leak issue

### ISSUE THREAD

**Issue by HassamTalha** [AgoraIO-Community/Agora-Flutter-Quickstart#143]
Hi, I tested this demo on different devices, Some were black screens but android 10 kept hanging after some time in the call. then restarting the phone was the only solution. Please look into this matter ASAP

**Comment by HassamTalha** [comment]
The device I used was Samsung A51 Android 10

**Comment by LichKing-2234** [comment]
is it ANR? or an OOM crash.

**Comment by HassamTalha** [comment]
Hi @LichKing-2234, thank you for the response. Actually we were testing it in a group of 10 persons. And one of them reported that his device kept hanging after some time while in the call. And he needs to force start the device. No error message. According to him, it was a possible memory leak. His device was Samsung A51 Android 10.

**Comment by HassamTalha** [comment]
What could possibly be wrong? What should I do?

**Comment by LichKing-2234** [comment]
We need more information, such as a crash log.

**Comment by gokulcm09** [comment]
Its an issue faced by Samsung new models and its a memory leak

**Comment by HassamTalha** [comment]
@gokulcm09  Do you have a workaround or a solution for this?

**Comment by plutoless** [comment]
@gokulcm09 how do you tell it's a memory leak? is there any chance you can collect some memory snapshots?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
