### ISSUE TITLE
Agora is unable to build for release,

### ISSUE THREAD

**Issue by EricRootLee** [AgoraIO-Community/Agora-Flutter-Quickstart#144]
Am using thelatest version of flutter and agora but its failling to build in release mode

Running Gradle task 'assembleRelease'...                                                                           
Running Gradle task 'assembleRelease'... Done                     201.4s (!)
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin agora_rtc_engine...
Running Gradle task 'assembleAarRelease'...                             
Running Gradle task 'assembleAarRelease'... Done                   15.6s

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/media/root/Core1/Projects/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-1.0.13/android/local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

The plugin agora_rtc_engine could not be built due to the issue above.

**Comment by plutoless** [comment]
as the error describes it failed to find your android sdk. pls follow the guidance to fix your issue and try again

```
SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at '/media/root/Core1/Projects/FlutterProjects/flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-1.0.13/android/local.properties'.
```
