### ISSUE TITLE
How to take screenshot in flutter using agora package?

### ISSUE THREAD

**Issue by suriyaKalidoss123** [AgoraIO-Community/Agora-Flutter-Quickstart#145]
**My Configuration:**
Agora rtc version: latest version
Also tried using this plugin in  flutter screenshot plugin  latest version
but still, the issue occurs

**Issue:**
Black screen issue occurs while taking a screenshot

Required solution:
**should able to take screen shot**

**Refer this link for more details:**
https://stackoverflow.com/questions/60426884/how-to-take-screenshot-in-flutter-during-video-call

My Code : 
`Future<void> _capturePng() async {
    try {
      RenderRepaintBoundary boundary =
          _globalKey.currentContext.findRenderObject();
      ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      ByteData byteData =
          await image.toByteData(format: ui.ImageByteFormat.png);
      var pngBytes = byteData.buffer.asUint8List();
      final result = await ImageGallerySaver.saveImage(pngBytes);
    } catch (e) {
      print(e);
    }  }  Widget build(BuildContext context) {
    return RepaintBoundary(
        key: _globalKey,
        child: Scaffold(
            backgroundColor: Colors.black,
            body: GestureDetector(
                onDoubleTap: () => _capturePng(),
                child: Screenshot(
                  controller: screenshotController,
                  child: Center(
                    child: Stack(
                      children: <Widget>[
                        _viewRows(),
                        _toolbar(),
                      ],
                    ),
                  ),
                ))));
}`

Is there is any API or workaround available for this issue?. I would like to purchase your plugin if this future is available?

**Comment by LichKing-2234** [comment]
RenderRepaintBoundary does not support PlatformView, you can refer to native_screenshot.
https://pub.dev/packages/native_screenshot

**Comment by suriyaKalidoss123** [comment]
let me check

**Comment by suriyaKalidoss123** [comment]
I Already searched your Api document there is no API available for screen record and screen capture future, is there is an API available in Agora for screen record and screen capture for a particular user
Check this also:https://stackoverflow.com/questions/62813972/how-to-screen-record-particular-widget-in-flutter

**Comment by plutoless** [comment]
@suriyaKalidoss123 there's no one single api call to achieve that. however you can write code in native layer to get the video raw data and write to disk yourself.

**Comment by Meherdeep** [comment]
@suriyaKalidoss123 you can try using this package to take screenshot: [https://pub.dev/packages/native_screenshot](https://pub.dev/packages/native_screenshot)

You can simply run this function to take the screenshot of your stream:
```
Future<void> _capturePng() async {
    String path = await NativeScreenshot.takeScreenshot();
    print(path);
  }
```
