### ISSUE TITLE
Can't set onTap on videoViews?

### ISSUE THREAD

**Issue by shinewanna** [AgoraIO-Community/Agora-Flutter-Quickstart#147]
I'm trying to add onTap on video view but unlucky to me.
Is there any reason or solution for it.
I want to add onTap on each Video View but not work yet.

**Comment by LichKing-2234** [comment]
you can use `Listener`

**Comment by shinewanna** [comment]
Getting Rendering error bro
`  Widget _expandedVideoRow(List<Widget> views) {
    final wrappedViews = views.map<Widget>((f) {
      return Listener(
        child: f,
        onPointerUp: (value) {
          print("here");
        },
      );
    }).toList();

    return Expanded(
      child: Row(
        children: wrappedViews,
      ),
    );
  }`

**Comment by LichKing-2234** [comment]
any error log?

**Comment by shinewanna** [comment]
![Simulator Screen Shot - iPhone Xʀ - 2020-07-10 at 15 27 48](https://user-images.githubusercontent.com/39454969/87136751-f13ced00-c2c1-11ea-8bc4-48e7798d870f.png)
It happen like this.

Error log is:
RenderUiKitView object was given an infinite size during layout.
The nearest ancestor providing an unbounded width constraint is: RenderFlex#9eaab relayoutBoundary=up4 NEEDS-LAYOUT NEEDS-COMPOSITING-BITS-UPDATE OVERFLOWING
The relevant error-causing widget was
    AgoraRenderWidget-[<'2963605545'>]

**Comment by shinewanna** [comment]
bro it work now, but how to add DoubleTap Gesture on Listener.

**Comment by LichKing-2234** [comment]
dev version support it
