### ISSUE TITLE
Module not found when archive in XCode

### ISSUE THREAD

**Issue by haifzhan** [AgoraIO-Community/Agora-Flutter-Quickstart#149]
Everything works fine(It works on the simulator and work on my phone)until I archive the IOS package, the build failed and I got:

```
Module 'agora_rtc_entgine' not found
```

I am using Flutter channel stable and the minimum ios version is 10.0.

I have asked the question on StackOverflow:

https://stackoverflow.com/questions/62886197/flutter-project-archive-issue-using-xcode-agora-rtc-engine-module-agora-rtc-e

Please help, thanks!

**Comment by LichKing-2234** [comment]
sorry for late replay, is this problem still exist?

**Comment by avinashk369** [comment]
problem still exist, although build run without fail in vs code.
![Screenshot 2020-11-01 at 11 57 56 AM](https://user-images.githubusercontent.com/5073425/97796567-867d3c00-1c39-11eb-9b00-a8d0f3324b4b.png)

**Comment by LichKing-2234** [comment]
@avinashk369 have your run `pod install`? by the way, please show your `flutter doctor -v`

**Comment by avinashk369** [comment]
sorry for the late response.
issue had with my runner.xcodeproj but when i select runner.xcworkspace then there wasn't any issue.

**Comment by bharath8831** [comment]
But what is the answer here , could you explain

**Comment by bharath8831** [comment]
How to fix "Module 'agora_rtc_engine' not found" issue??

**Comment by stevenosse** [comment]
Please do we have a solution for this:
I've tried these:

- Update iOS deployment version to 11.0
- Open the xcworkspace instead of xcodeproj
- Runned `flutter clean` and Product -> clean build folder on iOS

None of these solutions worked. Can anyone please help on this ?

**Comment by LichKing-2234** [comment]
@stevenosse maybe you can make a demo and upload it, then I can test it and find some solutions.

**Comment by stevenosse** [comment]
@LichKing-2234 sorry for bothering
I finally found what was causing the bug.

All i had to do was to remove the Podfile (`rm -rf Podfile` from the ios folder), and then rerun the flutter build ios command.

**Comment by aliasgarlabs** [comment]
https://github.com/flutter/flutter/issues/72887#issuecomment-907776844

**Comment by coder-Aayush** [comment]
Facing still the same issue.. how can I fix the issue..?

**Comment by stevenosse** [comment]
> Facing still the same issue.. how can I fix the issue..?

Here is what i did:

rm -rf ios/Podfile ios/Podfile.lock
flutter pub get
flutter run

**Comment by ajax-76** [comment]
I am also having the same issue
