### ISSUE TITLE
app启动正常后，点击join报错，onError：110

### ISSUE THREAD

**Issue by yuchao86** [AgoraIO-Community/Agora-Flutter-Quickstart#150]
运行正常后，点击join报错，onError：110
如下图：

![image](https://user-images.githubusercontent.com/1749503/87748035-73c82e00-c827-11ea-9999-a67bdc3ac91e.png)

**Comment by plutoless** [comment]
您好，110的错误代表token错误，因为您的项目打开了安全设置，所以您在加入频道时需要使用token加入
