### ISSUE TITLE
App crashes when I enter a channel

### ISSUE THREAD

**Issue by GabrielHVM** [AgoraIO-Community/Agora-Flutter-Quickstart#151]
I cloned your repository and insert my appID in the settings.dart file, however when I build the apk and install it on my phone, it just crashes and exits the application. Note: I have already followed the steps of this issue (https://github.com/AgoraIO/Flutter-SDK/issues/7) and it still didn't work. Can someone help me?

Ps.: I tried the architecture arm64-v8a, armeabi-v7a, x86 and also as proposed in issue saided

**Comment by LichKing-2234** [comment]
any crash log?

**Comment by GabrielHVM** [comment]
Hello @LichKing-2234 ! No logs, the app just close. No logging, the app just closes. I even thought about downloading an application that takes the system log, but I didn't have much success.

**Comment by LichKing-2234** [comment]
why no logging, I think it is impossible.

**Comment by GabrielHVM** [comment]
I didn't have any logs, as I said, the app just closes instantly when you enter the chat room.
However, I was uneasy, refactored the code and found a solution to the problem.
The steps I took were:

- update version of agora_rtc_engine in pubspec.yaml to 1.0.13

- Switch wrapper function return to Container instead of Expanded.
![Exchange location](https://user-images.githubusercontent.com/32372054/88385714-3f9fc080-cd85-11ea-859e-6d445f1ccb1d.png)
