### ISSUE TITLE
Change Audio Source 

### ISSUE THREAD

**Issue by sukonin** [AgoraIO-Community/Agora-Flutter-Quickstart#152]
Hello guys! 
Can you please tell me if there is support for changing the audio source?
For example, broadcast sound from a device (not from microphone) directly to a stream.
As far as I can see, there is such support in the native library, but in flutter, unfortunately, I could not find anything similar.

**Comment by LichKing-2234** [comment]
Flutter SDK only supports audio mixing, if you want to add custom audio source, you can fork our SDK.

**Comment by sukonin** [comment]
Yes, I've found methods like `pushExternalAudioFrame` and `pullPlaybackAudioFrame`, but I didn't understand how to capture audio directly from device and redirect bytes to this method. Can you help me on that, or provide some examples, I searched the whole github for examples, but I couldn't find anything =(

**Comment by plutoless** [comment]
@sukonin you can find the example
https://github.com/AgoraIO/Advanced-Audio/tree/master/Android
https://github.com/AgoraIO/Advanced-Audio/tree/master/iOS%26macOS/AgoraAudioIO-Objective-C
