### ISSUE TITLE
How can I get the user that is speaking?

### ISSUE THREAD

**Issue by Hiomma** [AgoraIO-Community/Agora-Flutter-Quickstart#153]
I like would make a App like Google Meet. This app changes the View Video when the user speak and I like would make in my app. Can someone help me?

**Comment by LichKing-2234** [comment]
you can use this method
https://agoraio.github.io/Flutter-SDK/rtc_engine/RtcEngine/enableAudioVolumeIndication.html

**Comment by Hiomma** [comment]
Thank you <3
