### ISSUE TITLE
视频渲染

### ISSUE THREAD

**Issue by nicorobine** [AgoraIO-Community/Agora-Flutter-Quickstart#155]
使用Flutter_boost的时候，视频渲染不出来

**Comment by nicorobine** [comment]
补充一下，只有Android端出现这种情况，iOS端视频正常，而且Android端只是在屏幕上渲染不出来，视频数据能够正常的发送接收，而且iOS端能够正常显示

**Comment by LichKing-2234** [comment]
用Flutter_boost是必现的么

**Comment by nicorobine** [comment]
> 用Flutter_boost是必现的么

根flutter_boost的注册插件有关，Android端原生注册了两次插件，如果注册一次不会有问题，原因是flutter_boost1.12版本注册插件的代码可能有点问题，注册的插件拿不到Activity，造成flutter_boost不能正常使用，目前这里的解决方案有两个，一个是修改flutter_boost的源码，更改下注册插件的方法，一种是注册两次插件（第二次是自己注册），但是注册两次插件就会引起视频不能渲染的问题

**Comment by LichKing-2234** [comment]
那你可以试试dev版本，这个版本应该解决了多次注册的问题
