### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by DedSecTeam17** [AgoraIO-Community/Agora-Flutter-Quickstart#157]
When app on debug mode work fine , but when i build for release black screen show up.

**Comment by LichKing-2234** [comment]
have you tried our demo?

**Comment by DedSecTeam17** [comment]
Ok, my problem is runtime permissions, the last package I used has an auto-request for runtime permission, the package name is `agora_flutter_webrtc ` because problems that I faced in this package I convert to this package and permission already granted before and application work fine,  so when I build app black scree reveal caused by permissions. so I hope on the next release include permission check.
