### ISSUE TITLE
Chat message while one to one video call is going on

### ISSUE THREAD

**Issue by RuhaanSharma** [AgoraIO-Community/Agora-Flutter-Quickstart#158]
I have created one to one video call implementation using Agora and flutter.
Now my client need that both caller can send chat message to each other too while they are active in video call.
Please let me know how can I achieve sending text in agora when 2 users have already joined the channel and video call is going on.

**Comment by LichKing-2234** [comment]
you can use our RTM SDK.
https://pub.dev/packages/agora_rtm

**Comment by RuhaanSharma** [comment]
But this will require to establish a new connection using AgoraRtmClient.
1). I was wondering if it is possible by means using the connection already established between 2 users via AgoraRtcEngine ?
2). What about the scenario 2 users are not in direct chat. But one user must listen to messages from any number of users even when that user is offline in the app ?

**Comment by plutoless** [comment]
1). currently AgoraRtcEngine only transfer stream data, using RTM is a more reliable way to do p2p/channel messaging
2). RTM support offline message, so he will be able to receive the message once he comes back online. you may also achieve this via push notification

**Comment by RuhaanSharma** [comment]
I am facing same issue in your demo app ?
Should I avoid using AgoraRtmClient if users are not receiving offline message yet ?

**Comment by LichKing-2234** [comment]
@RuhaanSharma

**Comment by RuhaanSharma** [comment]
@LichKing-2234 
So for my purpose user can send offline message and can see chat history, RTM SDK will not be able to provide these features at the moment.
I will look forward to any other solution at the moment.
Thanks for clearing my doubts and letting me go on another path.
