### ISSUE TITLE
Error code 17: when view is in draggable

### ISSUE THREAD

**Issue by pavankumarkatakam** [AgoraIO-Community/Agora-Flutter-Quickstart#16]
Hi, I'm using the draggable widget for moving the LocalVideo, the video is working fine and dragging is also working fine but Error code 17 is coming whenever the dragging is finished.

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/57220261-3534c200-702d-11e9-872e-6b2b9593803f.png)
please refer to the doc and check if your integration could cause similar issues

**Comment by pavankumarkatakam** [comment]
I saw another documentation having another line for error code 17 only "The user tries to join the channel during echo test. Wait until the echo test is finished", what is echo test and who do i need to wait for that echo test

Because, i have kept some print statements at joinChannel is only calling once. And the error code is occuring when DragStopped .

**Comment by plutoless** [comment]
Could you pls help provide your sdk logs? Echo test is a specific api used to test potential echos of user environment. If you are not calling it, you may simply ignore it. Have you joined successfully at all? Callback received?

**Comment by pavankumarkatakam** [comment]
Where will be the SDK logs? how to get them?
I'm successfully joining the channel and getting the remote video as well, I'm not stuck at development but getting the error code 17 always that's it.

**Comment by plutoless** [comment]
you can call setLogFile api to set a path where to store your log file, and use whatever ways you are used to to get the file and attach to this issue. btw what happens when you see the error code? if it's not affecting at all maybe you can also just ignore the error code?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
