### ISSUE TITLE
Handle incomming calls while video  call is in progress

### ISSUE THREAD

**Issue by vaibhavmali123** [AgoraIO-Community/Agora-Flutter-Quickstart#160]
**How we can Handle incomming calls while video  call is in progress using flutter agora video call SDK please help it's emergency**

**Comment by LichKing-2234** [comment]
you can try to add permission.

<uses-permission android:name="android.permission.READ_PHONE_STATE" />

**Comment by LichKing-2234** [comment]
<uses-permission android:name="android.permission.READ_PHONE_STATE" />

**Comment by alexlovar** [comment]
hello, @vaibhavmali123 , can you show an incoming call screen for video calls? could you help me to implement this in this sample?
thanks a lot

**Comment by plutoless** [comment]
we have native demo at https://github.com/AgoraIO-Usecase/Video-Calling
maybe you can take a look at that first. for the moment we have no plans to make such a demo for flutter, you may search for existing flutter plugins to achieve this though.
