### ISSUE TITLE
Is it possible to implement Cloud Recording in Flutter.

### ISSUE THREAD

**Issue by panchalAlpit** [AgoraIO-Community/Agora-Flutter-Quickstart#161]
Is it possible to implement Cloud Recording in Flutter using [https://pub.dev/packages/agora_rtc_engine](URL) this dependency?
I have checked the [https://docs.agora.io/en/cloud-recording/cloud_recording_api_rest?platform=All%20Platforms#start](URL) But it's not helpful for Flutter.
Thanks

**Comment by plutoless** [comment]
Cloud recording is server end restful api and it's recommend to call from your own server.
