### ISSUE TITLE
直播模式下，观众角色二次进入没有视频画面

### ISSUE THREAD

**Issue by 1yus2yus3** [AgoraIO-Community/Agora-Flutter-Quickstart#162]
在使用flutter 1.0.3版本 接入项目时发现，观众角色第一次进入，app有主播的视频画面和声音，退出当前页面后，重新进入直播间，调用的方法都是和第一一样的方法，但是就是没有视频画面，只有声音。从声网的服务端读取channel下的观众列表确实有刚才的观众，但是就是二次没有画面

**Comment by LichKing-2234** [comment]
退出页面有leavechannel么

**Comment by 1yus2yus3** [comment]
有，调用了leaveChannel，我也在观众角色进入和退出 直播间的时候，我读取了声网的服务端接口，发现用户uid确实在进入时有uid，退出了就没有uid，说明服务端已经接收到了声网客服端的角色，我在官网尝试了工单，他们给出的建议说 吧RTC..的create（ID）方法在整个app中只需要调用一次，我也尝试了 放到了我app的main.dart中，测试发现还是 没有画面只有声音

**Comment by 1yus2yus3** [comment]
核心代码如下，：
`@override
  void dispose() async {
    super.dispose();
    _stompClient?.deactivate();
    _scrollController?.dispose();
    _leaveAndStop();
  }

  @override
  void initState() {
    super.initState();
    Wakelock.enable();
    initialize();
    _initWebSocket();
    _addAgoraEventHandlers();
    BlocProvider.of<LiveRoomViewVOBloc>(context)
        .add(LiveRoomViewVORequested(liveRoomTimesId: widget.liveRoomTimesId));
    BlocProvider.of<LiveRoomQuestionListBloc>(context).add(
        LiveRoomQuestionListRequested(liveRoomTimesId: widget.liveRoomTimesId));
  }

  Future<void> _leaveAndStop() async {
    await AgoraRtcEngine.leaveChannel();
    await AgoraRtcEngine.stopPreview();
  }

  Future<void> initialize() async {
    /// 创建直播实例
    AgoraRtcEngine.create(widget.appId);

    /// 配置直播还是视频通话
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);

    /// 设置视频宽高
    AgoraRtcEngine.setLocalRenderMode(VideoRenderMode.Hidden);

    /// 配置直播参数：
    VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    config.frameRate = 24;
    List<String> _videoDimensions = widget.videoDimensions.split('x');
    config.dimensions = Size(
        double.parse(_videoDimensions[0]), double.parse(_videoDimensions[1]));
//    config.dimensions = Size(1920, 1080);
    await AgoraRtcEngine.setVideoEncoderConfiguration(config);
    AgoraRtcEngine.enableVideo();
    AgoraRtcEngine.enableAudio();

    /// 设置美颜级别
//    BeautyOptions beautyOptions = BeautyOptions();
//    beautyOptions.lighteningContrastLevel = LighteningContrastLevel.High;
//    beautyOptions.lighteningLevel = 1.0;
//   
    /// 设置直播角色
    if (widget.userRole == UserRole.BROADCAST) {
      AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    } else {
      AgoraRtcEngine.setClientRole(ClientRole.Audience);
    }

    /// 开启直播预览
    AgoraRtcEngine.startPreview();

    /// 加入直播间
    AgoraRtcEngine.joinChannel(
        widget.token, widget.liveRoomTimesId, null, widget.uid);
  }

  void _addAgoraEventHandlers() {
    AgoraRtcEngine.onConnectionStateChanged = (int state, int reason) {
      print('>>>>>>>>>onConnectionStateChanged $state');
    };

    AgoraRtcEngine.onError = (dynamic code) {
      print('>>>>>>>>>>>>error $code');
    };

    AgoraRtcEngine.onJoinChannelSuccess = (
      String channel,
      int uid,
      int elapsed,
    ) {
      /// 成功加入直播间时，向后端发送请求，修改直播状态
      LiveRepository()
          .joinChannelSuccess(
              channel: widget?.liveRoomTimesId,
              uid: widget?.uid,
              userRole: widget?.userRole)
          .then((value) {
        print(value);
      }).catchError((error) {
        print('>>>>>> $error');
      });
    };

    AgoraRtcEngine.onLeaveChannel = () {
      LiveRepository()
          .leaveChannelSuccess(
              channel: widget?.liveRoomTimesId,
              uid: widget?.uid,
              userRole: widget?.userRole)
          .then((value) {
        print(value);
      }).catchError((err) {
        print('>>>>>. $err');
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      final info = 'userJoined: $uid';
      print('>>>>>>>>>>>>>>>>>>>>onUserJoined $info');
    };

    AgoraRtcEngine.onUserOffline = (int uid, int reason) {
      final info = 'userOffline: $uid';
      print('>>>>>>>>>>>>>>>>>>onUserOffline $info');
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (
      int uid,
      int width,
      int height,
      int elapsed,
    ) {
      final info = 'firstRemoteVideo: $uid ${width}x $height';
      print('>>>>>>>>>>>>>>>>onFirstRemoteVideoFrame $info');

    
      if (widget?.userRole == UserRole.AUDIENCE) {
        AgoraRtcEngine.setupRemoteVideo(0, VideoRenderMode.Fit, widget.uid);
      }
    };

    AgoraRtcEngine.onClientRoleChanged =
        (ClientRole oldRole, ClientRole newRole) {};

    AgoraRtcEngine.onRemoteVideoStateChanged =
        (int uid, int state, int reason, int elapsed) {
      final info = 'firstRemoteVideo: $uid';
      print('>>>>>>>>>>>>>>>>onFirstRemoteVideoFrame $info');
      if (mounted) {
        setState(() {
          if (state == 1 || state == 2) {
            _isBroadcasting = true;
          } else {
            _isBroadcasting = false;
          }
        });
      }

      /// 如果是观众，主播推流开始第一帧时，开始拉流
      if (widget.userRole == UserRole.AUDIENCE) {
        AgoraRtcEngine.setupRemoteVideo(0, VideoRenderMode.Fit, uid);
      }
    };
  }
`

**Comment by LichKing-2234** [comment]
为什么你调用setupRemoteVideo？我们widget内部会调用这个函数，你外部再调用传的viewId未必正确

**Comment by LichKing-2234** [comment]
请使用最新版本
