### ISSUE TITLE
In release version app got crash

### ISSUE THREAD

**Issue by Mamun361054** [AgoraIO-Community/Agora-Flutter-Quickstart#164]
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.aero.aero_meet <<<

backtrace:
  #00  pc 0000000000073430  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
  #01  pc 000000000001f058  /data/app/com.aero.aero_meet-DAuhkaGNBGuC7g0sq6NpHQ==/split_config.arm64_v8a.apk

but debug mode woking fine

**Comment by LichKing-2234** [comment]
seem like the dump is not from our SDK.
https://github.com/flutter/flutter/issues/63374

**Comment by elaishane** [comment]
Try to Use Proguard Rules.

**Comment by tanmoy27112000** [comment]
I was not able to find the progaurd rule file anywhere. Do I need to create a new file?

**Comment by LichKing-2234** [comment]
@tanmoy27112000 if you use the dev version, you can use our SDK without progaurd.

https://github.com/AgoraIO/Flutter-SDK/blob/master/android/consumer-rules.pro

**Comment by elaishane** [comment]
> I was not able to find the progaurd rule file anywhere. Do I need to create a new file?
Yes you do need to create a Proguard file in Android > app directory 
Search for proguard in Android on web and you shall find it 😁😁
