### ISSUE TITLE
How to achieve full-screen reduced-screen playback?

### ISSUE THREAD

**Issue by hongjiasheng** [AgoraIO-Community/Agora-Flutter-Quickstart#165]
Our company has based on your SDK, and we are currently developing an App, and we have encountered a problem. How to achieve full screen/reduced screen playback? At the beginning of the zoom routing page, after adding to the channel, we create AgoraRenderWidget, the user clicks on the full screen button, jump Go to the full-screen routing page and we will pass the AgoraRenderWidget. The full-screen routing page can have a video, and go back to the zoomed routing page. The AgoraRenderWidget has no video playing. What should I do?

**Comment by LichKing-2234** [comment]
Can you provide sample code for this function

**Comment by LichKing-2234** [comment]
pls try the latest version, I believe it works fine.
