### ISSUE TITLE
Users go offline when switching screen

### ISSUE THREAD

**Issue by jacksonw765** [AgoraIO-Community/Agora-Flutter-Quickstart#168]
I create an instance of agora on screen 1 and all users join. Everything works great no issues. 

When the a user switches screen via Navigator.pushReplacement(), the callback "onUserOffline" is triggered and all the calls drop. 

Is there anyway to fix this? I want to have the call stay connected regardless of what screen is shown. Using Flutter 1.21.0-9.2.pre.

Thanks in advance.

**Comment by LichKing-2234** [comment]
if you did not call the `destroy` or `leaveChannel` method, the communication should keep.

**Comment by jacksonw765** [comment]
Yeah that's what I thought too. It works fine on stable but beta is where it seems to be iffy. Thanks for the help! I'll close this issue since I found the answer.
