### ISSUE TITLE
How to removeNativeView at 3.0.x version?

### ISSUE THREAD

**Issue by mrpvb-pvbk** [AgoraIO-Community/Agora-Flutter-Quickstart#169]
I have an app where the feed consists of live streams (PageView). When scrolling, the current moment should be played back, and the last one will be deleted.

**Comment by LichKing-2234** [comment]
do you mean how to remove the rendered widget?

**Comment by mrpvb-pvbk** [comment]
> do you mean how to remove the rendered widget?

Yes

**Comment by LichKing-2234** [comment]
just do not render it in `Widget build(BuildContext context)`

**Comment by mrpvb-pvbk** [comment]
My bad. I just had to set a condition to check whether the desired screen is currently open) Sorry to bother you for nothing
