### ISSUE TITLE
直播的SDK有flutter版本么

### ISSUE THREAD

**Issue by Loissoul** [AgoraIO-Community/Agora-Flutter-Quickstart#17]

**Comment by plutoless** [comment]
@Loissoul 直播的SDK和通信的SDK是同一个SDK的，区别是在初始化的时候使用不同的channelProfile

**Comment by pc1995** [comment]
> @Loissoul 直播的SDK和通信的SDK是同一个SDK的，区别是在初始化的时候使用不同的channelProfile

这个SDK怎么设置呢

**Comment by plutoless** [comment]
有个setChannelProfile的接口的

**Comment by kennethlau89** [comment]
Is there a video broadcasting sample for flutter ? like  [Basic-Video-Broadcasting](https://github.com/AgoraIO/Basic-Video-Broadcasting) ?

**Comment by plutoless** [comment]
for the moment no. Is there any specific features you would like to see for broadcasting?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
