### ISSUE TITLE
knowing video or audio is disabled

### ISSUE THREAD

**Issue by Ranjithsp6** [AgoraIO-Community/Agora-Flutter-Quickstart#170]
Is there any functions that we can use to check whether the video or audio is disabled?

**Comment by LichKing-2234** [comment]
only can get it from the event listener.
```
/// Occurs when the remote video state changes.
RemoteVideoStateCallback remoteVideoStateChanged;

/// Occurs when the remote audio state changes.
/// This callback indicates the state change of the remote audio stream.
RemoteAudioStateCallback remoteAudioStateChanged;
```

**Comment by LichKing-2234** [comment]
you can refer to https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler.html#a93ebe88d2544253bf4b13faf34873131
