### ISSUE TITLE
Access denied finding property "net.dns1"

### ISSUE THREAD

**Issue by vladimircores** [AgoraIO-Community/Agora-Flutter-Quickstart#172]
Latest version of Agora: `agora_rtc_engine: 3.0.1-dev.7`

```
/Users/vladimir.minkin/Documents/SDKs/Flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel dev, 1.22.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale en-CZ)
    • Flutter version 1.22.0-1.0.pre at /Users/vladimir.minkin/Documents/SDKs/Flutter
    • Framework revision ce40de69b7 (2 weeks ago), 2020-08-20 07:31:50 -0700
    • Engine revision 81027ab0cc
    • Dart version 2.10.0 (build 2.10.0-45.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/vladimir.minkin/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/vladimir.minkin/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/vladimir.minkin/Library/Android/sdk
    • Java binary at: /Users/vladimir.minkin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6776251/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/vladimir.minkin/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-1/193.6626763/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
```

On Android emulator screen:
![Screenshot 2020-09-03 at 14 33 42](https://user-images.githubusercontent.com/442111/92115670-1302ae00-edf3-11ea-97a3-c213045cb3a8.png)

Logs:

```
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for Android SDK built for x86 to report its views...
Debug service listening on ws://127.0.0.1:59643/OKv5P3Ei4Ow=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation(18520): eglMakeCurrent: 0xe8e7f760: ver 3 0 (tinfo 0xd24d9150)
D/eglCodecCommon(18520): setVertexArrayObject: set vao to 0 (0) 1 0
W/IInputConnectionWrapper(18520): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(18520): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(18520): getTextAfterCursor on inactive InputConnection
W/IInputConnectionWrapper(18520): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(18520): endBatchEdit on inactive InputConnection
I/ora_integratio(18520): Background young concurrent copying GC freed 31801(1492KB) AllocSpace objects, 6(168KB) LOS objects, 34% free, 3300KB/5061KB, paused 4.452ms total 116.727ms
I/ora_integratio(18520): Background young concurrent copying GC freed 47645(2116KB) AllocSpace objects, 0(0B) LOS objects, 29% free, 4643KB/6605KB, paused 32.081ms total 137.178ms
E/BluetoothAdapter(18520): Bluetooth binder is null
D/agora-jni(18520): android bridge create done...
E/libc    (18520): Access denied finding property "net.dns1"
E/libc    (18520): Access denied finding property "net.dns2"
E/libc    (18520): Access denied finding property "net.dns3"
E/libc    (18520): Access denied finding property "net.dns4"
W/Gralloc3(18520): allocator 3.x is not supported
E/libc    (18520): Access denied finding property "net.dns1"
E/libc    (18520): Access denied finding property "net.dns2"
E/libc    (18520): Access denied finding property "net.dns3"
E/libc    (18520): Access denied finding property "net.dns4"
D/HostConnection(18520): HostConnection::get() New Host Connection established 0xba12fa70, tid 18696
D/EGL_emulation(18520): eglMakeCurrent: 0xddc7cac0: ver 3 0 (tinfo 0xddc6cf00)
D/HostConnection(18520): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon(18520): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(18520): eglCreateContext: 0xbe7e96a0: maj 3 min 0 rcv 3
D/EGL_emulation(18520): eglMakeCurrent: 0xbe7e96a0: ver 3 0 (tinfo 0xbe4499a0)
I/AGORA_SDK(18520): Surface changed to width 1080 height 1123
I/ora_integratio(18520): Background concurrent copying GC freed 83821(3481KB) AllocSpace objects, 1(16KB) LOS objects, 49% free, 2883KB/5767KB, paused 736us total 373.678ms
I/ora_integratio(18520): Background concurrent copying GC freed 25383(1066KB) AllocSpace objects, 1(16KB) LOS objects, 49% free, 5292KB/10MB, paused 1.159ms total 145.998ms
D/EGL_emulation(18520): eglMakeCurrent: 0xddc7cac0: ver 3 0 (tinfo 0xddc6cf00)
D/HostConnection(18520): HostConnection::get() New Host Connection established 0xba12fb10, tid 18697
D/EGL_emulation(18520): eglMakeCurrent: 0xddc7cac0: ver 3 0 (tinfo 0xddc6cf00)
D/HostConnection(18520): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon(18520): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(18520): eglCreateContext: 0xddc7cca0: maj 3 min 0 rcv 3
D/EGL_emulation(18520): eglMakeCurrent: 0xddc7cca0: ver 3 0 (tinfo 0xd24d9930)
I/AGORA_SDK(18520): Surface changed to width 1080 height 1808
E/BluetoothAdapter(18520): Bluetooth binder is null
I/chatty  (18520): uid=10167(livevideo.flutter.agora.flutter_agora_integration) identical 1 line
E/BluetoothAdapter(18520): Bluetooth binder is null
E/BluetoothAdapter(18520): Bluetooth binder is null
I/chatty  (18520): uid=10167(livevideo.flutter.agora.flutter_agora_integration) identical 5 lines
E/BluetoothAdapter(18520): Bluetooth binder is null
E/libc    (18520): Access denied finding property "net.dns1"
E/libc    (18520): Access denied finding property "net.dns2"
E/libc    (18520): Access denied finding property "net.dns3"
E/libc    (18520): Access denied finding property "net.dns4"
D/*WEBRTCN*(18520): SetRenderAndroidVM
I/VideoCapabilities(18520): Unsupported profile 4 for video/mp4v-es
I/CameraManagerGlobal(18520): Connecting to camera service
```

Appreciate any help.

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/92118229-c4700680-ee28-11ea-8501-64ba77e994ad.png)
your token is invalid.

**Comment by vladimircores** [comment]
Hey @LichKing-2234 thanks for the answer. But what is the token, and where can I find the valid one?

**Comment by LichKing-2234** [comment]
please refer to this doc.
https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms#app-id

**Comment by vladimircores** [comment]
So, if I'm understanding it correctly I have to use the API method to generate token before join the call, right?
And use for this purpose special method `buildTokenWithUid` but in Flutter Agora SDK I can't find it. 

<img width="550" alt="Screenshot 2020-09-04 at 05 54 18" src="https://user-images.githubusercontent.com/442111/92198143-ea6ec880-ee73-11ea-9b94-d5adb996f488.png">

Also in documentation it's written that:
```
Use either an App ID or a token for authentication. For example, when existing users are using App ID for authentication, new users can use a token for authentication, and thus both new and old users can join the same channel. You can gradually phase out the use of App ID for authentication.
```
from [here](https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms#appcertificate)

What **`existing users`** means? (there is only one mentioning of the word `existing` on that page)

**Comment by LichKing-2234** [comment]
build uid should implement on server

you can use the temp token when you test. the doc also contains it.

**Comment by swapnens** [comment]
Hi @vladimircores 
I am glad you solved the issue. Could you please elaborate on the solution?
I face the same issue.

Log:
`Running "flutter pub get" in avey...                                1.8s
Using hardware rendering with device Android SDK built for x86. If you notice graphics artifacts, consider enabling software rendering with "--enable-software-rendering".
Launching lib\main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...                          
FLUTTER_ROOT: C:\src\flutter










Running Gradle task 'assembleDebug'...                            113.3s
ΓêÜ Built build\app\outputs\flutter-apk\app-debug.apk.
Installing build\app\outputs\flutter-apk\app.apk...                 2.0s
Waiting for Android SDK built for x86 to report its views...          8ms
I/OpenGLRenderer(16202): Davey! duration=884ms; Flags=1, IntendedVsync=19947942865482, Vsync=19947942865482, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=19947956944200, AnimationStart=19947957025000, PerformTraversalsStart=19947957098900, DrawStart=19948748213000, SyncQueued=19948751809100, SyncStart=19948755310500, IssueDrawCommandsStart=19948758528000, SwapBuffers=19948777065800, FrameCompleted=19948831341700, DequeueBufferDuration=18179000, QueueBufferDuration=788000, 
I/Choreographer(16202): Skipped 52 frames!  The application may be doing too much work on its main thread.
Syncing files to device Android SDK built for x86...            
I/ai.rimads.avey(16202): Background concurrent copying GC freed 21903(1007KB) AllocSpace objects, 11(1136KB) LOS objects, 49% free, 2839KB/5678KB, paused 10.696ms total 145.678ms

D/EGL_emulation(16202): eglMakeCurrent: 0xe5970400: ver 2 0 (tinfo 0xc650fd70)

D/eglCodecCommon(16202): setVertexArrayObject: set vao to 0 (0) 1 0
Syncing files to device Android SDK built for x86...             1,581ms

Flutter run key commands.
r Hot reload. 
R Hot restart.
h Repeat this help message.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).
An Observatory debugger and profiler on Android SDK built for x86 is available at: http://127.0.0.1:7624/5mD0ZE8_9QA=/
I/ai.rimads.avey(16202): Background young concurrent copying GC freed 31595(1688KB) AllocSpace objects, 0(0B) LOS objects, 11% free, 5000KB/5678KB, paused 832us total 132.193ms
I/ai.rimads.avey(16202): Background concurrent copying GC freed 27028(1326KB) AllocSpace objects, 2(88KB) LOS objects, 49% free, 4469KB/8939KB, paused 803us total 140.419ms
E/BluetoothAdapter(16202): Bluetooth binder is null
D/agora-jni(16202): android bridge create done...
E/libc    (16202): Access denied finding property "net.dns1"
E/libc    (16202): Access denied finding property "net.dns2"
E/libc    (16202): Access denied finding property "net.dns3"
E/libc    (16202): Access denied finding property "net.dns4"
E/libc    (16202): Access denied finding property "net.dns1"
E/libc    (16202): Access denied finding property "net.dns2"
E/libc    (16202): Access denied finding property "net.dns3"
E/libc    (16202): Access denied finding property "net.dns4"
W/Gralloc3(16202): allocator 3.x is not supported
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xdd87c030, tid 16353
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon(16202): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(16202): eglCreateContext: 0xc46ec240: maj 2 min 0 rcv 2
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xc46ec240: ver 2 0 (tinfo 0xc4680130)
I/AGORA_SDK(16202): Surface changed to width 1080 height 2088
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
E/BluetoothAdapter(16202): Bluetooth binder is null
I/chatty  (16202): uid=10147(ai.rimads.avey) identical 8 lines
E/BluetoothAdapter(16202): Bluetooth binder is null
E/libc    (16202): Access denied finding property "net.dns1"
E/libc    (16202): Access denied finding property "net.dns2"
E/libc    (16202): Access denied finding property "net.dns3"
E/libc    (16202): Access denied finding property "net.dns4"
D/*WEBRTCN*(16202): SetRenderAndroidVM
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
I/VideoCapabilities(16202): Unsupported profile 4 for video/mp4v-es
I/CameraManagerGlobal(16202): Connecting to camera service
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
W/AudioTrack(16202): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(16202): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
V/MediaRouter(16202): Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
D/AudioTrack(16202): stop(113): called with 0 frames delivered
W/AudioTrack(16202): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(16202): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
V/MediaRouter(16202): Selecting route: RouteInfo{ name=Phone, description=null, status=null, category=RouteCategory{ name=System types=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO  groupable=false }, supportedTypes=ROUTE_TYPE_LIVE_AUDIO ROUTE_TYPE_LIVE_VIDEO , presentationDisplay=null }
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/IAudioFlinger(16202): createRecord returned error -1
E/AudioRecord(16202): createRecord_l(0): AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI(16202): Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord(16202): Error code -20 when initializing native AudioRecord object.
E/RtcEngine(16202): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
E/RtcEngine(16202): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xaeee8350, tid 16401
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon(16202): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(16202): eglCreateContext: 0xc628d920: maj 2 min 0 rcv 2
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xc628d920: ver 2 0 (tinfo 0xc651b5d0)
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xdd87bef0, tid 16405
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon(16202): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(16202): eglCreateContext: 0xc46ec720: maj 2 min 0 rcv 2
I/AGORA_SDK(16202): Surface changed to width 1080 height 1044
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xc46ec720: ver 2 0 (tinfo 0xdd80f950)
I/AGORA_SDK(16202): Surface changed to width 1080 height 1044
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xe5a04d80, tid 16227
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xe5a04e70, tid 16222
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/*WEBRTCN*(16202): VideoRenderAndroid dtor
D/*WEBRTCN*(16202): VideoRenderAndroid dtor
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/HostConnection(16202): HostConnection::get() New Host Connection established 0xb63ad0a0, tid 16408
D/HostConnection(16202): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer ANDROID_EMU_vulkan_free_memory_sync GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2 
D/eglCodecCommon(16202): setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation(16202): eglCreateContext: 0xc628e160: maj 2 min 0 rcv 2
D/EGL_emulation(16202): eglMakeCurrent: 0xe596f800: ver 2 0 (tinfo 0xe599d380)
D/EGL_emulation(16202): eglMakeCurrent: 0xc628e160: ver 2 0 (tinfo 0xbedfefc0)
I/AGORA_SDK(16202): Surface changed to width 1080 height 2088

Application finished.
`

**Comment by talwarabhimanyu** [comment]
@swapnens Were you able to resolve the `E/libc (16202): Access denied finding property "net.dns1"` issue? If so, request you to share how you solved it. I'm facing the same. Thanks

**Comment by swapnens** [comment]
Hi

This is a warning. I just ignore it.

**Comment by deakjahn** [comment]
Unlikely to be related. I never used agora.io, yet I can see the same error (that's why I stumbled upon this thread). After some investigation, it looks like some permission issues introduced in Android Oreo in the usage of [DNSResolver.](https://developer.android.com/reference/android/net/DnsResolver) It probably is something in a library used by a library...
