### ISSUE TITLE
[embedding] Upgrading Pre 1.12 Android Projects Breaks Plugin 

### ISSUE THREAD

**Issue by alexlovar** [AgoraIO-Community/Agora-Flutter-Quickstart#175]
hello, after update to [embedding] Upgrading Pre 1.12 Android Projects Breaks Plugin

i follow the instructions from:
https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration

before this change the plugin works good , but now i have the follow error:

`
```
BUILD FAILED in 12s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Running Gradle task 'assembleAarRelease'...
Building plugin agora_rtc_engine...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':compileReleaseAidl'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\Users\alex\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\agora_rtc_engine-1.0.15\android\local.properties'.
```
`

**Comment by LichKing-2234** [comment]
could you provide a demo? I will test it and try to fix it.

**Comment by alexlovar** [comment]
looks like the plugin require a local properties file, with the sdk path include inside
the plugin is searching for local.properties and the file does not exist, is necessary to manually create in the path that is provide by the error info.
