### ISSUE TITLE
Black Screen over video call.

### ISSUE THREAD

**Issue by wizhob2020** [AgoraIO-Community/Agora-Flutter-Quickstart#177]
After doing all setup of Agora SDK in my (Flutter )project all things are working, except video screen. i.e I got channel info as well as broad cast id. even sound , but video are black.

**Comment by LichKing-2234** [comment]
is our demo working?

**Comment by vitulgoyani** [comment]
same black screen issue I added that you suggest in note.txt but after in release APK black screen is in video call

**Comment by vitulgoyani** [comment]
> is our demo working?

no, your demo also not working with the release APK

**Comment by umeshlakhani7170** [comment]
i have also same black screen issue when i made release APK.
i also tried that you suggest in readme.txt file
please help us.
Thank you🙏🏼

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart

Yes Demo is working fine, but i migrate the same code in my project,then
facing the same issue.

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart

Demo is alo not working fine because I am getting too much echo on the
recipient side.

Please help me i am really stuck,

**Comment by plutoless** [comment]
@wizhob2020 echo happens usually when you have two devices join the same channel and they are too close.

**Comment by LichKing-2234** [comment]
@vitulgoyani 
I have test our demo, it works when released.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/tree/master

by the way, make sure your version is > [3.0.1-dev.5](https://github.com/AgoraIO/Flutter-SDK/blob/master/CHANGELOG.md#301-dev5)

**Comment by umeshlakhani7170** [comment]
in your git tutorial demo, i think are you use 3.0.1-dev.7 version. and by your suggestion i also try 3.0.1-dev.5 version but same problem black screen at video calling screen.

**Comment by LichKing-2234** [comment]
@umeshlakhani7170 could you release our demo to apk file? Then I can test it.

**Comment by umeshlakhani7170** [comment]
i can't share more then 10 mb file, so can you give me you mail address?

**Comment by umeshlakhani7170** [comment]
This is release APK with this command -> flutter build apk --release

https://sendgb.com/VZlAKMiPewo

**Comment by LichKing-2234** [comment]
@umeshlakhani7170 seem like the `consumer-rules.pro` not work. could you pls check is the file exists? locate to `agora_rtc_engine/android/consumer-rules.pro`

**Comment by LichKing-2234** [comment]
if it not work, you can add these to your `app/proguard-rules.pro`

**Comment by umeshlakhani7170** [comment]
> @umeshlakhani7170 seem like the `consumer-rules.pro` not work. could you pls check is the file exists? locate to `agora_rtc_engine/android/consumer-rules.pro`

- This file not in your github demo code

**Comment by umeshlakhani7170** [comment]
> if it not work, you can add these to your `app/proguard-rules.pro`
> 
> ```
> -keepattributes *Annotation*
> -keep class kotlin.** { *; }
> -keep class org.jetbrains.** { *; }
> 
> -keep class io.agora.**{*;}
> ```

i added this code in app/proguard-rules.pro and made one release APK that not work 😥

**Comment by LichKing-2234** [comment]
@umeshlakhani7170 could you provide your demo project?

**Comment by LichKing-2234** [comment]
@umeshlakhani7170 
you should refer to this doc to config proguard.
https://developer.android.com/studio/build/shrink-code#enable

**Comment by umeshlakhani7170** [comment]
[video_conference_demo-master.zip](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/5218113/video_conference_demo-master.zip)

**Comment by LichKing-2234** [comment]
@umeshlakhani7170 
you miss flutter proguard config.
```
## Flutter wrapper
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }
-dontwarn io.flutter.embedding.**
```

**Comment by umeshlakhani7170** [comment]
> @umeshlakhani7170
> you miss flutter proguard config.
> 
> ```
> ## Flutter wrapper
> -keep class io.flutter.app.** { *; }
> -keep class io.flutter.plugin.**  { *; }
> -keep class io.flutter.util.**  { *; }
> -keep class io.flutter.view.**  { *; }
> -keep class io.flutter.**  { *; }
> -keep class io.flutter.plugins.**  { *; }
> -dontwarn io.flutter.embedding.**
> ```

This is grate help 👍🏼

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart

@Qianze Zhang  yes,

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart

 @Arthas

I have done the changes, but am still facing the same problem. As per
reference, I have attached my project environment demo app as given below:
https://drive.google.com/file/d/1xzhqVeCag7FPbWPiCqZwt_75WtPpYVK7/view?usp=sharing

Dear team please see the demo app and correct me if i am doing wrong steps.

**Comment by LichKing-2234** [comment]
@wizhob2020 What is your problem? getting too much echo on the
recipient side? are video and audio works?

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart

@Arthas  The root problem is black Screen in video call.

**Comment by wizhob2020** [comment]
Hi AgoraIO-Community/Agora-Flutter-Quickstart

@Arthas Please see the Demo App, Please correct me where i am lacking.

**Comment by manyopensource** [comment]
Seven days ago encountered the same black screen issue! If nothing has changed since then I believe it's still there!

**Comment by wizhob2020** [comment]
Hi AgoraIO-Community/Agora-Flutter-Quickstart

Dear Team thanks for quick response, Actually i have followed the
conversion as had with @ Umesh L Lakhani and I have modified the
progard-rule file but still facing the Same problem of black screen.   And
Also have attached my project Environment demo App, so this is a humble
request please see and mark the culprit point of the code snippet.

Demo App Link:
https://drive.google.com/file/d/1xzhqVeCag7FPbWPiCqZwt_75WtPpYVK7/view?usp=sharing

**Comment by LichKing-2234** [comment]
@wizhob2020 @manyopensource black screen only on release mode?

**Comment by LichKing-2234** [comment]
Our demo works fine whatever debug or release, you can clone and try it.

**Comment by LichKing-2234** [comment]
@wizhob2020 Sorry, your project is too large. any log when black screen? such as:
```
E/flutter (27900): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, Incomplete hierarchy for class AgoraRtcEnginePlugin, unresolved classes [io.flutter.embedding.engine.plugins.FlutterPlugin, io.flutter.plugin.common.MethodChannel.MethodCallHandler, io.flutter.plugin.common.EventChannel.StreamHandler], null)
E/flutter (27900): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572)
E/flutter (27900): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #2      RtcEngine.createWithAreaCode (package:agora_rtc_engine/src/rtc_engine.dart:88)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #3      AgoraInit._initAgoraRtcEngine (package:streaming_platform/controller/stream_ininialize.dart:20)
E/flutter (27900): <asynchronous suspension>
E/flutter (27900): #4      AgoraInit.init (package:streaming_platform/controller/stream_ininialize.dart:10)
E/flutter (27900): <asynchronous suspension>
```

**Comment by wizhob2020** [comment]
Hi AgoraIO-Community/Agora-Flutter-Quickstart

@Author <author@noreply.github.com>  I am happy for your quick response.
Please see the log as well as record the video.

LOG
W/IInputConnectionWrapper(14124): getTextBeforeCursor on inactive
InputConnection
W/IInputConnectionWrapper(14124): getSelectedText on inactive
InputConnection
W/IInputConnectionWrapper(14124): getTextAfterCursor on inactive
InputConnection
W/IInputConnectionWrapper(14124): beginBatchEdit on inactive InputConnection
W/IInputConnectionWrapper(14124): endBatchEdit on inactive InputConnection
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
D/agora-jni(14124): android bridge create done...
E/libc    (14124): Access denied finding property "net.dns1"
E/libc    (14124): Access denied finding property "net.dns2"
E/libc    (14124): Access denied finding property "net.dns3"
E/libc    (14124): Access denied finding property "net.dns4"
E/libc    (14124): Access denied finding property "net.dns1"
E/libc    (14124): Access denied finding property "net.dns2"
E/libc    (14124): Access denied finding property "net.dns3"
E/libc    (14124): Access denied finding property "net.dns4"
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
W/izhob.sanwizhob(14124): type=1400 audit(0.0:446): avc: denied { read }
for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In setSpeakerphoneOn(), on: false, calling
application: com.wizhob.sanwizhob
I/AudioManager(14124): In setSpeakerphoneOn(), on: false, calling
application: com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
I/AudioManager(14124): In setSpeakerphoneOn(), on: false, calling
application: com.wizhob.sanwizhob
I/AudioManager(14124): In setSpeakerphoneOn(), on: true, calling
application: com.wizhob.sanwizhob
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
E/libc    (14124): Access denied finding property "net.dns1"
E/libc    (14124): Access denied finding property "net.dns2"
E/libc    (14124): Access denied finding property "net.dns3"
E/libc    (14124): Access denied finding property "net.dns4"
D/*WEBRTCN*(14124): SetRenderAndroidVM
W/VideoCapabilities(14124): Unsupported mime video/divx
W/VideoCapabilities(14124): Unsupported mime video/divx311
W/VideoCapabilities(14124): Unsupported mime video/divx4
W/VideoCapabilities(14124): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14124): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(14124): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(14124): Unsupported mime video/x-ms-wmv
W/Utils   (14124): could not parse long range '175-174'
I/CameraManagerGlobal(14124): Connecting to camera service
W/ahpl_main(14124): type=1400 audit(0.0:448): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
W/ahpl_main(14124): type=1400 audit(0.0:449): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
W/ahpl_main(14124): type=1400 audit(0.0:450): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
W/Binder:14124_1(14124): type=1400 audit(0.0:451): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
D/        (14124): PlayerBase::PlayerBase()
D/        (14124): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(14124): Emulating old channel mask behavior (ignoring
positional mask 0x3, using default mask 0x3 based on channel count of 2)
I/AudioManager(14124): In isSpeakerphoneOn(), calling application:
com.wizhob.sanwizhob
W/AudioTrack(14124): createTrack_l(0): AUDIO_OUTPUT_FLAG_FAST denied by
server; frameCount 0 -> 648
W/libOpenSLES(14124): Conversion from OpenSL ES positional channel mask 0x4
to Android mask 0 loses channels
I/libOpenSLES(14124): Emulating old channel mask behavior (ignoring
positional mask 0x4, using default mask 0x10 based on channel count of 1)
I/AudioManager(14124): In isBluetoothScoOn(), calling application:
com.wizhob.sanwizhob
W/GENP.2  (14124): type=1400 audit(0.0:452): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
E/libc    (14124): Access denied finding property
"persist.vendor.camera.privapp.list"
E/libc    (14124): Access denied finding property
"vendor.camera.aux.packagelist"
W/Binder:14124_5(14124): type=1400 audit(0.0:453): avc: denied { read } for
name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=2273
scontext=u:r:untrusted_app:s0:c229,c258,c512,c768
tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0
I/AudioRecord(14124): createRecord_l(1174881543): AUDIO_INPUT_FLAG_FAST
successful; frameCount 0 -> 4096
D/        (14124): PlayerBase::stop() from IPlayer
D/AudioTrack(14124): stop(48): called with 3840 frames delivered
W/Gralloc3(14124): allocator 3.x is not supported
D/        (14124): PlayerBase::PlayerBase()
D/        (14124): TrackPlayerBase::TrackPlayerBase()
I/libOpenSLES(14124): Emulating old channel mask behavior (ignoring
positional mask 0x3, using default mask 0x3 based on channel count of 2)
I/AudioTrack(14124): createTrack_l(48): AUDIO_OUTPUT_FLAG_FAST successful;
frameCount 0 -> 384
W/libOpenSLES(14124): Conversion from OpenSL ES positional channel mask 0x4
to Android mask 0 loses channels
I/libOpenSLES(14124): Emulating old channel mask behavior (ignoring
positional mask 0x4, using default mask 0x10 based on channel count of 1)
I/AudioRecord(14124): createRecord_l(1969303137): AUDIO_INPUT_FLAG_FAST
successful; frameCount 0 -> 4096
I/OMXClient(14124): IOmx service obtained
I/ExtendedACodec(14124): setupVideoEncoder()
W/OMXUtils(14124): do not know color format 0x7fa30c04 = 2141391876
W/OMXUtils(14124): do not know color format 0x7f000789 = 2130708361
I/ACodec  (14124): setupAVCEncoderParameters with [profile: High] [level:
Level31]
I/ACodec  (14124): [OMX.qcom.video.encoder.avc] cannot encode HDR static
metadata. Ignoring.
I/ACodec  (14124): setupVideoEncoder succeeded
I/ExtendedACodec(14124): [OMX.qcom.video.encoder.avc] configure, AMessage :
AMessage(what = 'conf', target = 1) = {
I/ExtendedACodec(14124):   int32_t color-format = 21
I/ExtendedACodec(14124):   int32_t i-frame-interval = 301
I/ExtendedACodec(14124):   string mime = "video/avc"
I/ExtendedACodec(14124):   int32_t width = 1280
I/ExtendedACodec(14124):   int32_t bitrate-mode = 1
I/ExtendedACodec(14124):   int32_t bitrate = 1074450
I/ExtendedACodec(14124):   int32_t frame-rate = 15
I/ExtendedACodec(14124):   int32_t height = 720
I/ExtendedACodec(14124):   int32_t encoder = 1
I/ExtendedACodec(14124): }
W/ExtendedACodec(14124): Failed to get extension for extradata parameter

pubspec.yml
================

name: sanwizhob
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number
used as versionCode.
# Read more about Android versioning at
https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while
build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+3

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  image_picker:
  chopper: ^2.4.0
  provider: ^3.0.0+1
  shared_preferences: any
  connectivity: ^0.4.3+2
  dio: any
  configurable_expansion_tile: ^1.0.0


  json_annotation: any
  pin_code_text_field: ^1.5.1
  flutter_html: ^0.11.1
  search_map_place: ^0.1.1
  geolocator: ^5.1.3
  http: ^0.12.0+4
  cached_network_image: ^2.0.0
  flutter_screenutil: ^1.1.0
  socket_io_client: ^0.9.9
  bubble: ^1.1.9+1
  gallery_saver: ^1.0.7
  permission_handler: ^5.0.0+hotfix.3
  pull_to_refresh: ^1.5.8
  fimber: ^0.4.0
  timeago: ^2.0.26
  google_fonts: ^0.3.5
  firebase_messaging: ^6.0.13
  flutter_local_notifications: ^1.2.1
  share: ^0.6.3+6
  overlay_support: ^1.0.3
  device_info: ^0.4.2+1
  uuid: ^2.0.4
  photo_view: ^0.9.1
  line_awesome_icons: ^1.0.4+2
  line_icons: ^0.2.0
  flutter_sound: ^2.1.1
  file: ^5.0.4
  image_cropper: any
  admob_flutter: "^1.0.0-beta.2"
  google_sign_in: ^4.4.4
  flutter_facebook_login: ^3.0.0
  back_button_interceptor: ^4.2.3
  expandable: ^4.1.4
  flutter_datetime_picker: ^1.3.8
  table_calendar: ^2.2.3
  add_2_calendar: ^1.4.0
  rating_dialog: ^1.0.0
  flutter_email_sender: ^3.0.1
  kommunicate_flutter_plugin: ^1.0.3

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  smooth_star_rating: ^1.0.3
  intl: ^0.16.0
  searchable_dropdown: ^1.1.3
  firebase_auth: ^0.16.0
  package_info: ^0.4.1
  firebase_remote_config: ^0.3.1
  url_launcher: ^5.5.0
  firebase_crashlytics: ^0.1.3
  flutter_launcher_icons: "^0.7.0"
  flutter_automation: ^1.3.3
  file_picker: ^1.13.2
  apple_sign_in: ^0.1.0
  random_color: ^1.0.5
  wakelock: ^0.1.4+1
  flare_flutter:
  agora_rtc_engine: ^3.0.1-dev.7
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  chopper_generator: ^2.3.4
  # No version number means the latest version
  build_runner:

  json_serializable:
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham-Black.otf
        - asset: assets/fonts/Gotham-Bold.otf
        - asset: assets/fonts/Gotham-BookItalic.otf
        - asset: assets/fonts/Gotham-Light.otf
        - asset: assets/fonts/Gotham-Thin.otf
        - asset: assets/fonts/Gotham-ThinItalic.otf
        - asset: assets/fonts/Gotham-XLight.otf
        - asset: assets/fonts/Gotham-XLightItalic.otf
        - asset: assets/fonts/GothamBold.ttf
        - asset: assets/fonts/GothamBoldItalic.ttf
        - asset: assets/fonts/GothamBook.ttf
        - asset: assets/fonts/GothamBookItalic.ttf
        - asset: assets/fonts/GothamLight.ttf
        - asset: assets/fonts/GothamLightItalic.ttf
        - asset: assets/fonts/GothamMedium_1.ttf
        - asset: assets/fonts/GothamMedium.ttf
        - asset: assets/fonts/GothamMediumItalic.ttf




  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
===========================================================================



Video link:
https://drive.google.com/file/d/1nGhD5UyzK8O9adfNe1QSXMy_x5rPKa6F/view?usp=sharing

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart and Author

I am Still waiting for your response.

**Comment by LichKing-2234** [comment]
@wizhob2020 I will try your project.

**Comment by LichKing-2234** [comment]
@wizhob2020 I need the log from your logcat, and your device android version.

**Comment by LichKing-2234** [comment]
@wizhob2020 why add `debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;`?
our SDK only supports Android and iOS now. remove this line will work.

**Comment by wizhob2020** [comment]
Dear AgoraIO-Community/Agora-Flutter-Quickstart,

@Arthas

Awesome, Thanks for your uncountable and speechless support.

**Comment by Hassanmsaid** [comment]
Make sure to enable your local video after joining the channel
```
_engine.enableLocalVideo(true);
```

**Comment by lohnsonok** [comment]
> Make sure to enable your local video after joining the channel
> 
> ```
> _engine.enableLocalVideo(true);
> ```

Working for me

**Comment by KhalidScrypt** [comment]
Issue is closed but I had another case with Black screen and couldn't find any solution on internet. 
Make sure you're not building the views widget RtcLocalView.SurfaceView() or RtcRemoteView.SurfaceView() before you finish the initialization. 
When following the example in Agora.io blog, I just had to add: 
`initialized
              ? _viewRows()
              : Container(
                  height: MediaQuery.of(context).size.height,
                  child: Center(child: CupertinoActivityIndicator()),
                ),`

**Comment by JittuPrimo** [comment]
Make sure you have allow camera permission.

**Comment by ahmedelmwafy** [comment]
Make sure the Uid in Rtc remote view is the same with the user went live and the user joined to live

RtcRemoteView.SurfaceView( uid: uid, channelId:channelId, )
