### ISSUE TITLE
InvalideToken

### ISSUE THREAD

**Issue by Bharavi26** [AgoraIO-Community/Agora-Flutter-Quickstart#178]
i am new with agora sdk in flutter,
i just run example demo and on screen it retuns Invalidtoken error

**Comment by LichKing-2234** [comment]
you can refer to https://docs.agora.io/en/faq/token_error

**Comment by Bharavi26** [comment]
@LichKing-2234 sir,
in agora flutter example , there is not any token related code,
i set my account in agora test mode didn't make any changes n got appid n added in setting.dart in example code

**Comment by LichKing-2234** [comment]
the first param is token.
`await _engine.joinChannel(null, widget.channelName, null, 0);`
could you share a screen capture about your appId certification?

**Comment by Bharavi26** [comment]
i enable certificate manually from agora account n generated test token from panel n put in code, then camera works in **ClientRole.Broadcaster** but black screen in **ClientRole.Audience**

**Comment by LichKing-2234** [comment]
The audience can not broadcast media stream.

**Comment by lucasNewSharp** [comment]
Hi I find out why the we get invalid token on examle projetct. When we create an Agora account, one project is automatically created, and we can't change certificate configuration on edit project. What I did was, create a new project on the console. Creating a new project we can set just APP ID as security mode and when you click on "Edit" project you can enable the certificate if you want. So create a new project on the console and set APP ID as security, the example project will work without a token.

**Comment by plutoless** [comment]
@lucasNewSharp  correct.

**Comment by pirateani01** [comment]
i inserted the appId correctly but it is showing invalid token error.
please help me out.

**Comment by LichKing-2234** [comment]
> Hi I find out why we get invalid token on examle projetct. When we create an Agora account, one project is automatically created, and we can't change certificate configuration on edit project. What I did was, create a new project on the console. Creating a new project we can set just APP ID as security mode and when you click on "Edit" project you can enable the certificate if you want. So create a new project on the console and set APP ID as security, the example project will work without a token.

@pirateani01 you can refer to this comment.

**Comment by pirateani01** [comment]
What if we have to create a unique token and then run the app?

**Comment by LichKing-2234** [comment]
you can create a project without the certificate. but it is not safe.

**Comment by lucasNewSharp** [comment]
Another thing, they will stop with the APP ID security level, so, it's better work with token anyway. https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms

**Comment by jenniestrongbow** [comment]
Why was it closed? No good answer was given.

**Comment by LichKing-2234** [comment]
@jenniestrongbow https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms

**Comment by ishallwin20** [comment]
> Hi I find out why we get invalid token on examle projetct. When we create an Agora account, one project is automatically created, and we can't change certificate configuration on edit project. What I did was, create a new project on the console. Creating a new project we can set just APP ID as security mode and when you click on "Edit" project you can enable the certificate if you want. So create a new project on the console and set APP ID as security, the example project will work without a token.

This solved the issue. Thanks.

**Comment by abinvs-2019** [comment]
> Hi I find out why we get invalid token on examle projetct. When we create an Agora account, one project is automatically created, and we can't change certificate configuration on edit project. What I did was, create a new project on the console. Creating a new project we can set just APP ID as security mode and when you click on "Edit" project you can enable the certificate if you want. So create a new project on the console and set APP ID as security, the example project will work without a token.

But the audio/video feature will not be  enabled without Token...if got please help

**Comment by anywheresa** [comment]
Wow, I have been struggling with this until I saw this post. 
Agora really needs to sharpen their tutorials and docs. This stupid issue caused a lot of wasted time and Agora support not sharp either.

**Comment by hadi7khan** [comment]
@anywheresa How did you fix this issue?
