### ISSUE TITLE
Getting error Could not signal service com.apple.WebKit.WebContent

### ISSUE THREAD

**Issue by SalilThreeplus** [AgoraIO-Community/Agora-Flutter-Quickstart#179]
When I add the io.flutter.embedded_views_preview flag in info plist and I get the error Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service and the application is stuck on splash screen. If I don't add this flag then I get the black screen on iOS.
Any help is appreciated.

Below is the Info.plist ss

<img width="1680" alt="Screenshot 2020-09-13 at 2 53 44 PM" src="https://user-images.githubusercontent.com/58214996/93014843-23284380-f5d2-11ea-9485-b5b6ee43229e.png">

**Comment by LichKing-2234** [comment]
it seems like a problem from WKWebView.

https://stackoverflow.com/questions/40811887/could-not-signal-service-com-apple-webkit-webcontent

**Comment by SalilThreeplus** [comment]
But where do I configure that? I am using plugin like agora and google maps that are dependent on WKWebView, I do not have any custom code.

**Comment by LichKing-2234** [comment]
maybe you can follow this issue.
https://github.com/flutter/flutter/issues/58231

**Comment by SalilThreeplus** [comment]
Application is working fine in debug mode, video calling is working, but when I set io.flutter.embedded_views_preview to YES it sticks at splash screen, there are also no errors.

**Comment by LichKing-2234** [comment]
I will test it

**Comment by LichKing-2234** [comment]
have you try our demo in release mode?

**Comment by SalilThreeplus** [comment]
This is working fine now, there was some error when running code in widgetInitialised method, I shifted all the code to initState and it worked.
