### ISSUE TITLE
Live video broadcasting shows thumbnail size video 

### ISSUE THREAD

**Issue by lintonv** [AgoraIO-Community/Agora-Flutter-Quickstart#18]
I am trying to use agora and flutter to include live video broadcasting in my app. My host video is full screen and my audience video is half screen consistently. How do I fix this? I would like the host video and the audience video to be display the full screen. 

**Host code snippet**

```
 void initialize() {
    _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    _addRenderView(0, (viewId) {
      AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
      AgoraRtcEngine.setupLocalVideo(viewId, VideoRenderMode.Hidden);
      // state can access widget directly
      AgoraRtcEngine.joinChannel(null, "test", null, 0);
    });
  }
  Future<void> _initAgoraRtcEngine() async {
    AgoraRtcEngine.create(APP_ID);
    VideoEncoderConfiguration config = new VideoEncoderConfiguration();
    config.dimensions =  Size(3840, 2160);
    config.frameRate = 30;
    config.orientationMode = VideoOutputOrientationMode.Adaptative;
    config.bitrate = 3420;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);
    AgoraRtcEngine.enableVideo();
  }
void _addAgoraEventHandlers() {
    AgoraRtcEngine.onError = (int code) {
      setState(() {
        String info = 'onError: ' + code.toString();
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      setState(() {
        String info = 'userJoined: ' + uid.toString();
        _infoStrings.add(info);
        _addRenderView(uid, (viewId) {
          AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Hidden, uid);
        });
      });
    };

```

**Audience code snippet**

 ```
void initialize() {
    _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    _addRenderView(1, (viewId) {
      AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      AgoraRtcEngine.setClientRole(ClientRole.Audience);
      AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Hidden, 0);
      AgoraRtcEngine.joinChannel(null, "test", null, 0);
    });
  }

  Future<void> _initAgoraRtcEngine() async {
    AgoraRtcEngine.create(APP_ID);
    VideoEncoderConfiguration config = new VideoEncoderConfiguration();
    config.dimensions =  Size(1920, 1080);
    config.frameRate = 30;
    config.orientationMode = VideoOutputOrientationMode.Adaptative;
    config.bitrate = 3420;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);
    AgoraRtcEngine.enableVideo();
  }

  void _addAgoraEventHandlers() {
    AgoraRtcEngine.onError = (int code) {
      setState(() {
        String info = 'onError: ' + code.toString();
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      setState(() {
        String info = 'userJoined: ' + uid.toString();
        _infoStrings.add(info);
        _addRenderView(uid, (viewId) {
          AgoraRtcEngine.setRemoteRenderMode(uid, VideoRenderMode.Hidden);
          AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Hidden, uid);
        });
      });
    };

```

**Comment by plutoless** [comment]
@lintonv i noticed you set pretty high value for video configuration, but that's not necessary. you just need to expand the container in build method and the video will be automatically stretched to fill the container.

**Comment by lintonv** [comment]
@plutoless - You are correct. That was it!! I just expanded my container and fixed the issue. Closing!

**Comment by DK024-Dev** [comment]
I have stuck in live broadcasting render view for video. Its not working with Agora.createNativeView.

 Future<void> initialize() async {
    if (APP_ID.isEmpty) {
      setState(() {
        _infoStrings.add(
          'APP_ID missing, please provide your APP_ID in settings.dart',
        );
        _infoStrings.add('Agora Engine is not starting');
      });
      return;
    }

    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
  }

  /// Create agora sdk instance and initialize
  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(APP_ID);
    await AgoraRtcEngine.enableVideo();
  }

  /// Add agora event handlers
  void _addAgoraEventHandlers() {
    AgoraRtcEngine.onError = (dynamic code) {
      setState(() {
        final info = 'onError: $code';
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onJoinChannelSuccess = (
      String channel,
      int uid,
      int elapsed,
    ) {
      setState(() {
        final info = '$liveUserName is Live';
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onLeaveChannel = () {
      setState(() {
        _infoStrings.add('onLeaveChannel');
        _users.clear();
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      setState(() {
        final info = 'userJoined: $joinUser';
        _infoStrings.add(info);
        AgoraRtcEngine.createNativeView((viewId) {
          AgoraRtcEngine.setRemoteRenderMode(uid, VideoRenderMode.Hidden);
          AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Hidden, uid);
        });
        _users.add(uid);
      });
    };

    AgoraRtcEngine.onUserOffline = (int uid, int reason) {
      setState(() {
        final info = 'userOffline: $joinUser';
        _infoStrings.add(info);
        _users.remove(uid);
      });
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (
      int uid,
      int width,
      int height,
      int elapsed,
    ) {
      setState(() {
        final info = 'firstRemoteVideo: $uid ${width}x $height';
        _infoStrings.add(info);
      });
    };
  }

  /// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final List<AgoraRenderWidget> list = [
      AgoraRenderWidget(0, local: true, preview: true),
    ];
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
  }

  /// Video view wrapper
  Widget _videoView(view) {
    return Expanded(child: Container(child: view));
  }

  /// Video view row wrapper
  Widget _expandedVideoRow(List<Widget> views) {
    final wrappedViews = views.map<Widget>(_videoView).toList();
    return Expanded(
      child: Row(
        children: wrappedViews,
      ),
    );
  }

  /// Video layout wrapper
  Widget _viewRows() {
    final views = _getRenderViews();
    switch (views.length) {
      case 1:
        return Container(
            child: Column(
          children: <Widget>[_videoView(views[0])],
        ));
      case 2:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow([views[0]]),
            _expandedVideoRow([views[1]])
          ],
        ));
      case 3:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 3))
          ],
        ));
      case 4:
        return Container(
            child: Column(
          children: <Widget>[
            _expandedVideoRow(views.sublist(0, 2)),
            _expandedVideoRow(views.sublist(2, 4))
          ],
        ));
      default:
    }
    return Container();
  }

**Comment by Maincho06** [comment]
What is _addRenderView please

**Comment by plutoless** [comment]
@Maincho06  please check out the latest example. i think the code shown above is out dated.

**Comment by djdivesh007** [comment]
Can u give latest example link...and Even i am facing the same issue of half screen on users side !

**Comment by LichKing-2234** [comment]
@djdivesh007 
maybe you forget set video encoder config. the default size is 640*360.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/tree/dev/3.0.1

**Comment by djdivesh007** [comment]
These are my settings i have set

  AgoraRtcEngine.setParameters(
        '{\"che.video.lowBitRateStreamParameter\":{\"width\":640,\"height\":360,\"frameRate\":30,\"bitRate\":1000}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    AgoraRtcEngine.setClientRole(ClientRole.Audience);
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    config.minFrameRate = 30;

    config.dimensions = Size(960, 720);
    AgoraRtcEngine.setVideoEncoderConfiguration(config);

**Comment by LichKing-2234** [comment]
What have you set on your broadcast client?
