### ISSUE TITLE
全屏和缩小屏显示声网的视频

### ISSUE THREAD

**Issue by hongjiasheng** [AgoraIO-Community/Agora-Flutter-Quickstart#182]
我们公司使用贵司的声网传输功能，目前flutter app端要实现全屏界面播放，从小屏界面跳转到全屏横屏显示视频;
测试发现，在从小屏 -> 全屏 -> 小屏 播放视频中，偶尔会出现黑屏，切换几次后又正常，能给我一些建议或者有没有demo实现这样效果? 

小屏视频部分代码如下,  _viewRows里包裹的是 AgoraRenderWidget, 有远程用户加入通道后，传递uid 构造AgoraRenderWidget(uid), 用户点击了全屏按钮后 navigator跳转到全屏界面,用户在全屏界面点击缩小键跳转回小屏界面

Hero(
              tag: "player",
              child: Stack(
                alignment: Alignment.topCenter,
                children: <Widget>[
                  _viewRows(),
                  Positioned(
                    top: 14.rpx,
                    right: 44.rpx, // 14 + 30
                    child: showHeaderBtOfCameraSwitch(),
                  ),
                  Positioned(
//                    top: (406).rpx, //390 + 16
                    top: videoHeight + 16.rpx,
                    left: 32.rpx,
                    child: Material(
                      type: MaterialType.transparency,
                      child: InkWell(
                        splashColor: Color(0xff16181b),
                        highlightColor: Colors.transparent,
                        onTap: _onToggleMute,
                        child: Image(
                            image: muted
                                ? AssetImage(
                                    "assets/images/hybrid_ctrl_bt_play.png")
                                : AssetImage(
                                    "assets/images/hybrid_ctrl_bt_pause.png"),
                            width: 50.rpx,
                            height: 50.rpx),
                      ),
                    ),
                  ),
                  controlVolume
                      ? Positioned(
                          top: videoHeight - (250).rpx, //390 + 16 - 10 - 256
                          right: (107.5).rpx, //32 + 50 + 28 - 2.5
                          child: _getVolumeSlider(),
                        )
                      : Container(width: 0, height: 0),
                  Positioned(
                    top: videoHeight + 16.rpx, //390 + 16
                    right: (32).rpx,
                    child: Align(
                      alignment: FractionalOffset.centerRight,
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        crossAxisAlignment: CrossAxisAlignment.center,
                        children: <Widget>[
                          Material(
                            type: MaterialType.transparency,
                            child: InkWell(
                              splashColor: Color(0xff16181b),
                              highlightColor: Colors.transparent,
                              onTap: () {
                                setState(() {
                                  controlVolume = !controlVolume;
                                });
                              },
                              child: Image(
                                  image: volumeDisplay != 0
                                      ? AssetImage(
                                          "assets/images/hybrid_ctrl_bt_volume.png")
                                      : AssetImage(
                                          "assets/images/hybrid_ctrl_bt_mute.png"),
                                  width: 50.rpx,
                                  height: 50.rpx),
                            ),
                          ),
                          Padding(
                            padding: EdgeInsets.only(left: 28.rpx),
                          ),
                          Material(
                            type: MaterialType.transparency,
                            child: InkWell(
                              splashColor: Color(0xff16181b),
                              highlightColor: Colors.transparent,
                              onTap: () async {
                                AutoOrientation.landscapeAutoMode();
                                _videoPlayManager.dismissVideoReadyListener(
                                    onFirstRemoteVideoFrameListener);
                                _videoPlayManager.dismissVideoOfflineListener(
                                    onVideoOfflineListener);
                                await _routeVideoFullPage(context);
                                setState(() {});
                              },
                              child: Image(
                                  image: AssetImage(
                                      "assets/images/hybrid_ctrl_bt_expand.png"),
                                  width: 50.rpx,
                                  height: 50.rpx),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ],
              ),
            )

全屏部分代码:
Hero(
                tag: "player",
                child: Stack(
                  alignment: Alignment.topCenter,
                  children: <Widget>[
                    Container(
/*                      width: 960.rpx,
                      height: 542.rpx,*/
                      width: videoWidth,
                      height: videoHeight,
                      decoration: BoxDecoration(
                        color: const Color(0xff5e6778),
                        borderRadius: BorderRadius.circular(16.0.rpx), //16像素圆角
                      ),
                      child: _viewRows(),
                    ),
                    Positioned(
                      top: 14.rpx,
                      right: 14.rpx,
                      child: showHeaderBtOfCameraSwitch(),
                    ),
                    Positioned(
                      bottom: (16).rpx,
                      left: 32.rpx,
                      child: Material(
                        type: MaterialType.transparency,
                        child: InkWell(
                          splashColor: Colors.white.withOpacity(0.0),
                          highlightColor: Colors.transparent,
                          onTap: _onToggleMute,
                          child: Image(
                              image: widget.muted
                                  ? AssetImage(
                                      "assets/images/hybrid_ctrl_bt_play_full.png")
                                  : AssetImage(
                                      "assets/images/hybrid_ctrl_bt_pause_full.png"),
                              width: 50.rpx,
                              height: 50.rpx),
                        ),
                      ),
                    ),
                    controlVolume
                        ? Positioned(
                            top: videoHeight -
                                (332).rpx, //542 - 16 - 50 - 10 - 256
                            right: (107.5).rpx,

                            ///32 + 50 + 28 - 2.5
                            child: _getVolumeSlider(),
                          )
                        : Container(width: 0, height: 0),
                    Positioned(
                      bottom: (16).rpx,
                      right: (32).rpx,
                      child: Align(
                        alignment: FractionalOffset.centerRight,
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: <Widget>[
                            Material(
                              type: MaterialType.transparency,
                              child: InkWell(
                                splashColor: Colors.white.withOpacity(0.0),
                                highlightColor: Colors.transparent,
                                onTap: () {
                                  setState(() {
                                    controlVolume = !controlVolume;
                                  });
                                },
                                child: Image(
                                    image: volumeDisplay != 0
                                        ? AssetImage(
                                            "assets/images/hybrid_ctrl_bt_volume_full.png")
                                        : AssetImage(
                                            "assets/images/hybrid_ctrl_bt_mute_full.png"),
                                    width: 50.rpx,
                                    height: 50.rpx),
                              ),
                            ),
                            Padding(
                              padding: EdgeInsets.only(left: 28.rpx),
                            ),
                            Material(
                              type: MaterialType.transparency,
                              child: InkWell(
                                splashColor: Colors.white.withOpacity(0.0),
                                highlightColor: Colors.transparent,
                                onTap: () async {
                                  setState(() {
                                    deActiveVideoWidget = true;
                                  });
                                  AutoOrientation.portraitUpMode();
                                  Navigator.pop(context);
                                },
                                child: Image(
                                    image: AssetImage(
                                        "assets/images/hybrid_ctrl_bt_full_screen_full.png"),
                                    width: 50.rpx,
                                    height: 50.rpx),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              )

**Comment by LichKing-2234** [comment]
建议使用prerelease版本进行测试

**Comment by hongjiasheng** [comment]
prerelease是哪个版本?

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/94008331-6a35e600-fdd5-11ea-8a25-34c024c48957.png)

**Comment by hongjiasheng** [comment]
这个版本稳定么，能解决我上面提的问题么?我们已经发布使用了，开发时候还是
agora_rtc_engine: ^1.0.13
