### ISSUE TITLE
Flutter Agora SDK - How to generate token for joining channel?

### ISSUE THREAD

**Issue by MungaraJay** [AgoraIO-Community/Agora-Flutter-Quickstart#183]
Hello @plutoless @LichKing-2234 @Matrixbirds @VictorUvarov @azkdev @PRWrl @koudle @Akchy 

I was trying agora demo and i wanted to stream a channel. For now, i am generating a channel "Channel 1" from dashboard and taking token from there and setting it to the following method.

`await_engine.joinChannel("Your_Token", "Channel 1", null, 0);`

So, others can now join using that token and name. But, i think it's not a good approach to generate the token from agora dashboard. 

So, I want to create a channel let say "Channel 1", so how can i generate token from app so that i can upload this token to my database. And other users can join this channel from my database details. 

What is the best way to generate token for all the users. because, i do not think that generating token from agora dashboard is not feasible feature for everyone's requirement?

So can we generate Token from flutter app or we need to generate through web api or any other way.

Can anyone guide me on this issue?

Thanks.

**Comment by Akchy** [comment]
Hey @MungaraJay, actually for joining a channel you need to have the channel ID only. The tokens are used for security purposes (I think, I'm not sure). So tokens are not needed for just joining the channel in flutter.

**Comment by MungaraJay** [comment]
Hey @Akchy 

Thanks for quick reply.

So from where can i get this channel id?

**Comment by Akchy** [comment]
Yes the channel id the unique name which the users can join.

I'm sorry haven't generated token. Hope someone else help you in that.

😁

**Comment by LichKing-2234** [comment]
@MungaraJay you can refer to:
https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms

**Comment by MungaraJay** [comment]
@Akchy @LichKing-2234 where do i have to pass the channel id when joining? i mean which method and param?

**Comment by Akchy** [comment]
@MungaraJay in line no 64 of call.dart in this repo, there is a fuction to join channel with channelName as argument, thats the place where you want to pass the same channel name for same channel.

file location
lib > scr > pages > call.dart

**Comment by Akchy** [comment]
@MungaraJay  It could be better if you ask the error in the slack group. Mostly the code should work, dont know why its coming.

**Comment by topfreeworker123** [comment]
Hello
I am very interesting in this issue because I have some issue to generate token too.
await _engine.joinChannel(null, "1234567890", null, 0);
I think, this method is not running.
I want to know this cause.
Thanks

**Comment by LichKing-2234** [comment]
@topfreeworker123 pls refer to https://docs.agora.io/en/Agora%20Platform/token?platform=All%20Platforms, add 
```
await _engine.joinChannel(your_token, your_channelId, null, your_uid);
```

**Comment by manavagarwal-1216** [comment]
@LichKing-2234 I am making a project using flutter and currently I'm generating temporary token from dashboard how can I generate token automatically because I'm new with flutter too, so I am not able to understand that part. I saw the documentation but there is nothing for flutter.

**Comment by bogzag** [comment]
when you create an agora project you have two option: 
- the one which requires both token and app id
- the one which require only the app id

If you don't want to generate and use the token you can select the "only app id" option. So like that you will be able to use

`await_engine.joinChannel(null, "Channel Name", null, 0);`
