### ISSUE TITLE
Not able to join channel on the basis of APP_ID and channel name

### ISSUE THREAD

**Issue by akshay-02** [AgoraIO-Community/Agora-Flutter-Quickstart#184]
Hi,
I'm trying to join a channel by using method 
joinChannel(null, widget.channelName, null, 0) but I'm not able to. It is giving token error.

When I create a temporary token from Agora console for a given channel name, then video streaming is possible.
joinChannel(temp_token, channelName, null, 0)

Is there any way to directly join the channel or dynamically create temporary token for given channel name?

**Comment by jabonge** [comment]
you should make new project and select App_id authentication Then you can do joinChaneel(null,channelName,null,0) in TestMode

**Comment by Bonasnelson** [comment]
it is t

> you should make new project and select App_id authentication Then you can do joinChaneel(null,channelName,null,0) in TestMode

it is till showing me the same error

**Comment by plutoless** [comment]
@Bonasnelson how did you create the new project with appid only? did you update the new project appid into your project? the way described by @jabonge should be working. are you still seeing a token error?

**Comment by KKshitiz** [comment]
> @Bonasnelson how did you create the new project with appid only? did you update the new project appid into your project? the way described by @jabonge should be working. are you still seeing a token error?

Yes, I've also tried the above method but it shows token error. Temp token method works although.

**Comment by plutoless** [comment]
@KKshitiz if you create a new project with appid only. it should not complain with token error. 
1. do you have the actual error code or description?
2. are you sure you have picked the testing mode option when creating a new project?
![image](https://user-images.githubusercontent.com/471561/95642209-9f328000-0ad9-11eb-9e64-462537d92d34.png)
3. did you make the token field null when joining channel?

**Comment by freshbrigade** [comment]
App Id error

**Comment by asongkai** [comment]
I have the same error 

I followed the video [https://www.youtube.com/watch?v=v9ngriCV0J0](url) but if I used my appId it doesn't work but if I use the appId on the video or from the source code then it works.

How come? I create the app in test mode with APP_ID only but the reason if use my app ID then not works but use the ID from the source code of the video then it works.

**Comment by plutoless** [comment]
@asongkai is there any chance you can collect your sdk log? you can set sdk log file path via setLogFile api.

**Comment by LichKing-2234** [comment]
@plutoless his problem has been solved.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/50#issuecomment-713482574

**Comment by orestesgaolin** [comment]
I have the same issue i.e. even with test mode without app certificate I cannot join the channel from iOS in debug mode:

![image](https://user-images.githubusercontent.com/16854239/99540535-e866d100-29af-11eb-83eb-b3df7b7e1e33.png)

```dart
    try {
      await [Permission.camera, Permission.microphone, Permission.storage]
          .request();

      var engine = await RtcEngine.create(appId);
      engine.setEventHandler(RtcEngineEventHandler(
          joinChannelSuccess: (String channel, int uid, int elapsed) {
        print('joinChannelSuccess $channel $uid');
        setState(() {
          _joined = true;
        });
      }, userJoined: (int uid, int elapsed) {
        print('userJoined $uid');
        setState(() {
          _remoteUid = uid;
        });
      }, userOffline: (int uid, UserOfflineReason reason) {
        print('userOffline $uid');
        setState(() {
          _remoteUid = null;
        });
      }));
      await engine.enableVideo();
      await engine.joinChannel(null, 'test-channel', null, 0);
    } catch (e) {
      print(e);
    }
```

Above call results with:

```
flutter: PlatformException(5, request is refused, null, null)
```

**Comment by LichKing-2234** [comment]
@orestesgaolin is our quickstart working?

**Comment by orestesgaolin** [comment]
> @orestesgaolin is our quickstart working?

Yes, the quickstart worked for me after I generated the token in the console, thanks! The example from the plugin, however, had this issue.

**Comment by suraj0223** [comment]
> > @orestesgaolin is our quickstart working?
> 
> Yes, the quickstart worked for me after I generated the token in the console, thanks! The example from the plugin, however, had this issue.

How did I generate a random token with Channel Id?
