### ISSUE TITLE
Is there any way to check if a live session is already going on with the same channel before joining the channel as an audience? 

### ISSUE THREAD

**Issue by MrPengueeen** [AgoraIO-Community/Agora-Flutter-Quickstart#187]
I wanna know if there exists a way by which I can check if a specific channel has at least one broadcaster. I want to prevent an user from joining a channel as an audience that has no broadcaster or maybe stop the streaming when all the broadcasters leave. If no one has joined a specific channel as a broadcaster, an audience can still join the same channel. Of course, the view for that audience remains as a black screen until a broadcaster joins.

**Comment by plutoless** [comment]
you will have to set up a backend service to manage this kind of information.
