### ISSUE TITLE
iOS: Streaming results in black screen.

### ISSUE THREAD

**Issue by vladimircores** [AgoraIO-Community/Agora-Flutter-Quickstart#188]
Can't see stream on iOS 13
```
<key>io.flutter.embedded_views_preview</key>
<true/>
```
Use the same code as on Android
![ec5d8752-b6ce-4566-a5e7-b1c919ef76b2](https://user-images.githubusercontent.com/442111/94800682-38300f80-03e5-11eb-8982-86fbd88777f7.jpeg)

**Comment by vladimircores** [comment]
Probably this error is not a real cause of the problem, but something else on iOS side.

**Comment by LichKing-2234** [comment]
We don't support > iOS 13 simulator, pls use a real device.
