### ISSUE TITLE
Not able to fix Permissions for camera and microhone

### ISSUE THREAD

**Issue by chakshu21** [AgoraIO-Community/Agora-Flutter-Quickstart#189]
Future<void> _handleCameraAndMic() async {
    await PermissionHandler().requestPermissions(
      [PermissionGroup.camera, PermissionGroup.microphone],
    );
  }

// in lib/src/pages/index.dart

**Comment by LichKing-2234** [comment]
sorry, I can not understand, any problem with permissions?
