### ISSUE TITLE
How to make screenshot of current video stream, like thumbnail?

### ISSUE THREAD

**Issue by the-thirteenth-fox** [AgoraIO-Community/Agora-Flutter-Quickstart#192]

**Comment by LichKing-2234** [comment]
you can wait for 3.2.0, we will make a raw data plugin.

**Comment by mrpvb-pvbk** [comment]
> you can wait for 3.2.0, we will make a raw data plugin.

How long should I wait?

**Comment by LichKing-2234** [comment]
it will release this month-end.

**Comment by LichKing-2234** [comment]
[Raw data plugin](https://pub.dev/packages/agora_rtc_rawdata) is beta now, you can refer to the example and implement the code in the Android&iOS or C++ layer.
