### ISSUE TITLE
Unable to run the quickstart example on device

### ISSUE THREAD

**Issue by talwarabhimanyu** [AgoraIO-Community/Agora-Flutter-Quickstart#193]
Hello, I'm trying to run this quickstart example on an LG P875 phone - the app fails to start on the phone, and everytime I see this pop-up message "Unfortunately, agora_flutter_quickstart has stopped". I have seen the solution in https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/11#issuecomment-486945910 however that did not work for me.

I'm running Android Studio on a Windows 10 machine. Here is the output of `flutter doctor`:

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1139], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!

I copied the line `_engine.setParameters("{\"rtc.log_filter\": 65535}");` in call.dart but it produced no logs on the console.

Kindly help. Thanks.

**Comment by talwarabhimanyu** [comment]
I tried to run it again, and this time it produced this log on the console:

`E/AndroidRuntime(10014): FATAL EXCEPTION: main
E/AndroidRuntime(10014): java.lang.NoClassDefFoundError: io.flutter.embedding.engine.loader.FlutterLoader
E/AndroidRuntime(10014): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:48)
E/AndroidRuntime(10014): 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:24)
E/AndroidRuntime(10014): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1002)
E/AndroidRuntime(10014): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4302)
E/AndroidRuntime(10014): 	at android.app.ActivityThread.access$1300(ActivityThread.java:138)
E/AndroidRuntime(10014): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
E/AndroidRuntime(10014): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10014): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10014): 	at android.app.ActivityThread.main(ActivityThread.java:4904)
E/AndroidRuntime(10014): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10014): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(10014): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(10014): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(10014): 	at dalvik.system.NativeStart.main(Native Method)`

**Comment by LichKing-2234** [comment]
could you pls provide the crash log? it from logcat not flutter console.

**Comment by talwarabhimanyu** [comment]
Thanks for your quick response. There is some issue with my Android Studio and I'm just not able to view logcat. I'll post it as soon as I can get my hands on it.

This info might be useful - the phone I'm running on uses Android Version 4.1.2 and so API level 16. Is this API level supported by Agora? Could this error be due to that? Thanks

**Comment by talwarabhimanyu** [comment]
Here are the error messages I see on the console when I run in debug mode:

`Launching lib\main.dart on LG-P875-9cc6a09 in debug mode...
E/AndroidRuntime(10082): FATAL EXCEPTION: main
E/AndroidRuntime(10082): java.lang.NoClassDefFoundError: io.flutter.embedding.engine.loader.FlutterLoader
E/AndroidRuntime(10082): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:48)
E/AndroidRuntime(10082): 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:24)
E/AndroidRuntime(10082): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1002)
E/AndroidRuntime(10082): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4302)
E/AndroidRuntime(10082): 	at android.app.ActivityThread.access$1300(ActivityThread.java:138)
E/AndroidRuntime(10082): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
E/AndroidRuntime(10082): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10082): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10082): 	at android.app.ActivityThread.main(ActivityThread.java:4904)
E/AndroidRuntime(10082): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10082): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(10082): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(10082): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(10082): 	at dalvik.system.NativeStart.main(Native Method)
Running Gradle task 'assembleDebug'...
E/AndroidRuntime(10162): FATAL EXCEPTION: main
E/AndroidRuntime(10162): java.lang.NoClassDefFoundError: io.flutter.embedding.engine.loader.FlutterLoader
E/AndroidRuntime(10162): 	at io.flutter.view.FlutterMain.startInitialization(FlutterMain.java:48)
E/AndroidRuntime(10162): 	at io.flutter.app.FlutterApplication.onCreate(FlutterApplication.java:24)
E/AndroidRuntime(10162): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1002)
E/AndroidRuntime(10162): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4302)
E/AndroidRuntime(10162): 	at android.app.ActivityThread.access$1300(ActivityThread.java:138)
E/AndroidRuntime(10162): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1264)
E/AndroidRuntime(10162): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(10162): 	at android.os.Looper.loop(Looper.java:137)
E/AndroidRuntime(10162): 	at android.app.ActivityThread.main(ActivityThread.java:4904)
E/AndroidRuntime(10162): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(10162): 	at java.lang.reflect.Method.invoke(Method.java:511)
E/AndroidRuntime(10162): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
E/AndroidRuntime(10162): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
E/AndroidRuntime(10162): 	at dalvik.system.NativeStart.main(Native Method)`

**Comment by LichKing-2234** [comment]
seem like your flutter environment has broken? maybe you can try run `flutter upgrade`?

**Comment by talwarabhimanyu** [comment]
Appreciate your quick responses. I ran `flutter upgrade` and get the same error. One other thing is that in my `build.gradle` I'm using this ndk config (not sure if this is causing an issue):

`ndk {
            abiFilters 'armeabi-v7a'
 }`

**Comment by talwarabhimanyu** [comment]
While I wasn't able to make it run on my LG P875 mobile (Android API level 16), I did manage to run it on another phone with a higher API. Closing this issue.

**Comment by LichKing-2234** [comment]
@talwarabhimanyu Flutter only support API level 17+
