### ISSUE TITLE
How to integrate DeepAR into Agora?

### ISSUE THREAD

**Issue by edwinchanjy** [AgoraIO-Community/Agora-Flutter-Quickstart#199]
I have downloaded DeepAR SDK (native Android) and was trying to integrate it into the Flutter Agora as my project is already written in Dart and I would not like to rewrite it in native. I wonder if it is possible to integrate DeepAR into the Flutter Agora plugin as based on what I understand, the DeepAR SDK makes use of the GLSurfaceView while Flutter Agora plugin is currently not supporting it. 

Thank you.

**Comment by LichKing-2234** [comment]
if the DeepAR SDK does not support flutter, you must write native code with it. you can refer to https://github.com/AgoraIO/Flutter-SDK/issues/183#issuecomment-736271800

**Comment by Anilkumar18** [comment]
@LichKing-2234 I've come to do the same type of integration with Agora and DeepAR. And I don't have a clear view of how the raw data library can be used to integrate with DeepAR library.  

Should I implement my library inside the AgoraRtcRawdataPlugin itself? Or should I do that in the example/android of the library? Can you please give any idea on how to use this plugin to accomplish the task?
