### ISSUE TITLE
Problem on video Flutter-Ios

### ISSUE THREAD

**Issue by ValSbo** [AgoraIO-Community/Agora-Flutter-Quickstart#2]
Hello everyone, i'm developing a Flutter application.
I integrated the Flutter sdk with the app, on android is all ok, on Ios i have a problem: i can join the channel but i can't see the video, there's a black screen.
The app can access on camera and mic.
How can i solve this??

**Comment by plutoless** [comment]
@ValSbo  are you testing on iphone simulator or real device? Camera can not be simulated so if you want to see video you have to connect to a real device.

**Comment by ValSbo** [comment]
@plutoless I'm testing on a real device, i solved it, it was a dependency for views in the Info.plist file.

**Comment by matheusmota3242** [comment]
> @plutoless I'm testing on a real device, i solved it, it was a dependency for views in the Info.plist file.

I'm facing the same issue, but my device is a S9 :/

**Comment by urizeira** [comment]
> dependency for views in the Info.plist

Can you please share how you solved it? i'm facing the same problem

**Comment by LichKing-2234** [comment]
@urizeira maybe you forget to add the `io.flutter.embedded_views_preview` configuration in `info.plist`?

**Comment by urizeira** [comment]
> @urizeira maybe you forget to add the `io.flutter.embedded_views_preview` configuration in `info.plist`?

Yes I did. This solved the issue!

**Comment by BakhtMunirUet** [comment]
@ValSbo can you tell me the dependency in info.plist. Because i am facing the same problem. Agora working on android but black screen on Ios
