### ISSUE TITLE
How to know current user ids in a channel?

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#201]
Is there a way to fetch all the current users in a channel? Or do we have to keep track of this information on our own servers?
- If a user joins in late, it would be nice to know who is already in the channel.

**Comment by LichKing-2234** [comment]
you can refer to 
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174#issuecomment-691664325
