### ISSUE TITLE
Livestreaming the screen of a flutter mobile app

### ISSUE THREAD

**Issue by malithkuruppu** [AgoraIO-Community/Agora-Flutter-Quickstart#202]
I have a flutter mobile app. I want to livestream the activities that I do in the said app.

Is there a way to add live-streaming functionality to the said app and broadcast this into an another custom app and/or to youtube/twitch?

**Comment by LichKing-2234** [comment]
you can refer to the native doc about custom video capture.
https://docs.agora.io/en/Interactive%20Broadcast/custom_video_android?platform=Android
https://docs.agora.io/en/Interactive%20Broadcast/custom_video_android?platform=iOS
