### ISSUE TITLE
Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)

### ISSUE THREAD

**Issue by ahmedJD** [AgoraIO-Community/Agora-Flutter-Quickstart#203]
I need to run agora in onBackgroundMessage with FCM and in order to do that i need to register the plugin class Application 

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService
import com.github.cloudwebrtc.flutter_callkeep.FlutterCallkeepPlugin
import io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin
import io.agora.agora_rtc_engine.AgoraRtcEnginePlugin

class Application : FlutterApplication(), PluginRegistrantCallback {
 
  override fun onCreate() {
    super.onCreate()
    FlutterFirebaseMessagingService.setPluginRegistrant(this)
  }

  override fun registerWith(registry: PluginRegistry?) {
    io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    FlutterCallkeepPlugin.registerWith(registry?.registrarFor("com.github.cloudwebrtc.flutter_callkeep"));
    SharedPreferencesPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin"));    
    AgoraRtcEnginePlugin.registerWith(registry?.registrarFor("io.agora.agora_rtc_engine.AgoraRtcEnginePlugin"));
  }
  
}
how can i do that?

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
