### ISSUE TITLE
xcodebuild[50513:4848187]  DTDeviceKit: deviceType from 00008030-000459E11E42402E was NULL

### ISSUE THREAD

**Issue by sid-best-coder** [AgoraIO-Community/Agora-Flutter-Quickstart#204]
Getting the following errors when trying 'flutter run' on my ios device. Works fine on android.

xcodebuild[50513:4848187]  DTDeviceKit: deviceType from 00008030-000459E11E42402E was NULL
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'permission_handler' from project 'Pods')

ios device version: 14.0.1
xcode version: Xcode 12.2

Complete log:
I followed the steps as described in the README of the project.

$ git clone https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart.git
Cloning into 'Agora-Flutter-Quickstart'...
remote: Enumerating objects: 168, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (110/110), done.
remote: Total 414 (delta 62), reused 126 (delta 44), pack-reused 246
Receiving objects: 100% (414/414), 585.59 KiB | 5.58 MiB/s, done.
Resolving deltas: 100% (131/131), done.

$ cd Agora-Flutter-Quickstart/
$ flutter pub get
Running "flutter pub get" in Agora-Flutter-Quickstart...            1.6s

$ flutter run
Launching lib/main.dart on iPhone in debug mode...
 
Automatically signing iOS for device deployment using specified development team in Xcode project: GM72UGLGZW
Running pod install...                                              4.3s
Warning: Podfile is out of date
  This can cause a mismatched version of Flutter to be embedded in your app, which may result in App Store submission rejection or crashes.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/24641 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Running Xcode build...                                                  
Xcode build done.                                           10.6s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-12-21 14:27:20.301 xcodebuild[50513:4848187]  DTDeviceKit: deviceType from 00008030-000459E11E42402E was NULL
    2020-12-21 14:27:20.483 xcodebuild[50513:4848185]  DTDeviceKit: deviceType from 00008030-000459E11E42402E was NULL
    2020-12-21 14:27:20.483 xcodebuild[50513:4848185]  DTDeviceKit: deviceType from 00008030-000459E11E42402E was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'permission_handler' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'Pods-Runner' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'agora_rtc_engine' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'AgoraRtcEngine_iOS_Crypto' from project 'Pods')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'Flutter' from project 'Pods')
    error: No profiles for 'com.example.agoraFlutterQuickstart' were found: Xcode couldn't find any iOS App Development provisioning profiles
    matching 'com.example.agoraFlutterQuickstart'. Automatic signing is disabled and unable to generate a profile. To enable automatic signing,
    pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')
    warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0
    to 14.2.99. (in target 'Runner' from project 'Runner')

Could not build the precompiled application for the device.

It appears that your application still contains the default signing identifier.
Try replacing 'com.example' with your signing id in Xcode:
  open ios/Runner.xcworkspace

Error launching application on iPhone.

**Comment by LichKing-2234** [comment]
if you want to run on your physical device, you should refer to this doc. (find the `Select a Real Device` title)
https://developer.apple.com/documentation/xcode/running_your_app_in_the_simulator_or_on_a_device

**Comment by sid-best-coder** [comment]
Thanks a lot @LichKing-2234 . That was it :)

For the benefit of others, following are the steps I followed to make this app work on my iphone.
1. Clone the repo
2. Open the ios folder in Xcode. Set Signing & Capabilities.
3. Set the app id and token in settings.dart
4. flutter pub get; flutter run
