### ISSUE TITLE
Audio and video call ringing(ping) before join channel

### ISSUE THREAD

**Issue by wizhob2020** [AgoraIO-Community/Agora-Flutter-Quickstart#206]
Hi Team 

I have successfully integrated the agora audio and video call using channel which is created. NOW PROBLEM is that in recipient side there is no ringing functionality before join the call, for example what's app or other app. Please provide these things in sdk for flutter.

**Comment by LichKing-2234** [comment]
same as https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/207
