### ISSUE TITLE
Video or Audio call ringing

### ISSUE THREAD

**Issue by wizhob2020** [AgoraIO-Community/Agora-Flutter-Quickstart#207]
Hi Team 

I have successfully integrated the agora audio and video call using channel which is created. NOW PROBLEM is that in recipient side there is no ringing functionality before join the call, for example what's app or other app. Please provide these things in sdk for flutter.

**Comment by LichKing-2234** [comment]
You can implement it on your application, why it needs to be added to SDK?

**Comment by wizhob2020** [comment]
Dear @LichKing-2234 

How I can, such as suppose a caller trying to make a call to  receiver , and befor pick the call by receiver  his/her phone should be ringing, and same thing if receiver receive the call we need a acknowledgment for sender phone. So therefore Please explore the function details if exist in sdk. other wise I am doing a humble request to you please make a hint so that I can handle this Sanrio. Because I have stuck along with such requirement.

**Comment by LichKing-2234** [comment]
What do you use to make the call? FCM?

**Comment by wizhob2020** [comment]
Dear @LichKing-2234  

thanks for quick response, actually I am using make a call with channel id, and this channel id passing to other side by a rest api, and if user click corresponding ui which have associated with channel id then make a stubbliest channel between sender and reciever. but I think it's not look good because there is no prier information to reciever. I want to make video call such like other platform provide like ringing the receiver phone  and then pick this call and stabilise this connection.
And as per your hint FCM, How can make it in real scenario. like if I am send a notification to receiver side so how can get receive his/her ack to sender side quietly two way communication. Please help me.

**Comment by LichKing-2234** [comment]
you can use FCM or RTM to send an invitation and play music to ring when the client receives the invitation.

**Comment by kandarp-bhatt** [comment]
There is no specific solution to implement it in Agora SDK but by using another way manually you can achieve this:
 
In FCM, you need to any use real time database or cloud fire store database i.e. Firebase & using that you will get data change listener. 

To maintain the continuous status of the call, you have to manage it from the database. You have to store the current status of that call in the database & update it accordingly. 

For example, when you call to someone at that time you need to change the status of the call. Normal (default status) to Ringing (when another person receive a call). The other person will get the updated listener from firebase as you have updated the status. Then you can start the receive call screen to notify the user with attached audio file. And when that user will receive the call, change the status in the database again - Ringing to Calling & join Agora channel.  

Let me know if you are having any questions with this solution !!

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
