### ISSUE TITLE
Android Display Issue

### ISSUE THREAD

**Issue by mcagrigoktas** [AgoraIO-Community/Agora-Flutter-Quickstart#21]
Does not display videos of other participants on android devices. Even the log panel is not visible.

**Comment by plutoless** [comment]
but works on ios?

**Comment by mcagrigoktas** [comment]
Yes works on iOS

**Comment by plutoless** [comment]
is there any error info on logcat?

**Comment by mcagrigoktas** [comment]
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-65
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-66
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-68
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-70
D/AudioTrack(17145): Client defaulted notificationFrames to 1610 for frameCount 3220
W/AudioTrack(17145): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(17145): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AudioManager(17145): getStreamVolume isRestricted mode = 0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-76
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-78
D/*WEBRTCN*(17145): StartRender: thread started: 536868080
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-83
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-85
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-87
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-88
I/AEC_Delay(17145): aec->knownDelay = 0, knownDelay = 4875, move_elements = -304 (ms)
W/Thread-67(17145): type=1400 audit(0.0:4577): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-90

**Comment by mcagrigoktas** [comment]
I/flutter (17145): agora _getRenderViews
W/lseif.mycollage(17145): type=1400 audit(0.0:4557): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=11930 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "net.dns3"
W/Thread-4(17145): type=1400 audit(0.0:4561): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=11930 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "net.dns4"
W/Thread-4(17145): type=1400 audit(0.0:4562): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=11930 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-6
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-8
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-9
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-10
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-11
W/ResourceType(17145): No package identifier when getting name for resource number 0x00000000
I/zygote64(17145): Do full code cache collection, code=124KB, data=85KB
I/zygote64(17145): After code cache collection, code=107KB, data=61KB
I/flutter (17145): agora _getVideoSession
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-14
I/AGORA_SDK(17145): Surface changed to width 1080 height 2030
D/AudioManager(17145): setSpeakerphoneOn true
D/AudioManager(17145): java.lang.Throwable
D/AudioManager(17145): 	at android.media.AudioManager.setSpeakerphoneOn(AudioManager.java:1265)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.doSetAudioOutputRouting(AudioRoutingController.java:793)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.resetAudioRouting(AudioRoutingController.java:1069)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.access$700(AudioRoutingController.java:29)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController$ControllerStartState.<init>(AudioRoutingController.java:451)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.changeState(AudioRoutingController.java:306)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.access$600(AudioRoutingController.java:29)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController$ControllerBaseState.setState(AudioRoutingController.java:330)
D/AudioManager(17145): 	at io.agora.rtc.internal.AudioRoutingController.startMonitoring(AudioRoutingController.java:741)
D/AudioManager(17145): 	at io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(Native Method)
D/AudioManager(17145): 	at io.agora.rtc.internal.RtcEngineImpl.joinChannel(RtcEngineImpl.java:451)
D/AudioManager(17145): 	at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:101)
D/AudioManager(17145): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
D/AudioManager(17145): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:90)
D/AudioManager(17145): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:234)
D/AudioManager(17145): 	at android.os.MessageQueue.nativePollOnce(Native Method)
D/AudioManager(17145): 	at android.os.MessageQueue.next(MessageQueue.java:331)
D/AudioManager(17145): 	at android.os.Looper.loop(Looper.java:149)
D/AudioManager(17145): 	at android.app.ActivityThread.main(ActivityThread.java:6635)
D/AudioManager(17145): 	at java.lang.reflect.Method.invoke(Native Method)
D/AudioManager(17145): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
D/AudioManager(17145): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
D/*WEBRTCN*(17145): SetRenderAndroidVM
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-21
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-23
W/lseif.mycollage(17145): type=1400 audit(0.0:4565): avc: denied { read } for name="u:object_r:net_dns_prop:s0" dev="tmpfs" ino=11930 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:net_dns_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "net.dns1"
E/libc    (17145): Access denied finding property "net.dns2"
E/libc    (17145): Access denied finding property "net.dns3"
E/libc    (17145): Access denied finding property "net.dns4"
I/flutter (17145): agora _getRenderViews
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17145): Unsupported mime video/divx
W/VideoCapabilities(17145): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(17145): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
I/VideoCapabilities(17145): Unsupported profile 4 for video/mp4v-es
W/Utils   (17145): could not parse long range '175-174'
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17145): Unrecognized profile 2130706434 for video/avc
I/CameraManagerGlobal(17145): Connecting to camera service
W/CameraManagerGlobal(17145): [soar.cts] ignore the status update of camera: 2
W/CameraManagerGlobal(17145): [soar.cts] ignore the status update of camera: 3
W/Binder:17145_4(17145): type=1400 audit(0.0:4569): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=11901 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "camera.aux.packagelist"
E/libc    (17145): Access denied finding property "camera.aux.packagelist"
W/CameraManagerGlobal(17145): ignore the torch status update of camera: 3
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-34
I/zygote64(17145): Do partial code cache collection, code=123KB, data=75KB
I/zygote64(17145): After code cache collection, code=123KB, data=75KB
I/zygote64(17145): Increasing code cache capacity to 512KB
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-38
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-39
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-40
W/Thread-36(17145): type=1400 audit(0.0:4572): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
W/Thread-41(17145): type=1400 audit(0.0:4573): avc: denied { node_bind } for scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:node:s0 tclass=rawip_socket permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-42
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-43
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-44
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-45
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-46
W/Thread-55(17145): type=1400 audit(0.0:4574): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=11901 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "camera.hal1.packagelist"
W/Binder:17145_3(17145): type=1400 audit(0.0:4575): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=11901 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (17145): Access denied finding property "camera.aux.packagelist"
I/FeatureParser(17145): can't find whyred.xml in assets/device_features/,it may be in /system/etc/device_features
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-63
D/AudioManager(17145): getStreamVolume isRestricted mode = 0
D/AudioManager(17145): getStreamVolume isRestricted mode = 0
D/Camera  (17145): Lct package name is com.elseif.mycollage
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-65
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-66
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-68
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-70
D/AudioTrack(17145): Client defaulted notificationFrames to 1610 for frameCount 3220
W/AudioTrack(17145): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(17145): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
D/AudioManager(17145): getStreamVolume isRestricted mode = 0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-76
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-78
D/*WEBRTCN*(17145): StartRender: thread started: 536868080
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-83
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-85
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-87
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-88
I/AEC_Delay(17145): aec->knownDelay = 0, knownDelay = 4875, move_elements = -304 (ms)
W/Thread-67(17145): type=1400 audit(0.0:4577): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-90
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-91
W/Thread-89(17145): type=1400 audit(0.0:4578): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-93
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-94
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-95
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-96
W/Thread-92(17145): type=1400 audit(0.0:4579): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-98
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-99
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-100
W/Thread-97(17145): type=1400 audit(0.0:4580): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-102
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-103
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-104
W/Thread-101(17145): type=1400 audit(0.0:4581): avc: denied { read } for name="stat" dev="proc" ino=4026532075 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:proc_stat:s0 tclass=file permissive=0
E/RtcEngine(17145): onEvent: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: Thread-106

**Comment by plutoless** [comment]
it's a known issue fixed by this PR
we are planning to merge the fix soon. maybe try after we release the fix
https://github.com/AgoraIO/Flutter-SDK/pull/12

**Comment by mcagrigoktas** [comment]
Thanks Im waiting.

**Comment by SasLuca** [comment]
@plutoless Hi, I'm working on a flutter project using Agora SDK and we are planning to release in July on both Android and iOS. Could you give us a timeline on when this PR will be merged so that we can get it to work on Android? Thanks.

**Comment by plutoless** [comment]
the PR will be merged tonight and we will publish a release latest by thursday. @SasLuca

**Comment by plutoless** [comment]
@SasLuca  it's merged and 0.9.7 has been released to fix this.
