### ISSUE TITLE
flutter如何单对单呼叫？

### ISSUE THREAD

**Issue by jb522185660** [AgoraIO-Community/Agora-Flutter-Quickstart#211]
安卓那边这个操作可以执行单对单呼叫
// 获取 RtmCallManager 实例
RtmCallManager = RtmClient.getRtmCallManager();
void inviteCall(final String peerUid, final String channel) {
    //创建 LocalInvitation
    LocalInvitation invitation = RtmCallManager.createLocalInvitation(peerUid);
    invitation.setContent(channel);
    //发送呼叫邀请
    RtmCallManager.sendLocalInvitation(invitation);
}
Flutter 对应是如何实现？

**Comment by yoreland** [comment]
call invitation 是agora rtm sdk的功能这块flutter还没有封装rtm,只能在原生层集成

**Comment by LichKing-2234** [comment]
使用flutter rtm插件
