### ISSUE TITLE
InvalidAppId or JoinChannelRejected

### ISSUE THREAD

**Issue by somavoyager** [AgoraIO-Community/Agora-Flutter-Quickstart#212]
I am working on a flutter project, where I am looking to use voice chat for a group. I have created a project, enabled primary certificate and generated a temporary token.

Here is my code.
 try {
      _engine = await RtcEngine.createWithAreaCode(ApiKeys.AGORA_KEY, areaCode);
      await _engine.enableAudio();
      await _engine.setChannelProfile(ChannelProfile.Game);
      await _engine.setClientRole(ClientRole.Broadcaster);
      await _engine.setEnableSpeakerphone(true);
      _channel = await RtcChannel.create(channelName);
      await this._addListener(_channel);

    if (defaultTargetPlatform == TargetPlatform.android) {
      await [Permission.microphone].request();
    }
    await _channel.setClientRole(ClientRole.Broadcaster);
    await _channel.joinChannel(
        channelName, null, this.userId, ChannelMediaOptions(true, false));

      available = true;
    } catch (err) {
      log('exception occurred when connecting to live audio ${err.toString()}');
    }
 }
 _addListener(RtcChannel channel) {
    String channelId = channel.channelId;
    channel.setEventHandler(RtcChannelEventHandler(error: (errorCode) {
      log('Error reported $channel $errorCode');
    }, joinChannelSuccess: (channel, uid, elapsed) {
      log('joinChannelSuccess $channel $uid $elapsed');
    }, userJoined: (uid, elapsed) {
      log('userJoined ${channel.channelId} $uid $elapsed');
    }, userOffline: (uid, reason) {
      log('userOffline ${channel.channelId} $uid $reason');
    }, leaveChannel: (stats) {
      log('leaveChannel ${channel.channelId} ${stats.toJson()}');
    }));
  }

I am getting either InvalidAppId or JoinChannelRejected error in the call back. I had created a temporary token for a hardcoded channel name.

What am I doing wrong?

**Comment by LichKing-2234** [comment]
you can try our example in sdk folder

**Comment by LichKing-2234** [comment]
I will close this issue, you can reopen it if the issue still exists.
