### ISSUE TITLE
Not able to join channel after getting token from nodejs server

### ISSUE THREAD

**Issue by ishaan-puniani** [AgoraIO-Community/Agora-Flutter-Quickstart#213]
Hello,
I am trying to join channel from flutter application. 
If I generateToken from the website under project in agora.io it works perfectly fine 

but if I generate token using 
https://github.com/AgoraIO-Community/TokenServer-nodejs
or https://www.agora.io/en/blog/how-to-build-a-token-server-for-agora-applications-using-nodejs/
and use the token into my flutter applicartion 
![image](https://user-images.githubusercontent.com/2558553/107162969-fcb2dc80-69a6-11eb-89f0-5b1f04607ef8.png)

It is not able to connect and give error "Access denied finding property "net.dns1"",2,3,4,5 repeatedly.

I have checked https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/172 but not able to find the fix for the issue
Also tried https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/blob/master/lib/src/pages/call.dart but getting same issue.

Any help would be great :)

**Comment by LichKing-2234** [comment]
you can ignore the error `Access denied finding property "net.dns1"`, you can use the token to try our web demo.

https://webdemo.agora.io/agora-web-showcase/examples/Agora-Web-Tutorial-1to1-Web/

**Comment by ishaan-puniani** [comment]
Even though I ignored this error, I am not able to join channel success.

**Comment by plutoless** [comment]
@ishaan-puniani could you pls share the token you generated? and the channel and uid you used to join the channel for this token.

**Comment by LichKing-2234** [comment]
you can refer to `setLogFile` method to get the log file.

I will close this issue, you can reopen it if it still exists.

**Comment by harinderratton** [comment]
I am facing the same issue in React Native Android
I have generated the token from Laravel Server with Subscriber Privilege (2) but not able to join the channel
Note: Audio is coming but video is not coming
