### ISSUE TITLE
How to Generate Automatic token in flutter?

### ISSUE THREAD

**Issue by DaxeshV** [AgoraIO-Community/Agora-Flutter-Quickstart#215]
I am making a project using flutter and currently I'm generating temporary token from dashboard how can I generate token automatically because I'm new with flutter too, so I am not able to understand that part. I saw the documentation but there is nothing for flutter.

**Comment by plutoless** [comment]
@DaxeshV token should be generated from your own server. the client platform all uses the same token mechanism. 
for explanations of token please read https://docs.agora.io/en/Real-time-Messaging/faq/token_usage_generation_description#token-%E5%88%B0%E6%9C%9F%E6%97%B6%E7%9A%84sdk-%E8%A1%8C%E4%B8%BA%E4%B8%8E%E5%BB%BA%E8%AE%AE%E6%93%8D%E4%BD%9C

**Comment by Faisalkc4u** [comment]
@DaxeshV HI, 
I have created a token generator my server with node (package:agora-access-token)
The app is still in development mode also i haven't enable live mode.
Now when am using the token generated which is generated at the server side, am getting Invalid channel Name

**Comment by DaxeshV** [comment]
> @DaxeshV HI,
> I have created a token generator my server with node (package:agora-access-token)
> The app is still in development mode also i haven't enable live mode.
> Now when am using the token generated which is generated at the server side, am getting Invalid channel Name

While you create token pass just 2 thing 
 - uid = 0 and channelName.
 
 Once token generate you can use it for join.

**Comment by DaxeshV** [comment]
> @DaxeshV token should be generated from your own server. the client platform all uses the same token mechanism.
> for explanations of token please read https://docs.agora.io/en/Real-time-Messaging/faq/token_usage_generation_description#token-%E5%88%B0%E6%9C%9F%E6%97%B6%E7%9A%84sdk-%E8%A1%8C%E4%B8%BA%E4%B8%8E%E5%BB%BA%E8%AE%AE%E6%93%8D%E4%BD%9C

Thanks

**Comment by danielgchap** [comment]
The agora token approach is right next to moronic and you very poor documentation in regards to this. Pathetic.

**Comment by Luckymartins3600** [comment]
any update on this still having issues generating tokens for agora
