### ISSUE TITLE
Calling getUserInfoByUid in the userJoined callback throws a null pointer exception

### ISSUE THREAD

**Issue by UCetinkaya94** [AgoraIO-Community/Agora-Flutter-Quickstart#217]
Hi, 

I'm using `_engine.joinChannelWithUserAccount`. When `userJoined` is triggered, I'm calling `_engine.getUserInfoByUid(uid)` to get the user name. This throws the following exception:

`Tried calling: forEach(Closure: (dynamic, dynamic) => Null)`

I think it has to do with the fact that the UserInfo is not available right away when `userJoined` is triggered. What I'm doing right now is to wait a few milliseconds before calling `getUserInfoByUid`, which isn't ideal. 

```dart
await Future.delayed(Duration(milliseconds: 200));
final userInfo = await _engine.getUserInfoByUid(uid);
```

**Comment by LichKing-2234** [comment]
could you pls show the code about the `UserJoined` event?

**Comment by UCetinkaya94** [comment]
> could you pls show the code about the `UserJoined` event?

```dart
 userJoined: (uid, elapsed) async {

  // users is a Map<int, String>
  final users = state.users.copy();
  
  final userInfo = await _engine.getUserInfoByUid(uid);
  
  users[uid] = userInfo.userAccount;
  
  emit(state.copyWith(users: users));
}
```

**Comment by UCetinkaya94** [comment]
@LichKing-2234 I forgot to mention: the exception occurs on the client that is joining a channel with users already in it. Here is a short video:

https://user-images.githubusercontent.com/67158575/109279555-30e92280-781a-11eb-9ae2-24f796be8e2f.mov

**Comment by LichKing-2234** [comment]
you can try this
```
engine.setParameters('{"rtc.sync_user_account_callback": true}');
```

but if you do this, you must join the channel by calling `joinChannelWithUserAccount `.

**Comment by UCetinkaya94** [comment]
@LichKing-2234 It seems to work, thank you!
