### ISSUE TITLE
Audio calls works in One way in Agora Flutter Application

### ISSUE THREAD

**Issue by wytex** [AgoraIO-Community/Agora-Flutter-Quickstart#218]
I have setting up my application with Agora SDK flutter.
I have set up Role as Broadcast and if I talk the other side can hear my voice,
The problem is if the other side talk I can't hear his voice.
I have read documentation But I dindnt find anything related to this issue, when 2 users are in the same channel both of them should talk and each other can hear the voice of the other or I am wrong?

**Comment by LichKing-2234** [comment]
Hi, could you pls share the solution to your issue?
