### ISSUE TITLE
Black Screen issue from Local/Remote sides

### ISSUE THREAD

**Issue by Yahya-khodr** [AgoraIO-Community/Agora-Flutter-Quickstart#220]
This is The error log
  Note: I'm using the CreateWithConfig method since RtcEngine.create is deprecated.
E/MethodChannel#agora_rtc_engine(21216): Failed to handle method call
E/MethodChannel#agora_rtc_engine(21216): java.lang.RuntimeException: NEED TO check rtc sdk init fatal error
E/MethodChannel#agora_rtc_engine(21216):
E/MethodChannel#agora_rtc_engine(21216): 	at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:113)
E/MethodChannel#agora_rtc_engine(21216): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#agora_rtc_engine(21216): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#agora_rtc_engine(21216): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:818)
E/MethodChannel#agora_rtc_engine(21216): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#agora_rtc_engine(21216): 	at android.os.MessageQueue.next(MessageQueue.java:325)
E/MethodChannel#agora_rtc_engine(21216): 	at android.os.Looper.loop(Looper.java:142)
E/MethodChannel#agora_rtc_engine(21216): 	at android.app.ActivityThread.main(ActivityThread.java:7000)
E/MethodChannel#agora_rtc_engine(21216): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#agora_rtc_engine(21216): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/MethodChannel#agora_rtc_engine(21216): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by LichKing-2234** [comment]
your android module is the old version. pls uninstall your app and rerun it.
