### ISSUE TITLE
does it work for web and windows?

### ISSUE THREAD

**Issue by sinadalvand** [AgoraIO-Community/Agora-Flutter-Quickstart#222]
I'm trying to develop an application for Web and Windows by using Agora API, does it work on these platforms?

**Comment by LichKing-2234** [comment]
not support now, we are developing

**Comment by sinadalvand** [comment]
Can you estimate How long it is going to take until being ready?

**Comment by LichKing-2234** [comment]
maybe the end of Q2.

**Comment by sinadalvand** [comment]
nice, so that's near.

thanks for your support.
