### ISSUE TITLE
How to use SDK to engage 40 - 50 users in a video session?

### ISSUE THREAD

**Issue by HassamTalha** [AgoraIO-Community/Agora-Flutter-Quickstart#225]
Hi, this is more like a question. I would like to know how many users can join video session or how can I achieve the engagement of 50 users in a video session. I have searched for it and came to know that 7 users can share video in a group video call. But that answer was outdated and I haven't found anything updated on this.  I need more users. Can I use the live broadcasting example to engage that many users? and can the broadcaster/representative will be able to control the mic and video of all the users. like Zoom call or Microsoft teams call. Thanks

**Comment by plutoless** [comment]
you can have lots of audiences in the room, but only 17 hosts are allowed at same time within a channel. you can contact our support team to raise this limit, but usually there should not be that many people talking in the channel

**Comment by HassamTalha** [comment]
Thank you so much for the information.
