### ISSUE TITLE
Black screen on the local sides

### ISSUE THREAD

**Issue by hutomosaktikartiko** [AgoraIO-Community/Agora-Flutter-Quickstart#228]
This is the log 
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
I/agora_vrp(23497): stuck_watch: sd:372, id:0
I/agora_vrp(23497): Frames out=25. out Fps=12, Total out=459, stream=0, out interv=0, 0, 0, 0, 25, out render time interv=0, 0, 0, 0, 25
E/agora_vrp(23497): Frames replaced by swap=0, stream=0
I/agora_vrp(23497): stuck_watch: fps=12, id=0
I/agora_vrp(23497): stuck_watch: total=25, 0~15=0%, 15~30=0%, 30~40=0%, 40~60=0%, 60~80=32%, 80~110=68%, 110~150=0%, 150~200=0%, 200+=0%, id=0
I/agora_vrp(23497): stuck_watch: interval_distribution=8732540928, sd:382, id:0, avg draw cost:1
I/agora_vrp(23497): Frames rendered=25. Render Fps=12, Total rendered=460, stream=0, draw cost=25, 0, 0, 0, 0, 0, render inter=0, 0, 0, 0, 8, 17, 0, 0, 0
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
W/GENP.0  (23497): type=1400 audit(0.0:108053): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
I/chatty  (23497): uid=10317(com.armadius.starlive) identical 3 lines
W/GENP.0  (23497): type=1400 audit(0.0:108057): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
I/flutter (23497): joined
[log] RoomHOST USER ONE - 1000000300
[log] RoomChannel 77346679ee6daee7
[log] Jumlah diamond sebelum listerner 1006760
[log] Jumlah diamond host id penerima diamond ID#25f9e79432
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x7042c0ba80
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 2 is dropped, handle=0x703e0937c0
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x7042c0ba80
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 2 is dropped, handle=0x703e0937c0
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x7042c0ba80
W/PlatformViewsController(23497): Creating a virtual display of size: [708, 1420] may result in problems(https://github.com/flutter/flutter/issues/2897).It is larger than the device screen size: [720, 1378].
I/BufferQueue(23497): [unnamed-23497-5](this:0x6ff125c000,id:5,api:0,p:-1,c:-1) BufferQueue core=(23497:com.armadius.starlive)
E/libc    (23497): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(23497): [unnamed-23497-5](this:0x6ff125c000,id:5,api:0,p:-1,c:23497) connect(C): consumer=(23497:com.armadius.starlive) controlledByApp=true
E/libc    (23497): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(23497): [unnamed-23497-5](this:0x6ff125c000,id:5,api:0,p:-1,c:23497) setConsumerName: unnamed-23497-5
E/libc    (23497): Access denied finding property "vendor.debug.bq.dump"
I/BufferQueueConsumer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:0,p:-1,c:23497) setConsumerName: SurfaceTexture-0-23497-2
I/BufferQueueConsumer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:0,p:-1,c:23497) setDefaultBufferSize: width=708 height=1420
[log] 1000000300
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 0
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 0
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 2 is dropped, handle=0x703e0937c0
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:1,p:653,c:23497) connect(P): api=1 producer=(653:???) producerControlledByApp=false
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) cancelBuffer: slot 2
D/WindowManager(23497): Add to mViews: DecorView@57915cc[MainActivity], this = android.view.WindowManagerGlobal@1cb6cc3,pkg= com.armadius.starlive
D/ViewRootImpl[MainActivity](23497): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
I/InputTransport(23497): Create ARC handle: 0x704bd33440
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x7042c0ba80
I/SurfaceView(23497): 48508484 visibleChanged:true -> SurfaceHolder.Callback.surfaceDestroyed
D/Surface (23497): Surface::disconnect(this=0x703dd49000,api=1)
D/ViewRootImpl(23497): setSurfaceViewCreated, created:false
D/Surface (23497): Surface::disconnect(this=0x703dd49000,api=-1)
D/SurfaceView(23497): updateScreenMode w:0 h:0 ViewRoot w:708 h:1420
D/SurfaceView(23497): try to resquest 90Hz
D/SurfaceView(23497): updateScreenMode w:0 h:0 ViewRoot w:708 h:1420
D/SurfaceView(23497): try to resquest 90Hz
D/Surface (23497): Surface::disconnect(this=0x703dd47000,api=1)
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:23497) queueBuffer: slot 2 is dropped, handle=0x703e0937c0
D/View    (23497): [Warning] assignParent to null: this = DecorView@e1a5357[MainActivity]
I/InputTransport(23497): Destroy ARC handle: 0x703db58e40
D/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:-1) cancelBuffer: slot 2
E/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:-1) cancelBuffer: BufferQueue has been abandoned
I/Choreographer(23497): Skipped 2 frames!  The application may be doing too much work on its main thread.
[log] RoomHOST USER ONE - 1000000300
[log] RoomChannel 77346679ee6daee7
[log] Jumlah diamond sebelum listerner 1006760
[log] Jumlah diamond host id penerima diamond ID#25f9e79432
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-1](this:0x6ff0ffa000,id:4,api:1,p:653,c:-1) disconnect(P): api 1
D/Surface (23497): Surface::connect(this=0x703dd48000,api=1)
D/mali_winsys(23497): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/Surface (23497): Surface::setBufferCount(this=0x703dd48000,bufferCount=3)
I/SurfaceView(23497): 16424981 visibleChanged:true -> SurfaceHolder.Callback.surfaceCreated
D/ViewRootImpl(23497): setSurfaceViewCreated, created:true
I/SurfaceView(23497): 16424981 surfaceChanged -- format=4 w=708 h=1420 visibleChanged:true -> SurfaceHolder.Callback.surfaceChanged
D/SurfaceView(23497): updateScreenMode w:708 h:1420 ViewRoot w:708 h:1420
D/SurfaceView(23497): try to resquest 60Hz
D/libMEOW (23497): applied 0 plugin for [com.armadius.starlive].
D/Surface (23497): Surface::connect(this=0x703dd49000,api=1)
D/mali_winsys(23497): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/SurfaceView(23497): updateScreenMode w:708 h:1420 ViewRoot w:708 h:1420
D/SurfaceView(23497): try to resquest 60Hz
I/AGORA_SDK(23497): Surface changed to width 708 height 1420
I/Choreographer(23497): Skipped 3 frames!  The application may be doing too much work on its main thread.
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x703e0950c0
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:1,p:653,c:23497) queueBuffer: slot 1 is dropped, handle=0x703e096600
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x703e0950c0
[log] 1000000300
D/SurfaceView(23497): updateScreenMode w:708 h:1420 ViewRoot w:708 h:1420
D/SurfaceView(23497): try to resquest 60Hz
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=1, stream=0
I/BufferQueueProducer(23497): [SurfaceTexture-0-23497-2](this:0x6ff125c000,id:5,api:1,p:653,c:23497) queueBuffer: slot 0 is dropped, handle=0x703e0950c0
E/agora_vrp(23497): replaced by swap before render. gap=71 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=4, stream=0
I/agora_vrp(23497): stuck_watch: sd:595, id:0
I/agora_vrp(23497): Frames out=26. out Fps=13, Total out=485, stream=0, out interv=0, 0, 0, 0, 26, out render time interv=0, 0, 0, 0, 26
E/agora_vrp(23497): replaced by swap before render. gap=70 ms. all replaced by swap=5, stream=0
E/agora_vrp(23497): Frames replaced by swap=5, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=1, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=4, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=5, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=6, stream=0
W/GENP.0  (23497): type=1400 audit(0.0:108062): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
I/chatty  (23497): uid=10317(com.armadius.starlive) identical 3 lines
W/GENP.0  (23497): type=1400 audit(0.0:108066): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=7, stream=0
E/libc    (23497): Access denied finding property "net.dns1"
E/libc    (23497): Access denied finding property "net.dns2"
E/libc    (23497): Access denied finding property "net.dns3"
E/libc    (23497): Access denied finding property "net.dns4"
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=8, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=9, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=10, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=11, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=12, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=13, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=14, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=15, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=16, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=17, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=18, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=19, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=20, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=21, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=22, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=23, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=24, stream=0
I/agora_vrp(23497): stuck_watch: sd:339, id:0
I/agora_vrp(23497): Frames out=25. out Fps=12, Total out=510, stream=0, out interv=0, 0, 0, 0, 25, out render time interv=0, 0, 0, 0, 25
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=25, stream=0
E/agora_vrp(23497): Frames replaced by swap=25, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=1, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=4, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=5, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=6, stream=0
W/GENP.0  (23497): type=1400 audit(0.0:108068): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
I/chatty  (23497): uid=10317(com.armadius.starlive) identical 3 lines
W/GENP.0  (23497): type=1400 audit(0.0:108072): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=7, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=8, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=9, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=76 ms. all replaced by swap=10, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=11, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=12, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=76 ms. all replaced by swap=13, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=14, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=15, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=16, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=74 ms. all replaced by swap=17, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=18, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=19, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=20, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=21, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=22, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=23, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=24, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=25, stream=0
I/agora_vrp(23497): stuck_watch: sd:426, id:0
I/agora_vrp(23497): Frames out=26. out Fps=12, Total out=536, stream=0, out interv=0, 0, 0, 0, 26, out render time interv=0, 0, 0, 0, 26
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=26, stream=0
E/agora_vrp(23497): Frames replaced by swap=26, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=1, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=76 ms. all replaced by swap=4, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=5, stream=0
W/GENP.0  (23497): type=1400 audit(0.0:108077): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=6, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=7, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=8, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=9, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=10, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=11, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=12, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=13, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=14, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=15, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=16, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=17, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=18, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=76 ms. all replaced by swap=19, stream=0
W/madius.starliv(23497): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
W/madius.starliv(23497): Accessing hidden method Lsun/misc/Unsafe;->putInt(Ljava/lang/Object;JI)V (greylist, linking, allowed)
W/madius.starliv(23497): Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
W/madius.starliv(23497): Accessing hidden method Lsun/misc/Unsafe;->getLong(Ljava/lang/Object;J)J (greylist,core-platform-api, linking, allowed)
W/madius.starliv(23497): Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=20, stream=0
[log] Jumlah diamond sebelum listerner 1006760
[log] Jumlah diamond host id penerima diamond ID#25f9e79432
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=21, stream=0
[log] RoomHOST USER ONE - 1000000300
[log] RoomChannel 77346679ee6daee7
[log] 1000000300
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=22, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=23, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=77 ms. all replaced by swap=24, stream=0
I/agora_vrp(23497): stuck_watch: sd:492, id:0
I/agora_vrp(23497): Frames out=25. out Fps=13, Total out=561, stream=0, out interv=0, 0, 0, 0, 25, out render time interv=0, 0, 0, 0, 25
E/agora_vrp(23497): replaced by swap before render. gap=85 ms. all replaced by swap=25, stream=0
E/agora_vrp(23497): Frames replaced by swap=25, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=86 ms. all replaced by swap=1, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=73 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=4, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=86 ms. all replaced by swap=5, stream=0
W/GENP.0  (23497): type=1400 audit(0.0:108083): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
W/GENP.0  (23497): type=1400 audit(0.0:108084): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=6, stream=0
E/libc    (23497): Access denied finding property "net.dns1"
E/libc    (23497): Access denied finding property "net.dns2"
E/libc    (23497): Access denied finding property "net.dns3"
E/libc    (23497): Access denied finding property "net.dns4"
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=7, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=8, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=9, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=10, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=11, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=12, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=70 ms. all replaced by swap=13, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=14, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=15, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=16, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=17, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=18, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=19, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=20, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=21, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=81 ms. all replaced by swap=22, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=75 ms. all replaced by swap=23, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=24, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=79 ms. all replaced by swap=25, stream=0
I/agora_vrp(23497): stuck_watch: sd:528, id:0
I/agora_vrp(23497): Frames out=26. out Fps=13, Total out=587, stream=0, out interv=0, 0, 0, 0, 26, out render time interv=0, 0, 0, 0, 26
E/agora_vrp(23497): replaced by swap before render. gap=82 ms. all replaced by swap=26, stream=0
E/agora_vrp(23497): Frames replaced by swap=26, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=1, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=80 ms. all replaced by swap=2, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=78 ms. all replaced by swap=3, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=83 ms. all replaced by swap=4, stream=0
W/GENP.0  (23497): type=1400 audit(0.0:108089): avc: denied { search } for name="thermal" dev="sysfs" ino=30976 scontext=u:r:untrusted_app:s0:c61,c257,c512,c768 tcontext=u:object_r:sysfs_therm:s0 tclass=dir permissive=0
E/agora_vrp(23497): replaced by swap before render. gap=84 ms. all replaced by swap=5, stream=0
E/agora_vrp(23497): replaced by swap before render. gap=74 ms. all replaced by swap=6, stream=0

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by hutomosaktikartiko** [comment]
yes i have tried that

**Comment by LichKing-2234** [comment]
The example is working. have you modified some code?

**Comment by hutomosaktikartiko** [comment]
I haven't tried modifying it yet, I'll start now by creating a new project. please don't close this issue, I will confirm if find this problem again.

**Comment by LichKing-2234** [comment]
okay, maybe it causes by the camera permission?

**Comment by hutomosaktikartiko** [comment]
I don't think that's. in my project I created a broadcast channel, when no user joins the room (only the host) it's no problem, but when a user joins, the host screen goes black and strangely the video from the camera host is still alive in the user screen.
