### ISSUE TITLE
flutter作为主工程跑真机没问题，flutter当做模块集成到现有工程里就报错，如下，不知道为何？

### ISSUE THREAD

**Issue by fankfank** [AgoraIO-Community/Agora-Flutter-Quickstart#23]
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method create on channel agora_rtc_engine)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:7)
<asynchronous suspension>
#1      AgoraRtcEngine.create (package:agora_rtc_engine/agora_rtc_engine.dart:213:27)
<asynchronous suspension>
#2      _RTCConnectedState._initAgoraRtcEngine (package:smartnote_flutter/rtc/rtc_connected.dart:105:26)
<asynchronous suspension>

现有原生工程里已集成了RTM和RTC，RTC已注释，求解。

**Comment by plutoless** [comment]
作为模块集成是指？

**Comment by fankfank** [comment]
现有iOS工程集成flutter版的RTC。

**Comment by fankfank** [comment]
appdelegate里注册了flutter插件：GeneratedPluginRegistrant.register(with: self)
GeneratedPluginRegistrant里注册了[AgoraRtcEnginePlugin registerWithRegistrar:[registry registrarForPlugin:@"AgoraRtcEnginePlugin"]]; agora插件。当做模块集成也没别的生命周期方法需要调用好像？

**Comment by fankfank** [comment]
iOS工程里同时集成RTC和RTM，RTC里的房间内消息和RTM的房间内消息冲突吗？

**Comment by plutoless** [comment]
这边可以发个复现问题的最小demo给我我看下吗？

**Comment by fankfank** [comment]
集成在主项目里遇到的问题，不是demo...

**Comment by plutoless** [comment]
我知道，我的意思是你弄个简单的项目，然后把这个作为模块集成进去复现下发给我我看下。。
