### ISSUE TITLE
Thanks with your project.

### ISSUE THREAD

**Issue by vovskill** [AgoraIO-Community/Agora-Flutter-Quickstart#235]
Thank you for your github agora project.
This helps me a lot.
I did 'flutter run' with the Android stuido emulator (android version is 11) but the emulator shows only black screen after join the channel.
Please help me.
Please let me know to fix this issue

**Comment by vovskill** [comment]
Sorry
I found this issue fixed in the past.
Thank you

**Comment by LichKing-2234** [comment]
cloud you pls share your solution?
