### ISSUE TITLE
PlatformException (PlatformException(4, not supported, null, null))

### ISSUE THREAD

**Issue by swarupbhanjachowdhury** [AgoraIO-Community/Agora-Flutter-Quickstart#238]
PlatformException (PlatformException(4, not supported, null, null))

![image](https://user-images.githubusercontent.com/55395995/130688770-ecabb718-e9e4-4383-9af8-b92824a9372d.png)

please help me with this issue, I'm stuck here

**Comment by LichKing-2234** [comment]
client role only support in live broadcasting channel profile.
