### ISSUE TITLE
为何 _addRenderView 中的 finished 会是 null ?

### ISSUE THREAD

**Issue by coooooof** [AgoraIO-Community/Agora-Flutter-Quickstart#24]
当我作为一个观众进入某个直播间时，_addRenderView 中的 finished 打印出来显示 

`Closure: (int) => Null`

因此后续步骤都不执行了

**Comment by Matrixbirds** [comment]
请问是哪个平台？ @coooooof

**Comment by coooooof** [comment]
> 请问是哪个平台？ @coooooof
> 麻烦提供一下flutter doctor的结果还有复现的环境

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.17763.615], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.36.1)
[√] Connected device (1 available)

• No issues found!

插件版本 agora_rtc_engine: ^0.9.8；

已配置好签名的 release 版 apk；

所有函数与 qiuckstart 的一致，除了 app id 外，未修改参数；

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
