### ISSUE TITLE
Agora example: `RtcRemoteView.SurfaceView` shows black screen

### ISSUE THREAD

**Issue by HasanAlyazidi** [AgoraIO-Community/Agora-Flutter-Quickstart#240]
Hello,

The issue is remote user's view `RtcRemoteView.SurfaceView(uid: remoteUid)` is not showing anything while `RtcLocalView.SurfaceView()` is working as intended.

### Screenshot
From the example in `Agora-Flutter-Quickstart`

![image](https://user-images.githubusercontent.com/7901330/134914231-f0156d6f-4a97-48e0-a556-9ba671546058.png)

### Expected Behavior
Local and remote views to be shown for anyone connects to the channel

### How to reproduce
1. Run the example in `Agora-Flutter-Quickstart`
2. Select `ClientRole.Broadcaster` for both users
3. Join

Thank you for your effort and time

**Comment by LichKing-2234** [comment]
this demo is out of date, pls refer to the example in the SDK repo.
