### ISSUE TITLE
cannot join channel after some elapsed time , we can only join in fix time

### ISSUE THREAD

**Issue by sadaqatkarimi** [AgoraIO-Community/Agora-Flutter-Quickstart#242]
cannot join channel after some elapsed time , we can only join in fix time . we not join channel after elapsed that fix time. how i fix the issue?

**Comment by LichKing-2234** [comment]
have you tried our example?

**Comment by sadaqatkarimi** [comment]
yes i use example and i use server to get token , some time we can join channel but some time we are unable to join channel

**Comment by LichKing-2234** [comment]
token has expired time, pls double check it.

**Comment by sadaqatkarimi** [comment]
solve i used one digit number in uid, if you used in uid greater than one digit than its not working
