### ISSUE TITLE
How do i make the video call one way from one to many

### ISSUE THREAD

**Issue by nsmith1024** [AgoraIO-Community/Agora-Flutter-Quickstart#25]
Hello,

Im using your video chat example, created a room and the video is working, but its two way video.

I only want the video to go from the sender to many others in the room, but one way only.

Is there a way to do that?

Thanks

**Comment by plutoless** [comment]
assuming you are using live channel profile, you can use setRole/setClientRole function to set audience role for devices which you want to listen only.

**Comment by nsmith1024** [comment]
Can you show code how to do that because i sont see any method called setrole or setclientrole anywhere

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Flutter-SDK/blob/750c3fc85c66e950d42fb385969c2aad2b2a3770/lib/agora_rtc_engine.dart#L246

**Comment by pgajdhar** [comment]
any example on it ??

**Comment by plutoless** [comment]
@pgajdhar  just change setClientRole in current example to set yourself as an audience and that's it.

**Comment by usamaomar** [comment]
where should I set setClientRole I added it inside '_initAgoraRtcEngine' method and still not working is there any example, please

**Comment by usamaomar** [comment]
> any example on it ??

did you find a solution yet

**Comment by plutoless** [comment]
@usamaomar please show the code how you are calling the api. or you can upload your app project here so that i can take a look why it's not working.

**Comment by usamaomar** [comment]
@plutoless `Future<void> initialize() async {
    if (APP_ID.isEmpty) {
      setState(() {
        _infoStrings.add(
          'APP_ID missing, please provide your APP_ID in settings.dart',
        );
        _infoStrings.add('Agora Engine is not starting');

      });
      return;
    }

    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.setParameters('''
    {\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster); // this line 
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
  }` i add this lien setClientRole befure joinChannel only is there something else i have to do

**Comment by LichKing-2234** [comment]
@usamaomar please setChannelProfile LiveBroadcasting before setClientRole
`AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);`

**Comment by usamaomar** [comment]
@LichKing-2234 
what I really want is to provide is a Broadcaster who will have the ability to open a video stream (his screen will have only one video streaming for himself ) and an Audience (where they can watch the Broadcaster only in their screen without splitting the screen ) I have added the code like this 
using state if the first device is a Broadcaster or not but what I got is split screens on bothe devices streaming for both side this is the code :

`
 _addAgoraEventHandlers();
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.setParameters('''
    {\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
    if(widget.isBroadcaster) {
      await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster); // this line
      await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
    }else{
      await AgoraRtcEngine.setChannelProfile(ChannelProfile.Communication);
      await AgoraRtcEngine.setClientRole(ClientRole.Audience); // this line
      await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
    }
`
inside initialize method

**Comment by LichKing-2234** [comment]
both setChannelProfile to LiveBroadcasting
`AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);`
just change ClientRole
```
if(widget.isBroadcaster){
    AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
}else{
    AgoraRtcEngine.setClientRole(ClientRole.Audience);
}
```

**Comment by usamaomar** [comment]
@LichKing-2234 
Thank you but on the Broadcaster yes I can see my self only as a Broadcaster now on the other side I still see a split-screen is there a way to show me on Audience side  the Broadcaster streaming-only 
this is the code 

`
 if(widget.isBroadcaster) {
      await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster); // this line
    }else{
      await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      await AgoraRtcEngine.setClientRole(ClientRole.Audience); // this line
    }
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
`

**Comment by LichKing-2234** [comment]
if you are audience

dont init AgoraRenderWidget with local

**Comment by usamaomar** [comment]
@LichKing-2234 
yes I removed the local: true, from  
`AgoraRenderWidget(0,  preview: true), `
and also tried to change it to 
`AgoraRenderWidget(0, local: false, preview: true),`
the screen is split but it doesn't show the streaming of my device it shows a black screen and the other broadcaster streaming so is there a way to show the other  broadcaster streaming without splitting the screen thank you

**Comment by LichKing-2234** [comment]
sorry, my mistake, it should be removed

**Comment by LichKing-2234** [comment]
if client role is broadcaster

you can init AgoraRenderWidget with local

**Comment by usamaomar** [comment]
@LichKing-2234 
I have removed the method like this but it shows me an error 
`
List<Widget> _getRenderViews() {
    
    final list = [
    
    ];
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
  }
`
the error :
type 'List<dynamic>' is not a subtype of type 'List<Widget>'
and also i tryed to change it like this 

  List<Widget> _getRenderViews() {
    
    final list = [
      AgoraRenderWidget(0),
    ];
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
  }
but still there is a split screen of the broadcaster streaming and a black one i need to show the 
 broadcaster streaming only on the Audience side thanks alot for helping me

**Comment by LichKing-2234** [comment]
try this
```
List _getRenderViews() {
    List<AgoraRenderWidget> list = List();
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
}
```

**Comment by usamaomar** [comment]
@LichKing-2234 
Working !! 
Thanks a lot, it's working now so what I did for other developers who have the same issue is this 
first: create a boolean state to switch between users types if its Broadcaster or Audience then add this line inside _initAgoraRtcEngine() function 

if(widget.isBroadcaster) {
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster); 
}else{
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await AgoraRtcEngine.setClientRole(ClientRole.Audience); // this line
}
await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);

then replace this line inside _getRenderViews 
final list = [
      AgoraRenderWidget(0, local: true, preview: true),
    ];
whith this 
List<AgoraRenderWidget> list = List();
if you are an Audience 
and thats it should work now thank you for helping
