### ISSUE TITLE
White screen issue while switching between full and split screen during video call.

### ISSUE THREAD

**Issue by bzkhan96** [AgoraIO-Community/Agora-Flutter-Quickstart#251]
we've tested it with android 12 and android 13, what we have found is, white screen comes more frequently in android 13 as compare to android 12. need your kind support. Thanks in advance.

**Comment by LichKing-2234** [comment]
which version of the SDK you used, you can create an issue to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues, I will close this issue, thanks.
