### ISSUE TITLE
Build failed due to use of deprecated Android v1 embedding.

### ISSUE THREAD

**Issue by vickyone0** [AgoraIO-Community/Agora-Flutter-Quickstart#252]
the version and code you provide in this example is not working good now .please try to add a new version.I take the updated plan from your website. video call is important for my  project.so fix asap
![Screenshot (50)](https://user-images.githubusercontent.com/101127083/209503456-9d6ad9a8-43b8-430f-b60a-c5eda3a85e92.png)

**Comment by LichKing-2234** [comment]
Pls refer to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example
