### ISSUE TITLE
having a same issue with flutter 3.7.0 @rlee1990 @codesundar

### ISSUE THREAD

**Issue by temoorx** [AgoraIO-Community/Agora-Flutter-Quickstart#253]
@rlee1990 @codesundar 
please remove this code from your MainActivity
`GeneratedPluginRegistrant.registerWith(flutterEngine)`
new version of flutter will run this function by itself, I think it's a bug of flutter
Tips: keep flutterEmbedding to v2, when you run flutter, the generated file will change

_Originally posted by @LichKing-2234 in https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/53#issuecomment-568825611_

**Comment by LichKing-2234** [comment]
Thanks for your comments, this repo is out of date, pls migrate to https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/tree/main/example
