### ISSUE TITLE
I have integrated Agora in Flutter on iOS and Android. Is there an Agora demo for Flutter Web?

### ISSUE THREAD

**Issue by vikramkapoor** [AgoraIO-Community/Agora-Flutter-Quickstart#26]

**Comment by plutoless** [comment]
Nope. Flutter web is still in technical preview phase, it does not support any advanced features so maybe you need to wait for that.

**Comment by vikramkapoor** [comment]
I have rest of my application working in flutter_web. Is there another option available to enable Video chat between web and flutter Android and iOS applications using Agora plugin? E.g. Would using Agora JS SDK in the webapp enable it? Thanks.
Vikram
    On Thursday, August 22, 2019, 11:00:54 AM PDT, Qianze Zhang <notifications@github.com> wrote:  
 
 
Nope. Flutter web is still in technical preview phase, it does not support any advanced features so maybe you need to wait for that.

**Comment by plutoless** [comment]
yes we do have websdk which can interop with android/ios native sdk

**Comment by vikramkapoor** [comment]
Thanks. I was able to integrate websdk into the flutter web app and it works fine.

**Comment by ir2pid** [comment]
@vikramkapoor can you mention how you integrated the websdk into flutter web app.
