### ISSUE TITLE
我下载了demo 并且替换了在 https://dashboard.agora.io上注册的appid 但是demo跑不起来。

### ISSUE THREAD

**Issue by dioig** [AgoraIO-Community/Agora-Flutter-Quickstart#28]
![image](https://user-images.githubusercontent.com/55091253/64612770-3163e280-d407-11e9-92b7-15aec69ee81a.png)
这是我在官网注册的appid
![image](https://user-images.githubusercontent.com/55091253/64612829-50fb0b00-d407-11e9-93b7-d0dbbd0528ea.png)
我替换了appid并且直接在真机上运行了demo
下边是打印的run的 log
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...
I/Choreographer(17701): Skipped 44 frames!  The application may be doing too much work on its main thread.
Syncing files to device CPH1801...
E/CheckPermission(17701): _bluetooth code = 1 
E/CheckPermission(17701): _bluetooth code = 3 
E/CheckPermission(17701): camera-code= 1
I/AGORA_SDK(17701): Surface changed to width 720 height 599
I/Choreographer(17701): Skipped 4 frames!  The application may be doing too much work on its main thread.
D/AudioManager(17701): setSpeakerphoneOn on=true from com.example.agoraflutterquickstart
D/*WEBRTCN*(17701): SetRenderAndroidVM
D/AudioManager(17701): setSpeakerphoneOn keys: get_speaker_authority=com.example.agoraflutterquickstart mAuthoriyStr = true
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
W/Utils   (17701): could not parse long range '175-174'
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17701): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(17701): Unrecognized profile/level 0/3 for video/mpeg2
W/VideoCapabilities(17701): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(17701): Unsupported mime video/x-ms-wmv
W/VideoCapabilities(17701): Unsupported mime video/wvc1
W/VideoCapabilities(17701): Unsupported mime video/wvc1
W/VideoCapabilities(17701): Unsupported mime video/divx
W/VideoCapabilities(17701): Unsupported mime video/divx311
W/VideoCapabilities(17701): Unsupported mime video/divx4
W/VideoCapabilities(17701): Unsupported mime video/mp4v-esdp
I/VideoCapabilities(17701): Unsupported profile 4 for video/mp4v-es
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(17701): Unrecognized profile 2130706434 for video/avc
I/CameraManagerGlobal(17701): Connecting to camera service
E/CheckPermission(17701): camera-code= 9
E/CheckPermission(17701): camera-code= 6
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 8
E/CheckPermission(17701): camera-code= 8
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
I/Choreographer(17701): Skipped 5 frames!  The application may be doing too much work on its main thread.
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
D/Camera  (17701): mHypnusCtrl is true
E/CheckPermission(17701): camera-code= 3
I/AGORA_SDK(17701): Surface changed to width 720 height 1132
E/OpenGLRenderer(17701): hwui_debug::CanvasContext createSurface sur=0x0, isValid =0
I/Choreographer(17701): Skipped 5 frames!  The application may be doing too much work on its main thread.
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 11
E/CheckPermission(17701): camera-code= 10
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 1
E/CheckPermission(17701): camera-code= 2
E/CheckPermission(17701): real_camera-code= 2
E/CheckPermission(17701): real_camera-code= 11
E/CheckPermission(17701): real_camera-code= 10
E/CheckPermission(17701): real_camera-code= 3
E/CheckPermission(17701): real_camera-code= 5
E/OpenGLRenderer(17701): hwui_debug::CanvasContext createSurface sur=0x0, isValid =0
E/CheckPermission(17701): real_camera-code= 11
E/CheckPermission(17701): real_camera-code= 11
D/*WEBRTCN*(17701): StartRender: thread started: 1915065424
W/IInputConnectionWrapper(17701): finishComposingText on inactive InputConnection
不知道为何我手机运行后进去里边没有任何提示
![image](https://user-images.githubusercontent.com/55091253/64612970-9f100e80-d407-11e9-9ee2-50f19c5be975.png)
我用的是 agora_rtc_engine: 0.9.7这个版本的

**Comment by plutoless** [comment]
跑不起来是什么意思？你截的图好像是跑起来的？

**Comment by dioig** [comment]
感谢回复！！！ 
是这样的 一般创建成功会有这个提示类似下边这个界面吧
![image](https://user-images.githubusercontent.com/55091253/64618064-23678f00-d412-11e9-9f88-a27738588e08.png)
我这边一般都是没有提示，要么就是报错error 17 或者onError 110
![IMAGE 2019-09-10 21:31:26](https://user-images.githubusercontent.com/55091253/64618169-5873e180-d412-11e9-8914-90dd91a1c515.jpg)

**Comment by plutoless** [comment]
110的意思是token无效。从你dashboard的界面看你应该打开了安全证书，这种情况下可以在dashboard生成一个临时token，然后作为joinChannel的第一个参数传入

**Comment by dioig** [comment]
![image](https://user-images.githubusercontent.com/55091253/64618622-2ca52b80-d413-11e9-8a1a-4d94b12f39fa.png)
我这边加上token了但是他有报错101了

**Comment by dioig** [comment]
![IMAGE 2019-09-10 21:40:39](https://user-images.githubusercontent.com/55091253/64618862-a2a99280-d413-11e9-823b-891202236803.jpg)
这个是截图

**Comment by plutoless** [comment]
token，不是appid，你看你dashboard上，应该有个生成临时Token的按钮

**Comment by dioig** [comment]
大佬 可以了
![image](https://user-images.githubusercontent.com/55091253/64619646-fff21380-d414-11e9-94f8-b50c6940389c.png)
这个是语音通话，
请问视频通话有demo么

**Comment by dioig** [comment]
话说有木有官方的这个api啊。。。好多方法不知道怎么用的

**Comment by plutoless** [comment]
这本来就是视频通话。。
接口可以参考文档https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/oc/docs/headers/Agora-Objective-C-API-Overview.html
基本和Native一致的

**Comment by dioig** [comment]
🙏我试下
