### ISSUE TITLE
能请教下关于go后台生成token的问题么

### ISSUE THREAD

**Issue by dioig** [AgoraIO-Community/Agora-Flutter-Quickstart#29]
我这边后台 生成token加入频道的时候报错110根据大佬你上次提示应该是token无效
这是后台 go的代码
![image](https://user-images.githubusercontent.com/55091253/64782460-d8778400-d597-11e9-9fcb-ad65a05a500b.png)

这是他生成的token
![image](https://user-images.githubusercontent.com/55091253/64782508-f04f0800-d597-11e9-94b3-75e00051ce79.png)
不知道为何他的token比我之前用的临时token还要长了点，请问是不是他生成token的代码那里有问题啊

**Comment by plutoless** [comment]
麻烦发一个你通过go版本生成的token给我看一下

**Comment by plutoless** [comment]
token最长1天肯定会过期，所以只发token的话不用担心

**Comment by dioig** [comment]
> 麻烦发一个你通过go版本生成的token给我看一下

        "channel":"c435669292e5d3ebc2121ba1347625d0",
        "token":"00679ac8152c1394babaf20f341ad76e04cIAD9opWbCJSctfXMlwiB8yb3UIK4VCBQGgY8FQyOcCY/0Chk6Mg5celxIgDE0OgDdrWAXQQAAQAAAAAAAgAAAAAAAwAAAAAABAAAAAAA",
        "uid":98165224717

这是他的三个参数， 不知道为啥他的token中间有个/

**Comment by dioig** [comment]
大神忙不忙阿。。。

**Comment by plutoless** [comment]
@dioig  我们的uid是uint32的，你这个uid明显超了，所以不行，生成token的时候如果uid设0就是不检查uid，所以可以

**Comment by dioig** [comment]
> @dioig 我们的uid是uint32的，你这个uid明显超了，所以不行，生成token的时候如果uid设0就是不检查uid，所以可以

哦 了解
