### ISSUE TITLE
加入频道后一直弹出bug信息

### ISSUE THREAD

**Issue by dioig** [AgoraIO-Community/Agora-Flutter-Quickstart#31]
![image](https://user-images.githubusercontent.com/55091253/65325603-ea81a400-dbe1-11e9-9f4f-f3355bbdad40.png)
大神 这个是我加入频道开始视频聊天后 debug一直打印的数据，
我的版本是  agora_rtc_engine: 1.0.0
顺便说下之前的那个 加入频道 uid必须是0否则 创建的频道别人加入不进来
不知道为何啊。。。
![image](https://user-images.githubusercontent.com/55091253/65326577-64b32800-dbe4-11e9-9d63-7abd369c35a1.png)

**Comment by dioig** [comment]
而且这个报错信息一直打印，那些 oppo vivo手机 一会儿就扛不住 崩掉了一开始能视频，过一会儿就error 17了

**Comment by plutoless** [comment]
这个错误看起来不是我们sdk的，另外如果创建的频道其他人加不进来，可能token算的和加入的uid不匹配

**Comment by dioig** [comment]
> 这个错误看起来不是我们sdk的，另外如果创建的频道其他人加不进来，可能token算的和加入的uid不匹配

好的
