### ISSUE TITLE
not able to get second screen of the video

### ISSUE THREAD

**Issue by tassidondup** [AgoraIO-Community/Agora-Flutter-Quickstart#32]
the app works fine on individual device. i tried to run the app on two device at the same time so that the video call could be test. i could join in the channel created from one device in the second device but the video screen of the second device is not showing up. the two devices connected are iphone 7 and lenovo android phone. Any idea what that could be. below are the error showing in the terminal.
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 6 is dropped, handle=0x7f42a041e0
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 4 is dropped, handle=0x7f7635d380
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 0 is dropped, handle=0x7f14bf85e0
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 2 is dropped, handle=0x7f14bf8680
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 6 is dropped, handle=0x7f42a041e0
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: fps=28.60 dur=1014.09 max=76.89 min=4.86
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 4 is dropped, handle=0x7f7635d380
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 0 is dropped, handle=0x7f14bf85e0
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 2 is dropped, handle=0x7f14bf8680
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 6 is dropped, handle=0x7f42a041e0
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 4 is dropped, handle=0x7f7635d380
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 0 is dropped, handle=0x7f14bf85e0
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 2 is dropped, handle=0x7f14bf8680
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 6 is dropped, handle=0x7f42a041e0
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 4 is dropped, handle=0x7f7635d380
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 0 is dropped, handle=0x7f14bf85e0
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 2 is dropped, handle=0x7f14bf8680
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 6 is dropped, handle=0x7f42a041e0
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 4 is dropped, handle=0x7f7635d380
I/CameraFramework( 4992): handleMessage: 16
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 0 is dropped, handle=0x7f14bf85e0
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 2 is dropped, handle=0x7f14bf8680
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 1 is dropped, handle=0x7f42a04000
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 5 is dropped, handle=0x7f427fd340
I/CameraFramework( 4992): handleMessage: 16
I/BufferQueueProducer( 4992): [SurfaceTexture-42-4992-3](this:0x7f5d9ec400,id:3,api:4,p:325,c:4992) queueBuffer: slot 3 is dropped, handle=0x7f427fad20

**Comment by ykaito21** [comment]
@tassidondup , Did you solve the problem?
I'm facing the same issue.
