### ISSUE TITLE
flutter 版的语音通话功能 api在哪里查看呢

### ISSUE THREAD

**Issue by dioig** [AgoraIO-Community/Agora-Flutter-Quickstart#33]
我现在使用语音通话只能用视频通话的api了，视频逻辑那些大部分都不能该，否则就会报错了。。。 请问下能提供下 flutter 版的 语音通话的api么 大神。。。
![image](https://user-images.githubusercontent.com/55091253/65937705-53271700-e453-11e9-8c5d-6b30d174ad34.png)

有时候进去会报这个 
W/SettingsInterface(17412): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
或者是这种的
W/ServiceManager(27791): Permission failure: android.permission.READ_PHONE_STATE from uid=10291 pid=27791
E/CheckPermission(27791): Permission Denial: can't access location pid=27791, uid=10291
W/Settings(27791): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.

**Comment by Matrixbirds** [comment]
检查一下你的权限相关配置 比如配置文件和app授权

**Comment by dioig** [comment]
> 检查一下你的权限相关配置 比如配置文件和app授权

可以了大佬，就是能提供下官方api么嘛。 还有那些连麦，视频这些能api功能能考虑提供下么，有这些需求的公司很多的。

**Comment by plutoless** [comment]
https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/java/index.html
官方文档，接口基本和flutter sdk一致

**Comment by dioig** [comment]
> https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/java/index.html
> 官方文档，接口基本和flutter sdk一致

了解了，  大神。
