### ISSUE TITLE
so many repeat errors, how to avoid;

### ISSUE THREAD

**Issue by wanjm** [AgoraIO-Community/Agora-Flutter-Quickstart#36]
there are so many following errors repeatly; is there anything wrong with my code, how to avoid it;

D/*LowLatencyEvent*(20825): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (20825): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640

**Comment by Matrixbirds** [comment]
Please provide your platform, mobile info and errors log here. I will check it with our teammate.

**Comment by wanjm** [comment]
mobile is 'honor 10 android 9';
logs has already pasted in the first post, the two line printed very fast repeated; many many such errors;

**Comment by wanjm** [comment]
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0
I/GRALLOC (30391): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200,  uStride: 640
D/*LowLatencyEvent*(30391): failed to ReadFd(0, 0) return 8, expected 16, errno 0

**Comment by zanesc** [comment]
I get this one as well, it's really annoying as I can't easily see any of my other logs:

`I/GRALLOC (20825): LockFlexLayout: baseFormat: 11, yStride: 640, ySize: 307200, uOffset: 307200, uStride: 640`

**Comment by plutoless** [comment]
@zanesc 
https://stackoverflow.com/questions/55848649/asking-camera-permission-for-webview-at-runtime
does this ring your bell? looks like a camera permission issue?
