### ISSUE TITLE
怎么实现类似于微信视频通话可以呼叫对方而不是加入频道的形式呢

### ISSUE THREAD

**Issue by YinJone** [AgoraIO-Community/Agora-Flutter-Quickstart#37]
怎么实现类似于微信视频通话可以呼叫对方而不是加入频道的形式呢

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Advanced-Video/tree/master/Calling-Interface

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
