### ISSUE TITLE
getAudioMixingCurrentPosition  无法返回int数据问题

### ISSUE THREAD

**Issue by hufu4635** [AgoraIO-Community/Agora-Flutter-Quickstart#39]
getAudioMixingCurrentPosition  返回的是void   怎么得到类似android 平台返回的int值

**Comment by plutoless** [comment]
应该是个bug，我们下周有空看一下，或者你能不能提个PR帮我们修一下？

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
