### ISSUE TITLE
[Flutter] Recording Broadcast stream

### ISSUE THREAD

**Issue by fvisticot** [AgoraIO-Community/Agora-Flutter-Quickstart#4]
Is is possible with Flutter SDK to record "somewhere" the broadcasted Video ?

**Comment by plutoless** [comment]
agora has its recording sdk to do this job. you can rely on here for the docs, https://docs.agora.io/en/Recording/product_recording?platform=All%20Platforms

**Comment by fvisticot** [comment]
Awesome !
Does it works with a "Broascaster" Mobile Device using the Flutter SDK to Broadcast ?

**Comment by plutoless** [comment]
yes it does. Btw you will need a server to do this recording.

**Comment by fvisticot** [comment]
Yep, I see we need a server part.
Do you have docker images we could deploy on a cloud easily ?

**Comment by plutoless** [comment]
Unfortunately no for the moment.
You may checkout this repo for a sample demo as reference, https://github.com/AgoraIO/Basic-Recording

**Comment by fvisticot** [comment]
Great !
Does it works with a Mac as well ? I do not have Linux at home :)

**Comment by plutoless** [comment]
closed if no more questions.

**Comment by alauk** [comment]
Hi plutoless,
I'm testing https://github.com/AgoraIO/Basic-Recording, it works fine with web solution. Now, at Android is recording audio but doesn't recording video. I thought would be the resolution, but this is the same in two cases. Can you help me?

**Comment by plutoless** [comment]
could you pls provide recording logs?

**Comment by alauk** [comment]
I adding this lines in the app Flutter and its worked fine:
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);

Now, the problem is a resolution. At Basic Recording, I don't know resolution is better to work in App mobile's case. I found this values in C++ code, I testing with 1x1 (480x480) values but the quality don't worked good (I set 480x480 in Flutter code too)

**Comment by LichKing-2234** [comment]
@alauk you can refer to https://docs.agora.io/en/Interactive%20Broadcast/video_profile_windows?platform=Windows#recommended-video-profiles

**Comment by mrhmamun** [comment]
is it possible  to use Firebase & Cloud Firestore for recording?

**Comment by LichKing-2234** [comment]
@mrhmamun Sorry, I don't understand, How can Firebase get the video stream.

**Comment by Sid1249** [comment]
Can agora record a live stream from the camera and at the end of recording give me a link that I can save in firebase

My use case is that I want to allow user to record and save directly on cloud and can also access his recorded videos to view or delete them later.
