### ISSUE TITLE
Getting net.dn1 dns2 dns3 dns4 error when connecting.

### ISSUE THREAD

**Issue by Jazzykhan** [AgoraIO-Community/Agora-Flutter-Quickstart#41]
Steps to reproduce. 
Make a new flutter project. import the agora sdk and do simple steps to make both parties join a single video call.
once both parties are in the channel we receive this error
Access denied finding property "net.dns1"
E/libc    (27366): Access denied finding property "net.dns2"
E/libc    (27366): Access denied finding property "net.dns3"
E/libc    (27366): Access denied finding property "net.dns4"
yesterday it was fine i didnt changed anything in the code. also, i tried different app id on agora.io
thanks

**Comment by gabrielarlo** [comment]
Is this bug fixed already? Same issue here.

**Comment by plutoless** [comment]
@gabrielarlo  it's not a bug. it's simply some android low level system warnings. it should not affect your usage.

**Comment by yanmingLiu** [comment]
> 这不是一个错误。这只是一些Android低级系统警告。它不应该影响您的使用。

严重影响，整个控制台全是你们的log

**Comment by rahmanprofile** [comment]
im facing this in voice calling, how i fix that ?

E/flutter ( 5916): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: AgoraRtcException(-17, null)
E/flutter ( 5916): #0      RtcEngineImpl.joinChannel (package:agora_rtc_engine/src/impl/agora_rtc_engine_impl.dart:789:7)
E/flutter ( 5916): <asynchronous suspension>
E/flutter ( 5916): #1      _AudioHomeState.join (package:agoraapp/audio/audio_home.dart:129:5)
E/flutter ( 5916): <asynchronous suspension>
E/flutter ( 5916): 
E/libc    ( 5916): Access denied finding property "net.dns1"
E/libc    ( 5916): Access denied finding property "net.dns2"
E/libc    ( 5916): Access denied finding property "net.dns3"
E/libc    ( 5916): Access denied finding property "net.dns4"
