### ISSUE TITLE
In android emulator and device, camera not opened only black screen

### ISSUE THREAD

**Issue by fullstacktop2019** [AgoraIO-Community/Agora-Flutter-Quickstart#42]
I am trying to use this sdk but I got black screen in both android device and emulator.

W/VideoCapabilities(13641): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(13641): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(13641): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(13641): Unrecognized profile 2130706434 for video/avc
W/VideoCapabilities(13641): Unrecognized profile 2130706433 for video/avc
W/VideoCapabilities(13641): Unrecognized profile 2130706434 for video/avc

**Comment by plutoless** [comment]
it seems you are using some strange video profile? could you pls show me how you set up video resolutions in your app?

**Comment by iammadhukar** [comment]
I am also facing the same problem. Getting black screen when entering into the channel both in emulator and device.
![Screenshot_20191126-152032~2](https://user-images.githubusercontent.com/50227772/69619052-f6b23380-1060-11ea-9471-a485365e4fe1.png)

**Comment by fullstacktop2019** [comment]
> it seems you are using some strange video profile? could you pls show me how you set up video resolutions in your app?

I tried to run this project without any change but I can't get message 'onJoinChannel' like above screenshot.

**Comment by plutoless** [comment]
@fullstacktop2019 
looks familiar to this one
https://github.com/flutter/flutter/issues/24391

**Comment by fullstacktop2019** [comment]
I have checked but my issue is that when I build and run this project and join to channel it doesn't connect to channel.
It never shows message 'onJoinChannel: abc, uid: xx'.

**Comment by plutoless** [comment]
ok. is there any error displayed on screen instead?

**Comment by fullstacktop2019** [comment]
There is no error in screen.

This is log

E/libc    ( 5374): Access denied finding property "net.dns1"
E/libc    ( 5374): Access denied finding property "net.dns2"
E/libc    ( 5374): Access denied finding property "net.dns3"
E/libc    ( 5374): Access denied finding property "net.dns4"
D/        ( 5374): HostConnection::get() New Host Connection established 0xca34d7c0, tid 7329
D/EGL_emulation( 5374): eglCreateContext: 0xdb610100: maj 2 min 0 rcv 2
D/EGL_emulation( 5374): eglMakeCurrent: 0xdd005ea0: ver 2 0 (tinfo 0xc5d6a030)
D/EGL_emulation( 5374): eglMakeCurrent: 0xdb610100: ver 2 0 (tinfo 0xbbb63cc0)
I/AGORA_SDK( 5374): Surface changed to width 1080 height 1584
E/RtcEngine( 5374): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference

**Comment by plutoless** [comment]
ok i will take a look tonight and give you feedback tomorrow morning.

**Comment by fullstacktop2019** [comment]
Thanks, this is my android emulator I am running on.
![image](https://user-images.githubusercontent.com/47564047/69724303-969db900-1156-11ea-889d-7edc9491655f.png)

**Comment by iammadhukar** [comment]
I am able to join the channel. I can listen audio from remote also. but video is not coming. Not getting any error as well.

**Comment by fullstacktop2019** [comment]
@iammadhukar Did you build this project without any change?

**Comment by fullstacktop2019** [comment]
Hi, @plutoless is there any update? please help me.

**Comment by plutoless** [comment]
i'm working on it. will update soon

**Comment by plutoless** [comment]
it works on my real device w/o problem. i'm testing on my emulator.
just to double check that you have done this step right?
![image](https://user-images.githubusercontent.com/471561/69779558-5cc6c400-11e3-11ea-86eb-75d1707dfe03.png)

**Comment by fullstacktop2019** [comment]
Yes, I did and I tested in both emulator and device but same

**Comment by plutoless** [comment]
could you pls try adding this line
AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");

to call.dart
The eventual outcome would look like this,
...
    _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    AgoraRtcEngine.enableWebSdkInteroperability(true);
    AgoraRtcEngine.setParameters('{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
...

and then start the app. our sdk log will print directly to console in this case. please help collect this log and upload it here for me to take a look.

**Comment by fullstacktop2019** [comment]
[error_log.txt](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/3900054/error_log.txt)
This is entire log file

**Comment by plutoless** [comment]
i believe sth is wrong with your current network.

```
I/AGORA_SDK(16375): INFO    (13:35:17: 20 |    0)  16437; [ap] 3.0.213.60:8000 is reported failure, and will be disabled for 4000 ms
I/AGORA_SDK(16375): INFO    (13:35:17: 20 |    0)  16437; [ap] 52.68.71.190:1080 is reported failure, and will be disabled for 4000 ms
I/AGORA_SDK(16375): INFO    (13:35:17: 20 |    0)  16437; [ap] 52.58.56.244:25000 is reported failure, and will be disabled for 4000 ms
```

i see lots of logs like this. could you pls try switching to a 4G or other network if you are currently under some kind of enterprise or limited network space? it's also possible that your network has disabled udp so we won't be able to reach out.

**Comment by fullstacktop2019** [comment]
Does this sdk use another port except 80 or 443?

**Comment by plutoless** [comment]
yes it does. we just range of ports as listed here
https://docs.agora.io/en/Agora%20Platform/firewall?platform=All%20Platforms#%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F-sdk

**Comment by fullstacktop2019** [comment]
Great, it works. my computer has blocked ports, that's the reason.
Thanks

**Comment by codesundar** [comment]
Still facing same black screen issue, how did you resolved ?

**Comment by hemil237** [comment]
> Great, it works. my computer has blocked ports, that's the reason.
> Thanks

brother i am facing same problem as u had , my emulator does not open the camera and showing black display like uh what should i do plz help me
![haha](https://user-images.githubusercontent.com/72067093/95185087-e83ab980-07e5-11eb-9513-4c69d1d4ea64.PNG)
how can i change the port, what was the reasone for this can plz explain me

**Comment by LichKing-2234** [comment]
@hemil237 could you pls provide our SDK log? you can refer to this [doc](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/flutter/rtc_engine/RtcEngine/setLogFile.html)
