### ISSUE TITLE
setLiveTranscoding returns PlatformException without errorcode

### ISSUE THREAD

**Issue by faiyyazs** [AgoraIO-Community/Agora-Flutter-Quickstart#49]
setLiveTranscoding returns PlatformException, Following is the log
E/flutter (11305): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(error, length=3; index=100, null)
E/flutter (11305): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
E/flutter (11305): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:321:33)

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
