### ISSUE TITLE
Choosing the camera (front / rear)

### ISSUE THREAD

**Issue by fvisticot** [AgoraIO-Community/Agora-Flutter-Quickstart#5]
I see only the method switchCamera.
If I understand, the SDK is using front camera by default.
How to choose the front camera on the beginning ?
How to know which camera is used (front or rear) ?

**Comment by plutoless** [comment]
sorry for late reply. For now switchCamera is the only approach. You may need to rely on you own to keep track of which camera is being used.
We have plans to support choosing camera by index in the future though.

**Comment by nsmith1024** [comment]
I want to default to the rear camera, is there a way to do that without the user having to manually switch it?

**Comment by plutoless** [comment]
For the moment you have to do it manually.

**Comment by nsmith1024** [comment]
Can you put in code to default to rear camera because we are using it for emergencies so the user dont have time to figure all that out in an emergency.

**Comment by plutoless** [comment]
@nsmith1024  sry this is still a limitation for the moment. If you are working with our native sdk you can capture the camera yourself and provide that as videosource. But for flutter sdk there's no way for the moment.

**Comment by nsmith1024** [comment]
Hello, its been 25 days, so i wonder if this is a limitation still or has been fixed? The problem is that we are using it for something like emergency, so the user may not have time to configure the camera, or figure out which one is being used for recording during an emergency. It has to be always the back camera.
Thanks!

**Comment by plutoless** [comment]
@nsmith1024  currently i believe the camera opened by default is always front camera. is it possible for you to call switchCamera to open the back one?

**Comment by wanjm** [comment]
I my app, we need to let user chose what camera to use , and then call agora functions. so we need one function that can take camera id as parameter instead of switch camera;

**Comment by plutoless** [comment]
@wanjm  similarly to what i suggested above. you can just use default setting when user chooses front cam, and call switchCamera if user chooses back cam

**Comment by wanjm** [comment]
ok, got it, thanks;

then why don't we export such function to flutter?

**Comment by wanjm** [comment]
in fact the camera id  is 0/1, just the subindex of camera list;
what is the difficulty of such a parameter;

**Comment by plutoless** [comment]
low level it's trying to set a cameraIndex when using switchCamera, so it's equivalent.

**Comment by LichKing-2234** [comment]
dev version support it.

**Comment by fldvlpr** [comment]
Any updates on this

**Comment by LichKing-2234** [comment]
@fldvlpr Support it already.

**Comment by ravindra21** [comment]
Can i get the references how to switch the camera ?

**Comment by neilhosey** [comment]
was this ever resolved?  I have this issue 4 years later.  Need to set external camera as the camera source

**Comment by RamkumarDRS** [comment]
> I want to default to the rear camera, is there a way to do that without the user having to manually switch it?

i want to default to the front camera ,do you have any solution >

**Comment by gdhananjay** [comment]
I am using flutter sdk on mobile browser and hence no control over switching camera (as per definition of engine.switchCamera()). Sometime it uses front camera sometime it uses back camera.   Is there a way to fix
