### ISSUE TITLE
How can I record my session (audio or video) in SD card?

### ISSUE THREAD

**Issue by abcdna** [AgoraIO-Community/Agora-Flutter-Quickstart#51]
I have implemented the demo and working fine but I want to record the session and want to save audio or video in my SD card. Please suggest.

Thanks

**Comment by plutoless** [comment]
we provide server side recordings, you can take a look at https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms if interested

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
