### ISSUE TITLE
Camera Black Screen

### ISSUE THREAD

**Issue by geekz-reno** [AgoraIO-Community/Agora-Flutter-Quickstart#52]
Hi, Just clone this repository, i already added API_KEY, but when i run on real device, after i add channel and detail page show, it only show buttons with black background.

**Comment by plutoless** [comment]
could you pls follow instructions in https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#reporting-an-issue to provide some details for your issue?

**Comment by codesundar** [comment]
#53
