### ISSUE TITLE
能帮忙看下 go后台生成 token问题么

### ISSUE THREAD

**Issue by dio17337548611** [AgoraIO-Community/Agora-Flutter-Quickstart#54]
我这边用go生成token，不知道为何，token中总是有空格。
然后传递给flutter端，然后加入频道失败。
下边是我的go代码
![image](https://user-images.githubusercontent.com/58875519/71506898-adead600-28bd-11ea-9638-76554c2e8c8b.png)

这是 用这些代码生成的token:
00679ac8152c1394babaf20f341ad76e04cIACcj7qfrVmNJJW/lDpwiq8z0wMp45CSt UlUpLBOT7M8uuR0YQAAAAAIgAzFjECH/QGXgQAAQAAAAAAAgAAAAAAAwAAAAAABAAAAAAA
这是 flutter收到的token打印的log：
![image](https://user-images.githubusercontent.com/58875519/71507148-70d31380-28be-11ea-99a3-b03336889505.png)

感觉go后端生成的token其中不知道为何增加了个换行，
手机端flutter这边获得到的就是个带有空格的token。
就加入频道一直失败了

**Comment by LichKing-2234** [comment]
trim空格，这个token可以使用么

**Comment by dio17337548611** [comment]
> trim空格，这个token可以使用么

还是不行，我还用了 replace(" " ,"") 来处理这个字符串
感觉 这像是个换行。

**Comment by plutoless** [comment]
你就手动去掉这个换行，看token能不能用
