### ISSUE TITLE
Black  Screen during Audio and Video session

### ISSUE THREAD

**Issue by pojoba02** [AgoraIO-Community/Agora-Flutter-Quickstart#55]
Flutter Doctor Output:
 flutter doctor -v 
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-US)
    • Flutter version 1.12.13+hotfix.5 at /Users/flutter
    • Framework revision 27321ebbad (3 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/selorm/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 10 (API 29) (emulator)
    • iPhone 11 Pro Max         • 5D89513D-8599-446D-9357-CA8898C3AE04 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-3 (simulator)

• No issues found!

 await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
   await AgoraRtcEngine.enableWebSdkInteroperability(true);
    // set parameters for Agora Engine
   await AgoraRtcEngine.setParameters('{\"che.video.lowBitRateStreamParameter\"'
        +':{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    // join channel corresponding to current group
   await AgoraRtcEngine.joinChannel(null, widget.chatId, null, 0);
  }

  /// Create agora sdk instance and initialze
  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(APP_ID);
    await AgoraRtcEngine.enableVideo();
  }

  /// Add agora event handlers
  void _addAgoraEventHandlers() {
    AgoraRtcEngine.onError = (dynamic code) {
      setState(() {
        final info = 'onError: ' + code.toString();
        _infoStrings.add(info);
      });
    };
![Screenshot_1577752203](https://user-images.githubusercontent.com/8344941/71605926-afb4d380-2b21-11ea-8cf5-df430d793e9e.png)

I did follow all the configuration instructions, still giving me the same results.

**Comment by LichKing-2234** [comment]
#53 same problem?

**Comment by Manishmg3994** [comment]
same
