### ISSUE TITLE
关于小窗显示自己摄像头画面

### ISSUE THREAD

**Issue by WestWard-fjlajq** [AgoraIO-Community/Agora-Flutter-Quickstart#57]
现在视频通话时，通话界面是按接入的人数，界面上平分显示。我们这边一般是面对面的通话，希望可以和微信一样，自已显示在左或右上角的小框，对方显示在全屏。
这个功能有没有类似的可以参考一下？

**Comment by LichKing-2234** [comment]
这个修改下布局就可以，只要RenderView能绑定对应的uid就可以

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
