### ISSUE TITLE
broadcast video is getting zoomed

### ISSUE THREAD

**Issue by singlakaran** [AgoraIO-Community/Agora-Flutter-Quickstart#62]
I used this code:- 
await AgoraRtcEngine.setParameters(
        '{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":180}}');

it happens every time with me.

Channel Name: -R_nRurV

**Comment by LichKing-2234** [comment]
your can try to change the VideoRenderMode of AgoraRenderWidget

**Comment by singlakaran** [comment]
@LichKing-2234  i tried that also

i think its a view issue
i used stack and positioned 

here my code
```
Positioned(
            height: MediaQuery.of(context).size.height,
            width: MediaQuery.of(context).size.width,
            top: 0,
            left: 0,
            child: views[0],
          ),
```

**Comment by plutoless** [comment]
@singlakaran we provide fit/fill mode for video render view. if neither works for you could you pls briefly illustrate what kind of results you would like to see?

**Comment by singlakaran** [comment]
@plutoless  i get this broadcast video
![Screenshot_20200212-115301_Leher](https://user-images.githubusercontent.com/26064126/74308586-9c3a9080-4d8e-11ea-9d59-c2530dcdc755.jpg)

of this video
![Screenshot_2020-02-12-11-50-46-728_com leher](https://user-images.githubusercontent.com/26064126/74308608-a8bee900-4d8e-11ea-86e8-b560ee91594a.jpg)

i used
`await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);`

```
VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(180, 180);
    config.orientationMode = VideoOutputOrientationMode.Adaptative;
    await AgoraRtcEngine.setVideoEncoderConfiguration(config);
```

but i dont want this zoom on my broadcast video.

**Comment by singlakaran** [comment]
@plutoless 
Recently i have noticed when two user join same channel then both broadcast video is zoom

but in between one of them do `flutter run` then that user join that same channel then broadcast will become right.

**Comment by plutoless** [comment]
sorry for late reply. could you pls share a channel you used to join which reproduced this problem before, and corresponding time, i will check from backend to investigate.

**Comment by plutoless** [comment]
i will need channel name you used, the uids of two devices, and time when the issue was reproduced.

**Comment by LichKing-2234** [comment]
could you give us your sample code? I cant repetition your problem.

**Comment by Drata** [comment]
Hi, @plutoless, I'm having the same problem, but I think what's actually happening is that the video is being received by the audience with the width and height swapped. If you set the VideoRenderMode to Hidden, it will zoom in to fit it on the entire screen, as @singlakaran is reporting. But if you set it to Fit, you will see the broadcast without the zoom but landscaped.

If I can give you any further information to help you locate the cause of this, please, let me know.

Thank you.

**Comment by singlakaran** [comment]
@Drata  try this code

```
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);

    VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(640, 480);
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    config.frameRate = 15;
    config.bitrate = 0;
    await AgoraRtcEngine.setVideoEncoderConfiguration(config);
    await AgoraRtcEngine.joinChannel(null, widget.channelName, "", 0);
    List<AgoraLiveTranscodingUser> agoraLiveUserList =
        cdnLayout(0, _users, 640, 480);
    await AgoraRtcEngine.setLiveTranscoding(AgoraLiveTranscoding.fromJson({
      'width': 640,
      'height': 480,
      'videoBitrate': 1800,
      'videoFramerate': 15,
      'transcodingUsers': agoraLiveUserList,
      'watermark': AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
      'backgroundImage':
          AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
    }));
```

**Comment by Drata** [comment]
Doesn't work for me. I'm not using CDN live, though, just native Agora broadcasting.

**Comment by plutoless** [comment]
@Drata sorry for late reply. what is the resolution you set while doing native broadcasting? it might be also possible that the resolution you entered is not supported by the device. i can try out if you can provide your settings

**Comment by Drata** [comment]
Yes, thank you, I think that was it. I changed the resolution and now its working perfectly.

**Comment by VikashIOS** [comment]
can you share the solution Drata.

**Comment by Drata** [comment]
> can you share the solution @Drata.

` VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(1280, 720);
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    config.frameRate = 15;
    config.bitrate = 0;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);`

Try with this encoding configuration. It solved it for me.

**Comment by VikashIOS** [comment]
not working @Drata 
Future<void> _initAgoraRtcEngine() async {
    AgoraRtcEngine.create(APP_ID);
    AgoraRtcEngine.enableVideo();
    VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(1280, 720);
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    config.frameRate = 15;
    config.bitrate = 0;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);
    AgoraRtcEngine.enableWebSdkInteroperability(true);
    // AgoraRtcEngine.setParameters('{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    // use _addRenderView everytime a native video view is needed
    _addRenderView(0, (viewId) {
      AgoraRtcEngine.setupLocalVideo(viewId, VideoRenderMode.Hidden);
      AgoraRtcEngine.startPreview();

      AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
      if (widget.userRoleInChannel == "audience") {
        AgoraRtcEngine.setClientRole(ClientRole.Audience);
      } else {
        AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
      }
      AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
    });
  }

**Comment by LichKing-2234** [comment]
```
class AgoraLiveTranscodingUser {
  int uid;
  int width;
  int height;
  int x;
  int y;
  int zOrder;
  int alpha;
  int audioChannel;

  AgoraLiveTranscodingUser.fromJson(Map<dynamic, dynamic> json)
      : uid = json['uid'],
        width = json['width'],
        height = json['height'],
        x = json['x'],
        y = json['y'],
        zOrder = json['zOrder'],
        alpha = json['alpha'],
        audioChannel = json['audioChannel'];

  Map<dynamic, dynamic> toJson() => {
        'uid': uid,
        'width': width,
        'height': height,
        'x': x,
        'y': y,
        'zOrder': zOrder,
        'alpha': alpha,
        'audioChannel': audioChannel
      };
}

```

**Comment by 4Bits-solutions** [comment]
I am not getting where I have to put this code it will be great if anyone provides a full solution for broadcasting in a flutter.I tried many things but still getting video zoomed.

**Comment by plutoless** [comment]
@4Bits-solutions zoomed how? any screenshots?

**Comment by khaliqdadmohmand** [comment]
> @plutoless
> i used default mode and that is `Hidden`
> i get this broadcast video
> ![Screenshot_20200212-115301_Leher](https://user-images.githubusercontent.com/26064126/74308586-9c3a9080-4d8e-11ea-9d59-c2530dcdc755.jpg)
> 
> of this video
> ![Screenshot_2020-02-12-11-50-46-728_com leher](https://user-images.githubusercontent.com/26064126/74308608-a8bee900-4d8e-11ea-86e8-b560ee91594a.jpg)
> 
> i used
> `await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);`
> 
> ```
> VideoEncoderConfiguration config = VideoEncoderConfiguration();
>     config.dimensions = Size(180, 180);
>     config.orientationMode = VideoOutputOrientationMode.Adaptative;
>     await AgoraRtcEngine.setVideoEncoderConfiguration(config);
> ```
> 
> but i dont want this zoom on my broadcast video.

Hey bro i really need your code for live streaming.

**Comment by singlakaran** [comment]
anyone can help me for solving this issue

https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/96

**Comment by aaverty** [comment]
Hello, has someone found a solution to this problem? I have the same concerns and I must find a solution quickly. If any of you have solved the problem or have any clues to give me that would be really cool! : D Thank you

**Comment by LichKing-2234** [comment]
@aaverty Same problem when trying our demo?

**Comment by khaliqdadmohmand** [comment]
i am getting same issue.. from broadcaster side its fine but from audience side its getting zoomed. 

> await AgoraRtcEngine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":0}}''');

**Comment by plutoless** [comment]
for people who are having issues here, could you pls try setting the video dimension to vertical, e.g. 320 x 480 and see if the zoom issue still persists?

**Comment by aaverty** [comment]
I have found a workaround.
`// Code with broadcast video zoomed for audience
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await AgoraRtcEngine.setClientRole(isBroadcaster() ? ClientRole.Broadcaster : ClientRole.Audience);
// Code with broadcast not zoomed for audience
await AgoraRtcEngine.setChannelProfile(ChannelProfile.Communication);
`

**Comment by LichKing-2234** [comment]
zoomed because the video size is too small in VideoEncoderConfiguration

**Comment by Muhammad-Ullah** [comment]
@khaliqdadmohmand  did you get the solution??.
I think it is outdated now and not working
