### ISSUE TITLE
Code for Audio Chat Only

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO-Community/Agora-Flutter-Quickstart#63]
Can you please show me some code for using only Agora audio call with Flutter? Your Quickstart is for video call but I want code for only audio call.

To achieve this, is it as simple as using AgoraRtcEngine.disableVideo(); for each user? Do I still need to add _getRenderViews() code if the call is only audio call?

**Comment by LichKing-2234** [comment]
the SDK is in audio mode by default,  you can remove the code of `enableVideo`. and render views should be removed

**Comment by AxesandGrinds** [comment]
Ok, thank you! I may reopen this issue when I enter the testing part of my code and it does not work.
