### ISSUE TITLE
[Question] Is it possible to know which user is talking?

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#64]
- I would like to try to mimic discord and add a green border around the person talking. Is it possible?

**Comment by LichKing-2234** [comment]
you can refer to this doc
https://docs.agora.io/cn/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#aaec0b8db9458b45d14cdcb3003f76fbe
