### ISSUE TITLE
[Question] Is it possible to wrap a GestureDetector over a AgoraRenderWidget?

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#65]
I have tried wrapping `AgoraRenderWidget` with a `GestureDetector` and a few Buttons. However the function onPressed in those widgets never gets fired. I assume this has to do with flutter imbedded views being in technical preview.

**Comment by LichKing-2234** [comment]
try another view? then see is it worked

**Comment by VictorUvarov** [comment]
What do you mean by another view? The other AgoraRenderWidget when there are two people in the channel?

**Comment by LichKing-2234** [comment]
not AgoraRenderWidget, any flutter view

**Comment by VictorUvarov** [comment]
Yes my other widgets work with a GestureDetector

**Comment by AxesandGrinds** [comment]
Any news on this?

**Comment by LichKing-2234** [comment]
use `Listener` to replace 'GestureDetector'

**Comment by VictorUvarov** [comment]
Thanks it works

**Comment by MungaraJay** [comment]
@LichKing-2234 @VictorUvarov @plutoless @PRWrl 

Can you please tell me how can i import this AgoraRenderWidget ?

I am not able to find it. I am using agora_rtc_engine: ^3.0.1-dev.7?

Is there any changes for this widget?

**Comment by LichKing-2234** [comment]
@MungaraJay You can refer to the quickstart

**Comment by AxesandGrinds** [comment]
> use `Listener` to replace `GestureDetector`

Hello @LichKing-2234, can you give an example? I'm not sure what you mean by 'Listener'

**Comment by AxesandGrinds** [comment]
I think I figured it out.
[](https://api.flutter.dev/flutter/widgets/Listener-class.html)

**Comment by AxesandGrinds** [comment]
I figured it out.
https://api.flutter.dev/flutter/widgets/Listener-class.html

**Comment by LichKing-2234** [comment]
@AxesandGrinds The new version of SDK support `GestureDetector `

**Comment by AxesandGrinds** [comment]
Excellent news. onTap in `GestureDetector` is better than the options for `Listener`.
