### ISSUE TITLE
Flutter Plugin: agora_rtc_engine-1.0.6  中存在问题

### ISSUE THREAD

**Issue by fmok** [AgoraIO-Community/Agora-Flutter-Quickstart#66]
agora_rtc_engine-1.0.6 ---> lib ---> src  ---> base.dart文件中：第126行，'audioSampleRate'的value写成了_resolveAudioCodecProfileType[audioSampleRate]，应该是_resolveAudioSampleRate[audioSampleRate]吧？？？
_resolveAudioCodecProfileType这个map对应的应该是audioCodecProfile
_resolveAudioSampleRate这个map对应的才应该是audioSampleRate吧。

如果上述提到的问题确实存在的话，我在我本地修改了，run只有，直接crash在iOS的  native SDK（AgoraRtcEngine_iOS 2.9.1）中，并且无任何crash的日志打印。
请检查是否存在该问题，还有相应的native SDK中是否也有问题。

**Comment by LichKing-2234** [comment]
这个地方确实写错了，你这边本地修改后是正常了么

**Comment by fmok** [comment]
修改后，调用时候传入正确的value，直接crash了，没有任何崩溃信息
'audioSampleRate':AgoraAudioSampleRateType.MidRateType

**Comment by fmok** [comment]
复现情景是：设置CDN转码
Map userMap = {'uid':0, 'x':0, 'y':0, 'zOrder':0, 'alpha':1, 'width':MediaQuery.of(context).size.width.toInt(), 'height':MediaQuery.of(context).size.height.toInt(), 'audioChannel':0};
            AgoraLiveTranscodingUser user = AgoraLiveTranscodingUser.fromJson(userMap);

            Map transcodingMap = {'width':MediaQuery.of(context).size.width.toInt(), 'height':MediaQuery.of(context).size.height.toInt(),
              'videoBitrate':400, 'videoFramerate':30, 'videoGop':30, 'videoCodecProfile':AgoraVideoCodecProfileType.High, 'transcodingUsers':[user], 'transcodingExtraInfo':'transcodingExtraInfo',
              'watermark':AgoraImage('', 0, 0, 0, 0), 'backgroundImage':AgoraImage('', 0, 0, 0, 0), 'backgroundColor':0,
              'audioSampleRate':AgoraAudioSampleRateType.MidRateType, 'audioBitrate':48, 'audioChannels':2, 'audioCodecProfile': AgoraAudioCodecProfileType.HEAAC};
            AgoraLiveTranscoding transcoding = AgoraLiveTranscoding.fromJson(transcodingMap);
            AgoraRtcEngine.setLiveTranscoding(transcoding);

**Comment by LichKing-2234** [comment]
好的，我这边试下

**Comment by LichKing-2234** [comment]
1.0.7发布了，修复了这个问题

**Comment by fmok** [comment]
目前在 pub 上只能更新到1.0.6，更新不到1.0.7，github上已经能看到修改的地方，，，请问是pub上没有更新吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arthas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月18日(星期二) 中午11:57
收件人:&nbsp;"AgoraIO-Community/Agora-Flutter-Quickstart"<Agora-Flutter-Quickstart@noreply.github.com&gt;;
抄送:&nbsp;"凤鸣"<1528123808@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO-Community/Agora-Flutter-Quickstart] Flutter Plugin: agora_rtc_engine-1.0.6  中存在问题 (#66)




1.0.7发布了，修复了这个问题

**Comment by LichKing-2234** [comment]
更新了，你用的国内的镜像源吧，可能还没同步

**Comment by fmok** [comment]
好的，我用的是国内的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arthas"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月19日(星期三) 中午1:18
收件人:&nbsp;"AgoraIO-Community/Agora-Flutter-Quickstart"<Agora-Flutter-Quickstart@noreply.github.com&gt;;
抄送:&nbsp;"凤鸣"<1528123808@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO-Community/Agora-Flutter-Quickstart] Flutter Plugin: agora_rtc_engine-1.0.6  中存在问题 (#66)




更新了，你用的国内的镜像源吧，可能还没同步

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
