### ISSUE TITLE
Black Screen During video calls, Error 17 followed by onJoinChannel call

### ISSUE THREAD

**Issue by 24kmagik** [AgoraIO-Community/Agora-Flutter-Quickstart#67]
![Screenshot_2020-02-18-11-08-12-973_beta prithvi kinview_365](https://user-images.githubusercontent.com/43204606/74708156-c46c3880-5241-11ea-88b6-08ca15f1a78b.jpg)

D/Camera  (25653): Lct package name is beta.prithvi.kinview_365
E/libc    (25653): Access denied finding property "vendor.camera.aux.packagelist"
E/AccessibilityBridge(25653): VirtualView node must not be the root node.
D/AudioManager(25653): getStreamVolume isRestricted mode = 0
D/AudioManager(25653): getStreamVolume isRestricted mode = 0
E/RtcEngine(25653): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference
V/AudioTrack(25653): getMinFrameCount=1288: afFrameCount=1920, afSampleRate=48000, afLatency=80
V/AudioTrack(25653): set(): streamType -1, sampleRate 16000, format 0x1, channelMask 0x1, frameCount 2576, flags #0, notificationFrames 0, sessionId 0, transferType 3, uid -1, pid -1
V/AudioTrack(25653): set() streamType -1 frameCount 2576 flags 0000
V/AudioTrack(25653): Building AudioTrack with attributes: usage=2 content=1 flags=0x0 tags=[]
W/AudioTrack(25653): Use of stream types is deprecated for operations other than volume control
W/AudioTrack(25653): See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
I/AudioManager(25653): In isSpeakerphoneOn(), calling application: beta.prithvi.kinview_365
I/AudioManager(25653): In isSpeakerphoneOn(), calling application: beta.prithvi.kinview_365
D/AudioManager(25653): getStreamVolume isRestricted mode = 0
I/AudioManager(25653): In isSpeakerphoneOn(), calling application: beta.prithvi.kinview_365
I/AudioManager(25653): In isSpeakerphoneOn(), calling application: beta.prithvi.kinview_365
E/AccessibilityBridge(25653): VirtualView node must not be the root node.
W/AudioTrack(25653): releaseBuffer() track 0x794e95e800 disabled due to previous underrun, restarting
I/AudioManager(25653): In isSpeakerphoneOn(), calling application: beta.prithvi.kinview_365

The code for the calling page is nothing different from the Agora Quick Start for Flutter, but i set the channel ID as "sample"...

**Comment by LichKing-2234** [comment]
do you set the currect appId?

**Comment by parth22** [comment]
I also face this black screen issue in iOS device. At the other end streaming look perfect but the user which goes live shows black screen.
I'm using ```agora_rtc_engine: ^1.0.5```
![IMG_0196](https://user-images.githubusercontent.com/13308845/76058204-c522ff80-5fa1-11ea-92b3-9c2d3457e691.png)

**Comment by LichKing-2234** [comment]
@parth22 can you provide the SDK log to me?

**Comment by parth22** [comment]
@LichKing-2234 Thanks for quick reply. I didn't get any logs in my IDE when i'm gone live in iOS device just a black screen appear but, on the receiver side i got perfect view of both front and rear camera. If it's not enough for you so, i can provide you a short video of this issue.

**Comment by LichKing-2234** [comment]
why setupRemoteVideo uid is 0, pls check your code?

**Comment by LichKing-2234** [comment]
I think you miss the local configuration when init AgoraRenderWidget

**Comment by parth22** [comment]
@LichKing-2234 I also check that all local configuration as mentioned here [agora_rtc_engine](https://pub.dev/packages/agora_rtc_engine) and i didn't miss any.

**Comment by LichKing-2234** [comment]
`AgoraRenderWidget(0, local: true, preview: false)`
have your added this code?

**Comment by parth22** [comment]
Thanks @LichKing-2234 I forgot to add this line in my code when i'm gone live in my app and it's taking false value for preview property. Again thanks for guide me.

**Comment by rlee1990** [comment]
I am also getting a black screen was not before the update? Can you state what has changed?

**Comment by LichKing-2234** [comment]
@rlee1990 pls provide more infomation

**Comment by rlee1990** [comment]
I also get a black screen on android and a white screen on IOS It all worked until I updated to the newest version.
`AgoraRtcEngine.createNativeView((viewId) {
              AgoraRtcEngine.setupLocalVideo(viewId, VideoRenderMode.Hidden)
                  .then((a) {
                
                AgoraRtcEngine.startPreview();
              });
            }),`

**Comment by rlee1990** [comment]
I am trying to do a video broadcast

**Comment by rlee1990** [comment]
@LichKing-2234 Did the way to display the video feed change?
I also have `GeneratedPluginRegistrant.registerWith(flutterEngine);` commeted out

**Comment by rlee1990** [comment]
@LichKing-2234 I got it to work

**Comment by mauthsalam** [comment]
@LichKing-2234, I am facing the same problem
Here is my log file, the app can't connect to channel.
It connects to channel in ios but not working in android emulator.
And it can't send or receive video in both of android and ios
[log.txt](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/4418742/log.txt)
Can you help me please?

**Comment by LichKing-2234** [comment]
@mauthsalam the log show you join channel failed, pls check your network

**Comment by mauthsalam** [comment]
@LichKing-2234 I tested it again.
In agora console, they measured only voice call in minutes but no minutes for video call.
Actually video has never been received.
Any idea?

**Comment by LichKing-2234** [comment]
@mauthsalam maybe you miss `enableVideo`

**Comment by mauthsalam** [comment]
Here is some of my code, setting agora sdk and get render views.

`   AgoraRtcEngine.enableWebSdkInteroperability(true);
    AgoraRtcEngine.setChannelProfile(ChannelProfile.Communication);
    AgoraRtcEngine.setParameters('{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    AgoraRtcEngine.enableVideo();
    AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);`

`  List<Widget> _getRenderViews() {
    List<Widget> list = [AgoraRenderWidget(0, local: true, preview: false)];
    _users.forEach((int uid) => {
      list.add(AgoraRenderWidget(uid))
    });
    return list;
  }`

![image](https://user-images.githubusercontent.com/61812407/78728896-9074e000-7973-11ea-8916-dda17187e649.png)
But only audio works and video doesn't work like above image.
Any help?

**Comment by LichKing-2234** [comment]
@mauthsalam is our demo working?

**Comment by LichKing-2234** [comment]
@mauthsalam by the way, what platform is your pic about?

**Comment by mauthsalam** [comment]
It's from iPhone

**Comment by mauthsalam** [comment]
@LichKing-2234 And one more thing is that agora console logged minutes for video even my app didn't show any video

**Comment by LichKing-2234** [comment]
@mauthsalam maybe you forget to add the io.flutter.embedded_views_preview configuration in info.plist?

**Comment by mauthsalam** [comment]
@LichKing-2234 how can I do that? Is that a customized key&value for flutter or for this sdk?

**Comment by LichKing-2234** [comment]
@mauthsalam flutter's key&value

**Comment by mauthsalam** [comment]
![image](https://user-images.githubusercontent.com/61812407/78748691-9dabc200-79a7-11ea-873e-63960a381372.png)
Is this correct?

**Comment by LichKing-2234** [comment]
@mauthsalam yes, just do it

**Comment by KieranCTaylor** [comment]
> @LichKing-2234 I got it to work

Mind sharing what worked?
