### ISSUE TITLE
Is it possible to set the max video resolution cap?

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#68]
I want to be able to cap the video quality to 720p or to 1080p. Is this possible?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#af5f4de754e2c1f493096641c5c5c1d8f

**Comment by danielgchap** [comment]
> https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#af5f4de754e2c1f493096641c5c5c1d8f

Thanks @LichKing-2234
