### ISSUE TITLE
How to take screenshot in flutter?

### ISSUE THREAD

**Issue by suriyaKalidoss123** [AgoraIO-Community/Agora-Flutter-Quickstart#69]
During video call when I'm trying to take screenshot programmatically in flutter. Only a black screen appears. Please provide a solution to take a screenshot.

**Comment by plutoless** [comment]
how did you do the screenshot? could you pls share your code?

**Comment by suriyaKalidoss123** [comment]
replace this below code with flutter main.dart sample
[videocall.zip](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/4273568/call.zip)

**Comment by LichKing-2234** [comment]
I add the code of screenshot only, and I see it worked, pls check your code.
or you can try my code
[call.dart.zip](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/4273938/call.dart.zip)

**Comment by suriyaKalidoss123** [comment]
@LichKing-2234  still black screen issue occurs
![image](https://user-images.githubusercontent.com/45841845/75659433-ffce2480-5c8f-11ea-90b6-d0ae3656e54f.png)
Please save the image and check
` Future<void> _capturePng() {
    return new Future.delayed(const Duration(milliseconds: 20), () async {
      try {
        RenderRepaintBoundary boundary =
            rootWidgetKey.currentContext.findRenderObject();
        var image = await boundary.toImage(pixelRatio: 3.0);
        ByteData byteData = await image.toByteData(format: ImageByteFormat.png);
        Uint8List pngBytes = byteData.buffer.asUint8List();
        final result = await ImageGallerySaver.saveImage(pngBytes);
        return pngBytes; //这个对象就是图片数据
      } catch (e) {
        print(e);
      }
    });
  }`

**Comment by LichKing-2234** [comment]
onError:17
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_constants.html#a3f35b3060594b41f137101166f6401b4

 is state changed, cause `joinChannel` twice?

**Comment by suriyaKalidoss123** [comment]
@LichKing-2234  nope join channel method called on the page initialize.So changing the page state does not call join channel twice. Are you facing this issue?

**Comment by LichKing-2234** [comment]
by the way, your device is Android or iOS?

**Comment by suriyaKalidoss123** [comment]
> by the way, your device is Android or iOS?

Android

**Comment by LichKing-2234** [comment]
I think I misunderstood you. The picture in this album is black, but the app works fine?

**Comment by suriyaKalidoss123** [comment]
> I think I misunderstood you. The picture in this album is black, but the app works fine?

 yep, the plugin is working fine. But I can't able to take a screenshot due to the black screen issue.

**Comment by LichKing-2234** [comment]
because we use `SurfaceView` to render the video, screenshot is not worked for `SurfaceView`

**Comment by suriyaKalidoss123** [comment]
@LichKing-2234  absolutely correct, Is there is any alternatives for this issue?

**Comment by LichKing-2234** [comment]
your can try `TextureView`, but you need fork our code and modify it

**Comment by suriyaKalidoss123** [comment]
> your can try `TextureView`, but you need fork our code and modify it

which code?

**Comment by LichKing-2234** [comment]
you can refer to this doc
https://docs.agora.io/en/Interactive%20Broadcast/custom_advanced_android?platform=Android#agoratextureview-class

**Comment by LichKing-2234** [comment]
`
AgoraTextureView render = new AgoraTextureView(context);
render.init(null);
render.setBufferType(MediaIO.BufferType.BYTE_ARRAY);
render.setPixelFormat(MediaIO.PixelFormat.I420);
rtcEngine().setLocalVideoRenderer(render);
rtcEngine().setRemoteVideoRenderer(uid, otherRender);
`

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Comment by agungsb** [comment]
@LichKing-2234 Can you please provide an example of how to achieve that in Flutter?

**Comment by agungsb** [comment]
I see on https://github.com/AgoraIO/Flutter-SDK/tree/master/android/src/main/java/io/agora/agorartcengine , it only supports SurfaceView for Flutter. Any chance to add TextureView?

**Comment by LichKing-2234** [comment]
> @LichKing-2234 Can you please provide an example of how to achieve that in Flutter?
> 
> My guess is that I need `setExternalVideoSource` method but I can't find it in `AgoraRTCEngine`
> 
> https://docs.agora.io/en/Video/custom_video_android?platform=Android

You should add it into the java code

**Comment by LichKing-2234** [comment]
> I see on https://github.com/AgoraIO/Flutter-SDK/tree/master/android/src/main/java/io/agora/agorartcengine , it only supports SurfaceView for Flutter. Any chance to add TextureView?

We have planed to add TextureView.

**Comment by suriyaKalidoss123** [comment]
Is the issue fixed???

**Comment by Meherdeep** [comment]
Hi, for anyone who's still facing this issue : I was able to take the screenshot of my stream using this package https://pub.dev/packages/native_screenshot

You can simply run this function to take the screenshot of your stream:

```
Future<void> _capturePng() async {
    String path = await NativeScreenshot.takeScreenshot();
    print(path);
  }
```

You can find the complete code here: https://github.com/Meherdeep/agora-videocall-demo

**Comment by TungWang** [comment]
> Hi, for anyone who's still facing this issue : I was able to take the screenshot of my stream using this package https://pub.dev/packages/native_screenshot
> 
> You can simply run this function to take the screenshot of your stream:
> 
> ```
> Future<void> _capturePng() async {
>     String path = await NativeScreenshot.takeScreenshot();
>     print(path);
>   }
> ```
> 
> You can find the complete code here: https://github.com/Meherdeep/agora-videocall-demo

Is it working on iOS?
