### ISSUE TITLE
[Question] Running example with "flutter run --release" only shows local video

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#70]
- When running the example with the "flutter run --release" command and joining the same channel one two different phones only shows the local video on each phone and not the remote video.
- Is this intended behavior?

**Comment by LichKing-2234** [comment]
is debug worked?

**Comment by VictorUvarov** [comment]
Yes debug works fine. Only running with the --release flag does not work

**Comment by LichKing-2234** [comment]
It works fine for me, could you pls provide our SDK log?
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08

**Comment by VictorUvarov** [comment]
For some reason it works now. Must have had a bad build.
