### ISSUE TITLE
onLeaveChannel 建议回调时候增加 RtcStats 

### ISSUE THREAD

**Issue by hallywang** [AgoraIO-Community/Agora-Flutter-Quickstart#73]
flutter  onLeaveChannel 建议回调时候增加 RtcStats ，便于在离开频道时候获取到通话时长等信息

**Comment by plutoless** [comment]
这个可能需要从原生SDK层面解决，我会把你的需求提给产品经理，但目前暂时可能需要您自己这边做业务服务来计算通话时长。

**Comment by LichKing-2234** [comment]
add it in react-native-agora@beta
