### ISSUE TITLE
How to adjust the resolution of video call based on the internet speed?

### ISSUE THREAD

**Issue by suriyaKalidoss123** [AgoraIO-Community/Agora-Flutter-Quickstart#76]
Hi,
  Currently, bitrate and framerate of particular resolution are reduced If internet quality is bad. My question is. If the speed is suddenly reduced to lower bandwidth. How to adjust the resolution on run time based on internet speed so my video call runs smoothly on all network condition. Please provide a solution.
Thanks.

**Comment by LichKing-2234** [comment]
same as https://github.com/AgoraIO/Flutter-SDK/issues/90
