### ISSUE TITLE
Is there a better way to fix android black screen issue when video streaming?

### ISSUE THREAD

**Issue by VictorUvarov** [AgoraIO-Community/Agora-Flutter-Quickstart#77]
Currently you guys recommend removing this line from `MainActivity.java` if it extends `io.flutter.embedding.android.FlutterActivity` which all new flutter projects do.
```java
GeneratedPluginRegistrant.registerWith(flutterEngine);
```
However this causes other platform view plugins like [webview_flutter](https://pub.dev/packages/flutter_webview_plugin) to not work on android.
Is there a better solution to this problem or atleast a link to the flutter issue relating to this problem?

**Comment by LichKing-2234** [comment]
any error log? I will take a look later

**Comment by VictorUvarov** [comment]
It doesn't seem to black screen anymore. Maybe I had an old build not sure.

**Comment by mauthsalam** [comment]
@LichKing-2234, I'm getting the same error.
Could you check below log please?
[log.txt](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/files/4418747/log.txt)
