### ISSUE TITLE
LIVE Video Streaming everywhere.

### ISSUE THREAD

**Issue by jlucas577** [AgoraIO-Community/Agora-Flutter-Quickstart#83]
Good afternoon! Want to know how to use the AgoraIO API in Flutter to make and watch Lives to live.

**Comment by plutoless** [comment]
hi sorry for late reply. is the current demo not satisfying your needs?

**Comment by github4f** [comment]
> hi sorry for late reply. is the current demo not satisfying your needs?

Why it does not support v2 embedding in Flutter. When we downgrade the Flutter, all other services including firebase stop working! Are you going to upgrade the plugin? As far as I know, this issue is there since Dec 2019.

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
