### ISSUE TITLE
Android device audio too quiet

### ISSUE THREAD

**Issue by opringle** [AgoraIO-Community/Agora-Flutter-Quickstart#84]
# Steps to reproduce

1. Download, setup and run the sample
2. Upgrade agora flutter package to ^1.0.8
3. Run the sample on a connected iPhone using `flutter run`
4. Run the sample on a connected android device using `flutter run`
5. Open the app and join channel '123' on both devices
6. Max android system volume in all categories
7. speak into the iPhone

My devices are a Pixel 3 running Android version 10 and an iPhone 6 running iOS 12.4.5.

## Expected behaviour

Audio is emitted from the android device at an audible volume

## Actual behaviour 

Audio is emitted from the android device at very low volume

# `flutter doctor` output

```bash
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.3 19D76, locale en-CA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)
```

**Comment by opringle** [comment]
Adding this code increased android device call volume. Still I would expect the default settings to be audible.

```dart
await AgoraRtcEngine.enableWebSdkInteroperability(true);
await AgoraRtcEngine.adjustPlaybackSignalVolume(400); // added this line
await AgoraRtcEngine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
```

**Comment by opringle** [comment]
Reverting back to `1.0.5` (previously `^1.0.8`) increased the android device audio playback volume further.

**Comment by LichKing-2234** [comment]
what method, I cant see it.
by the way, can you make sure where is the voice emitted from, speakerphone or handset?

**Comment by opringle** [comment]
> what method, I cant see it.
> by the way, can you make sure where is the voice emitted from, speakerphone or handset?

The voice is emitted from the speakerphone of the android device. However, on plugging in headphones the audio is also very quiet.

**Comment by DK024-Dev** [comment]
I have issue voice is not clear during video calling
` Future<void> initialize() async {
     await AgoraRtcEngine.create(AGORA_ID);
    await AgoraRtcEngine.enableVideo();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.Communication);
    VideoEncoderConfiguration videoConfig = new VideoEncoderConfiguration();
    videoConfig.dimensions = Size(3840, 2160);
    videoConfig.frameRate = 30;
    videoConfig.orientationMode = VideoOutputOrientationMode.Adaptative;
    videoConfig.bitrate = 3420;
    await AgoraRtcEngine.setVideoEncoderConfiguration(videoConfig);
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
  }`

**Comment by LichKing-2234** [comment]
you may refer to this doc https://docs.agora.io/en/Audio%20Broadcast/volume_android?platform=Android

**Comment by LichKing-2234** [comment]
you can try `AudioScenario.GameStreaming`.
`AudioScenario.Default` in `ChannelProfile.Communication` will use in-call volume

**Comment by LichKing-2234** [comment]
you can refer to this doc https://docs.agora.io/en/faq/system_volume

**Comment by opringle** [comment]
My point is that the volume of the sound being emitted from the android device speakerphone is louder on 1.0.5 than it is on 1.0.8, with the same code.

**Comment by DK024-Dev** [comment]
I have issue surrounding voice during video call can't hear proper voice.
`Future<void> initialize() async {
     await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.Communication);
    VideoEncoderConfiguration videoConfig = new VideoEncoderConfiguration();
    videoConfig.dimensions = Size(3840, 2160);
    videoConfig.frameRate = 30;
    videoConfig.orientationMode = VideoOutputOrientationMode.Adaptative;
    videoConfig.bitrate = 3420;
    await AgoraRtcEngine.setVideoEncoderConfiguration(videoConfig);
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
  }
  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(AGORA_ID);
    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
  }`

**Comment by LichKing-2234** [comment]
@DK024-Dev can you give a detailed description of your problem?

**Comment by LichKing-2234** [comment]
> I have referred to the volume docs and implemented the steps (see my previous comment).
> 
> My point is that the volume of the sound being emitted from the android device speakerphone is louder on 1.0.5 than it is on 1.0.8, with the same code, so it seems something is broken.

is 1.0.5 worked for you?

**Comment by DK024-Dev** [comment]
I have implemented video call in my application but i have one issue, i can't here proper audio both side. it's like surrounding voice.

**Comment by LichKing-2234** [comment]
@DK024-Dev are your devices too near?

**Comment by DK024-Dev** [comment]
Yes, devices are near but in voice call its heard clearly.

**Comment by LichKing-2234** [comment]
you mean run `enableVideo` method then you can hear the noise, but run `enableAudio` method only, the voice is clear.

**Comment by opringle** [comment]
> > I have referred to the volume docs and implemented the steps (see my previous comment).
> > My point is that the volume of the sound being emitted from the android device speakerphone is louder on 1.0.5 than it is on 1.0.8, with the same code, so it seems something is broken.
> 
> is 1.0.5 worked for you?

As I said, it increased the volume coming from the android speakerphone. It is not as loud as I want though.

**Comment by DK024-Dev** [comment]
> you mean run `enableVideo` method then you can hear the noise, but run `enableAudio` method only, the voice is clear.

Yes `enableVideo` and `enableAudio` both combine not get clear voice but only `enableAudio` get clear voice.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
