### ISSUE TITLE
demo ios设备运行没问题，android设备运行一直在runnning中

### ISSUE THREAD

**Issue by tzt1994** [AgoraIO-Community/Agora-Flutter-Quickstart#85]
![image](https://user-images.githubusercontent.com/15625580/78002945-83039880-736a-11ea-8a59-4e82c348d567.png)

**Comment by LichKing-2234** [comment]
试试 gradle clean

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
