### ISSUE TITLE
Remote video call Quaintly  

### ISSUE THREAD

**Issue by Sarmed-armis** [AgoraIO-Community/Agora-Flutter-Quickstart#87]
Hello Dev Team;
kindly need your support to explain how to improve resolution of  remote video call   
since the current resolution as default setting is not good

**Comment by LichKing-2234** [comment]
use `setVideoEncoderConfiguration` method can set the resolution of the local video stream, then the remote device renders the video will be changed

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
