### ISSUE TITLE
OnLeaveChannel callback not invoked

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO-Community/Agora-Flutter-Quickstart#89]
onLeaveChannel callback is not triggered due to 
AgoraRtcEngine.destroy() being called in dispose() immediately after AgoraRtcEngine.leaveChannel()
The engine is destroyed before the callback has had a chance to trigger.  To fix call AgoraRtcEngine.destroy() in the callback.

```dart
  @override
  void dispose() {
    // clear users
    _users.clear();
    super.dispose();
  }
```
Also, fix for onLeaveChannel as the setState is being called after the widget is disposed and causing an exception. It is not necessary to clear users or call setState on onLeaveChannel in this sample. But if you are leaving and joining in the same StatefulWidget be sure to check 'mounted'.

```dart
    AgoraRtcEngine.onLeaveChannel = () {
      AgoraRtcEngine.destroy();
    };
```

**Comment by LichKing-2234** [comment]
sample code just shows how to use our API,  if you need `onLeaveChannel `, you should not add `destroy` below `leaveChannel` method.

**Comment by elhe26** [comment]
> 
> 
> sample code just shows how to use our API, if you need `onLeaveChannel `, you should not add `destroy` below `leaveChannel` method.

How so?
