### ISSUE TITLE
can we use this example to puild Video Broadcasting

### ISSUE THREAD

**Issue by abufaeys** [AgoraIO-Community/Agora-Flutter-Quickstart#9]
hi ,

can we use this example to puild Video Broadcasting .

thank you

**Comment by PRWrl** [comment]
Yes,

`AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting)` before join channel, 
and `AgoraRtcEngine.setClientRole(ClientRole.Broadcaster)` for broadcaster and 
`AgoraRtcEngine.setClientRole(ClientRole.Audience)` for audience.

**Comment by sarthaksadh01** [comment]
does it support screen sharing ?

**Comment by PRWrl** [comment]
Screen sharing is not supported for mobile SDK yet, it depends ReplayKit on iOS and Media Projection on Android.

**Comment by sarthaksadh01** [comment]
So is it possible to pass external video in flutter?
Like i have screen sharing code in flutter which provides live video frames how to pass this to agora?
thank you

**Comment by PRWrl** [comment]
Sorry but external media source is not supported.

**Comment by alfonsodev** [comment]
Hello, thank you for this Flutter SDK Sample!
I'm trying to make live broadcast work, 
here is the gist https://gist.github.com/alfonsodev/e7228253734ba11cd6cecc5cc50488f3
It is simplified to join directly to a broadcast,
The Broadcaster seems to work (I can see the preview video) on the Audience side I only see black screen.

This is how I initialise the Audience side
```
  Future<void> _initAgoraRtcEngine() async {
    AgoraRtcEngine.create('xxxxxxxxxxxxxxxxxx');
    AgoraRtcEngine.enableVideo();
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    AgoraRtcEngine.setClientRole(ClientRole.Audience);
    AgoraRtcEngine.enableWebSdkInteroperability(true);
  }
```
And then I render with 
```
AgoraRtcEngine.createNativeView(1, (viewId) {
  AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Fit, 1);
  AgoraRtcEngine.joinChannel(null, 'flutter', null, 1);
})
```

And here is how I initialise  the Host side,
```
  Future<void> _initAgoraRtcEngine() async {
    AgoraRtcEngine.create('xxxxxxxxxxxxxxxxxxxx');
    AgoraRtcEngine.enableVideo();
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    AgoraRtcEngine.enableWebSdkInteroperability(true);
  }
```
and render
```
AgoraRtcEngine.createNativeView(0, (viweId) {
  AgoraRtcEngine.setupLocalVideo(viweId, VideoRenderMode.Fit);
  AgoraRtcEngine.startPreview();
  AgoraRtcEngine.joinChannel(null, 'flutter', null, 0);
})
```

Any ideas why I'm not getting video in the Audience side ? 

Thank you ❤️

**Comment by PRWrl** [comment]
Hi @alfonsodev   

Audience has to setupRemoteVideo with uid of broadcaster, which you can get in the `onUserJoined` callback.

**Comment by PRWrl** [comment]
```Dart
AgoraRtcEngine.joinChannel(null, 'flutter', null, audienceUid);

AgoraRtcEngine.createNativeView(broadcasterUid, (viewId) {
  AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Fit, broadcasterUid);
})
```

**Comment by alfonsodev** [comment]
onUserJoined, doesn't trigger on the Audience side
```
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    AgoraRtcEngine.setClientRole(ClientRole.Audience);
    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      _log("onUserJoined: uid: $uid  elapsed: $elapsed");
    };
    AgoraRtcEngine.enableVideo();
    _log('to join channel flutter with uid $_uid');

    AgoraRtcEngine.leaveChannel();
    AgoraRtcEngine.joinChannel(null, 'flutter', null, 0);
```
when is supposed to trigger the event ?

I'm testing on a real device, on debug mode.

**Comment by alfonsodev** [comment]
I found in the docs, `onUserJoined` 
> The audience in the channel receives the onUserJoined callback when a new host joins the channel.
But doesn't seem to work on Flutter SD

**Comment by alfonsodev** [comment]
sorry it is working now, for some reason `onUserJoined` wasn't triggering but it is working.
thanks!

**Comment by Andresdiazz** [comment]
Hello alfonsodev, in main.dart, I call the method Host.dart or Audiende.dart?

**Comment by ejdrian313** [comment]
> Hi @alfonsodev
> 
> Audience has to setupRemoteVideo with uid of broadcaster, which you can get in the `onUserJoined` callback.
> 
> ```dart
> AgoraRtcEngine.joinChannel(null, 'flutter', null, audienceUid);
> 
> AgoraRtcEngine.createNativeView(broadcasterUid, (viewId) {
>   AgoraRtcEngine.setupRemoteVideo(viewId, VideoRenderMode.Fit, broadcasterUid);
> })
> ```

could you provide full example? i still getting black screen with as a audiance

**Comment by rlee1990** [comment]
I tried setting up mine the way @alfonsodev but when I try to broadcast I get a black screen.  @PRWrl  could you help?

**Comment by plutoless** [comment]
@rlee1990 please follow instructions [here](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#reporting-an-issue) to report an issue.

**Comment by plutoless** [comment]
@rlee1990 i'll close this one. please provide details in the new ticket you just opened.

**Comment by DK024-Dev** [comment]
@plutoless  I tried to add AgoraRtcEngine.createNativeView but its doesn't set the render view.

**Comment by khaliqdadmohmand** [comment]
> Yes,
> 
> `AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting)` before join channel,
> and `AgoraRtcEngine.setClientRole(ClientRole.Broadcaster)` for broadcaster and
> `AgoraRtcEngine.setClientRole(ClientRole.Audience)` for audience.

do you have any example of that ? plz i need to make a live bradcasting module in my app

**Comment by plutoless** [comment]
@khaliqdadmohmand is the sample within this repository not working for you?

**Comment by khaliqdadmohmand** [comment]
i have issue in this line.. 

> AgoraRtcEngine.createNativeView(0, (viweId){})
 
where it support only one parameter.. if i remove the broadcaster or audience ID which is here 0 in example.. the code works fine but audience cannot see the breadcaster..
 please help me

**Comment by plutoless** [comment]
sorry i don't quite get it. could you pls show me how you changed the code or share with me a sample project?
