### ISSUE TITLE
On android application is crashing with Display.getDisplayId() on null object error

### ISSUE THREAD

**Issue by chhota89** [AgoraIO-Community/Agora-Flutter-Quickstart#91]
When more then 3 people join some time android app get crash with error as Display.getDisplayId() on null object reference.

This is my flutter doctor
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (2 available)
```

My progurad-rule.pro
```
-keep class io.flutter.app.** { *; }
-keep class io.flutter.plugin.**  { *; }
-keep class io.flutter.util.**  { *; }
-keep class io.flutter.view.**  { *; }
-keep class io.flutter.**  { *; }
-keep class io.flutter.plugins.**  { *; }

-keep class io.agora.**{*;}
```

As I was facing the black screen. the error I have commented below line
GeneratedPluginRegistrant.registerWith(flutterEngine) my MainActivity look like

```
class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
//        GeneratedPluginRegistrant.registerWith(flutterEngine);
     }
}
```

Crash report 
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Display Adjustments android.view.Display.getDisplay Adjustments()' on a null object reference

at

android.view.ViewRootlmpl.perform Traversals(View Rootlm pl.java:1788) at android.view.ViewRootlmpl.do Traversal(ViewRootImpl.java :1532) at android.view.ViewRootlmpl$TraversalRunnable.run(ViewRo otlmpl.java:7419) at

android.view.Choreographer$CallbackRecord.run(Choreogr apher.java:1092)

at

android.view.Choreographer.doCallbacks(Choreographer.java:888) va:888) at android.view.Choreographer.doFrame(Choreographer.java:

819) at

android.view.Choreographer$FrameDisplayEventReceiver.r un(Choreographer.java:1078) at android.os.Handler.handleCallback(Handler.java:873) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loop(Looper.java:201) at android.app.ActivityThread.main(Activity Thread.java:

6810) at java.lang.reflect.Method.invoke(Native Method)

at com.android.internal.os.Runtimeinit$MethodAndArgsCaller .run(Runtimeinit.java:547) at com.android.internal.os.Zygoteinit.main(Zygoteinit.java:

873)
```

Please help me guys to solve this issue. As my client is dancing on my head

**Comment by chhota89** [comment]
I have created the one [testing project](https://github.com/chhota89/agora_test) to replicate this issue.  When more than two people join the call then some time app gets crash. Or sometimes when one people left and try to rejoin the call then also it gets crash

**Comment by LichKing-2234** [comment]
@chhota89 is working for me.
`Display.getDisplayId()` may be a bug of flutter, I got it when I test change orientation laster year.
![image](https://user-images.githubusercontent.com/9312526/78740221-ca9cac80-7988-11ea-9db1-d9af15edbb05.png)

**Comment by chhota89** [comment]
@LichKing-2234 What is flutter version?

**Comment by LichKing-2234** [comment]
Flutter (Channel master, v1.15.21, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)

**Comment by chhota89** [comment]
I try with the same flutter version. But still on some device application is crashing. I found the same issue open on Flutter repo. This error is not related to the agora it's coming from the flutter when we try to use the native view in the flutter usually this error is coming. Any solution to this?

**Comment by LichKing-2234** [comment]
@chhota89 Sorry, I have no idea for this bug now.
