### ISSUE TITLE
how to pass extra information while join channel

### ISSUE THREAD

**Issue by singlakaran** [AgoraIO-Community/Agora-Flutter-Quickstart#92]
problem:-
i want to show an image to other users when any user mute local video. so that i have to maintain a Map between agora UID and profilePic.
i tried these 2 ways:-
1)  i used joinChannel function and pass a String in optionalInfo but other users can't get that String while joining.
2)  i used joinChannelWithUserAccount function, and pass a String in userAccount but still it didn't work for me.
if somebody have any solution, then please share here.

**Comment by LichKing-2234** [comment]
@singlakaran use `joinChannelWithUserAccount`, then you can use `getUserInfoByUid `

**Comment by singlakaran** [comment]
@LichKing-2234  i did but `getUserInfoByUid`  gives error 

```PlatformException(getUserInfoByUserAccountError, get user info failed, -134)```

**Comment by LichKing-2234** [comment]
have you used `joinChannelWithUserAccount`?

**Comment by singlakaran** [comment]
@LichKing-2234  yes

**Comment by LichKing-2234** [comment]
extra information should get from your service. the 134 error code means the userAccount is invalid.
https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler_1_1_error_code.html#a624c520d2409935a73a05ac25032791a

**Comment by lakshmiayinala** [comment]
Any updates on this ?.. I'm running through a similar use case where the app needs to show the list of the users(profile pic & username) who joined the channels. I feel this is a basic requirement for the platform to support. Please let me know if any possibility with Agora.

**Comment by varunsdcet** [comment]
@lakshmiayinala ,have you get solution for this,

**Comment by varunsdcet** [comment]
@LichKing-2234 I'm running through a similar use case where the app needs to show the list of the users(profile pic & username) who joined the channels. I feel this is a basic requirement for the platform to support. Please let me know if any possibility with Agora.

**Comment by gdhananjay** [comment]
@LichKing-2234 , @lakshmiayinala @karansingla007 ,

Found any solution i have similar use case.
