### ISSUE TITLE
Implementing Initiates a Call (channelInviteUser) method in flutter

### ISSUE THREAD

**Issue by basilFodouly** [AgoraIO-Community/Agora-Flutter-Quickstart#94]
Hi,
I'm using Agora in flutter to build phone call app , I wont to implement the Initiates a Call (channelInviteUser) in flutter
is there any way

**Comment by LichKing-2234** [comment]
you can use our RTM SDK to invite another user

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.

**Comment by jigarfumakiya** [comment]
Does RTM SDK is available in flutter? @LichKing-2234

**Comment by LichKing-2234** [comment]
@jigarfumakiya sure, you can find it https://pub.dev/packages/agora_rtm

**Comment by jigarfumakiya** [comment]
Thanks, @LichKing-2234
