### ISSUE TITLE
Flutter Plugin: Video Black Screen (v2 embedding)

### ISSUE THREAD

**Issue by github4f** [AgoraIO-Community/Agora-Flutter-Quickstart#95]
It seems that the SDK does not work with the new version of Flutter (v2 embedding). When we downgrade the Manifest.xml from 2 to 1, everything is fine. However, in that case, all other plugins/SDKs including our backend which is based on Firebase stop working... Is there any upgrade in the plugin to tackle this issue? We need to release our product ASAP...

**Comment by LichKing-2234** [comment]
@github4f you can refer to our new [readme](https://github.com/AgoraIO/Flutter-SDK/blob/master/README.md)

**Comment by LichKing-2234** [comment]
@github4f you can refer to our new [readme](https://github.com/AgoraIO/Flutter-SDK/blob/master/README.md) and this[issue](https://github.com/AgoraIO/Flutter-SDK/issues/104)

**Comment by github4f** [comment]
Fantastic. Thanks. It solved the issue!
