### ISSUE TITLE
i get an error while call setLiveTranscoding method

### ISSUE THREAD

**Issue by singlakaran** [AgoraIO-Community/Agora-Flutter-Quickstart#96]
i want to redirect my stream to youtube, facebook

i am using `setLiveTranscoding` and `addPublishStreamUrl`  but it gives me error
```
PlatformException(error, length=3; index=100, null) agora
```
i am using agora_rtc_engine: ^1.0.10

**Comment by LichKing-2234** [comment]
have you done this?
https://docs.agora.io/en/Interactive%20Broadcast/cdn_streaming_android?platform=Android#prerequisites

**Comment by singlakaran** [comment]
yes, i did that
same configuration and same APP_ID is working on android native

here is my code:-

```
 Future<void> setTranscoding(int uid) async {
    try {
      List<AgoraLiveTranscodingUser> agoraLiveUserList =
          cdnLayout(uid, _users, 360, 640);
      await AgoraRtcEngine.setLiveTranscoding(AgoraLiveTranscoding.fromJson({
        'width': 480,
        'height': 640,
        'videoBitrate': 1800,
        'videoFramerate': 15,
        'transcodingUsers': agoraLiveUserList,
        'watermark': AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
        'backgroundImage':
            AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
        'audioSampleRate': AgoraAudioSampleRateType.MidRateType,
        'audioChannels': 2,
        'audioBitrate': 48,
        'videoCodecProfile': AgoraVideoCodecProfileType.High
      }));
      await AgoraRtcEngine.addPublishStreamUrl(
          'rtmp://a.rtmp.youtube.com/live2/deqj-h312-m17h-bbkf', true);
    } catch (error, stackTrace) {
      print(error);
      print(stackTrace);
    }
  }
```

here, i set my layout.

```
List<AgoraLiveTranscodingUser> cdnLayout(
      int bigUserId, List<int> publishers, int canvasWidth, int canvasHeight) {
    List<AgoraLiveTranscodingUser> users = [];
    int index = 0;
    double xIndex, yIndex;
    int viewWidth;
    int viewHEdge;
    if (publishers.length <= 1) {
      viewWidth = canvasWidth;
    } else {
      viewWidth = canvasWidth ~/ 2;
    }
    if (publishers.length <= 2) {
      viewHEdge = canvasHeight;
    } else {
      viewHEdge = canvasHeight ~/ ((publishers.length - 1) / 2 + 1);
    }
    users.add(AgoraLiveTranscodingUser.fromJson({
      'uid': bigUserId,
      'width': viewWidth,
      'height': viewHEdge,
      'x': 0,
      'y': 0,
      'zOrder': 0,
      'alpha': 1,
      'audioChannel': 0
    }));
    index++;
    for (int entry in publishers) {
      if (entry == bigUserId) continue;
      xIndex = index % 2.0;
      yIndex = index / 2;
      users.add(AgoraLiveTranscodingUser.fromJson({
        'uid': entry,
        'width': viewWidth,
        'height': viewHEdge,
        'x': ((xIndex) * viewWidth).toInt(),
        'y': (viewHEdge * (yIndex)).toInt(),
        'zOrder': index + 1,
        'alpha': 1,
        'audioChannel': 0
      }));
      index++;
    }
    return users;
  }
```

**Comment by LichKing-2234** [comment]
it seems like a bug of native code, could you help me to confirm it?
![image](https://user-images.githubusercontent.com/9312526/79684042-f8bf9d80-8260-11ea-8a72-5ce9cc21c8a6.png)

**Comment by LichKing-2234** [comment]
dart invoke method with enum value, but native wants the index value.
![image](https://user-images.githubusercontent.com/9312526/79684087-4cca8200-8261-11ea-8cc3-1d6e5524da09.png)

**Comment by singlakaran** [comment]
@LichKing-2234 
i hardcode the values but still not working. my stream is not redirecting to youtube.
![Screenshot from 2020-04-20 12-02-06](https://user-images.githubusercontent.com/26064126/79721067-68846580-82ff-11ea-9b22-356d7691344b.png)

**Comment by plutoless** [comment]
@singlakaran i think there's a callback named rtmpStreamingStateChanged, could you pls listen to that event to see what state value you get?

**Comment by jajuat** [comment]
@LichKing-2234  Who can help up with this issue? Is there something we are missing in implementation or its an SDK bug?

**Comment by LichKing-2234** [comment]
@jajuat @singlakaran the SDK has some bug, you can try this.
![image](https://user-images.githubusercontent.com/9312526/80570424-5015f880-8a2d-11ea-9818-18129c73de12.png)
And refer to [this doc](https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a3cb9804ae71819038022d7575834b88c)
```
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
```

**Comment by singlakaran** [comment]
> @LichKing-2234
> i hardcode the values but still not working. my stream is not redirecting to youtube.
> ![Screenshot from 2020-04-20 12-02-06](https://user-images.githubusercontent.com/26064126/79721067-68846580-82ff-11ea-9b22-356d7691344b.png)


@LichKing-2234  i already tried this
that was not working for me.

**Comment by LichKing-2234** [comment]
@singlakaran have you setChannelProfile to ChannelProfile.LiveBroadcasting?

**Comment by singlakaran** [comment]
yes, @LichKing-2234 
i already set 
```
await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
```

**Comment by plutoless** [comment]
@singlakaran  could you pls double check that you have enabled RTMP converter as following
![image](https://user-images.githubusercontent.com/471561/80965147-aa0b2980-8e44-11ea-9b3d-6bd054dd4dbb.png)

if not please help provide your project, we may help take a look.

**Comment by singlakaran** [comment]
![Screenshot from 2020-05-04 23-08-45](https://user-images.githubusercontent.com/26064126/80995707-5278b800-8e5c-11ea-9a6a-1d17d364087c.png)

@plutoless i already enabled

**Comment by jajuat** [comment]
The published stream you see if when @singlakaran published via Android SDK. The Android SDK works for us, we are successfully able to stream to You Tube, the same settings in Flutter SDK doesn't work.

**Comment by LichKing-2234** [comment]
@singlakaran @jajuat pls provide your complete dart code about init and join, I will help to check it.

**Comment by singlakaran** [comment]
@LichKing-2234 
i used agora_rtc_engine 1.0.11

but i got error 
`java.lang.Integer cannot be cast to java.lang.Double`
when i call `setLiveTranscoding` method.

you can see my sample project
`https://github.com/singlakaran/agoarCdn`

i set parameters according to:-
`https://docs.agora.io/en/Audio%20Broadcast/cdn_streaming_android?platform=Android`

**Comment by LichKing-2234** [comment]
try this, I will update later
![image](https://user-images.githubusercontent.com/9312526/81462428-fc519f00-91e4-11ea-9896-470ee509e050.png)

**Comment by singlakaran** [comment]
@LichKing-2234  i tried this, but no luch
this time it did not give me any error, but its not redirecting my stream to youtube.

**Comment by LichKing-2234** [comment]
> @singlakaran i think there's a callback named rtmpStreamingStateChanged, could you pls listen to that event to see what state value you get?

pls provide the params of this callback

**Comment by singlakaran** [comment]
@LichKing-2234 
i used these params

```
  Future<void> setTranscoding(int uid) async {
    try {
      List<AgoraLiveTranscodingUser> agoraLiveUserList =
          cdnLayout(uid, _users, 360, 640);

      await AgoraRtcEngine.setLiveTranscoding(AgoraLiveTranscoding.fromJson({
        'width': 480,
        'height': 640,
        'videoBitrate': 1800,
        'videoFramerate': 15,
        'transcodingUsers': agoraLiveUserList,
        'watermark': AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
        'backgroundImage':
            AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
        'audioSampleRate': AgoraAudioSampleRateType.MidRateType,
        'audioChannels': 2,
        'audioBitrate': 48,
        'videoCodecProfile': AgoraVideoCodecProfileType.High
      }));
      await AgoraRtcEngine.addPublishStreamUrl(
          'rtmp://a.rtmp.youtube.com/live2/deqj-h312-m17h-bbkf', true);
    } catch (error, stackTrace) {
      print(error);
      print(stackTrace);
    }
  }
```

```
users.add(AgoraLiveTranscodingUser.fromJson({
        'uid': entry,
        'width': viewWidth,
        'height': viewHEdge,
        'x': ((xIndex) * viewWidth).toInt(),
        'y': (viewHEdge * (yIndex)).toInt(),
        'zOrder': index + 1,
        'alpha': 1,
        'audioChannel': 0
      }));
```

**Comment by LichKing-2234** [comment]
I think you misunderstood me,I want to see the return value of the callback rtmpStreamingStateChanged

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
