### ISSUE TITLE
AgoraRtcEnginePlugin.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by sathishkumarjktech** [AgoraIO-Community/Agora-Flutter-Quickstart#97]
Note: F:\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-1.0.10\android\src\main\java\io\agora\agorartcengine\AgoraRtcEnginePlugin.java uses unchecked or unsafe operations. Note: Recompile with -Xlint:unchecked for details.

**Comment by LichKing-2234** [comment]
this just warning

**Comment by sathishkumarjktech** [comment]
yes i know , But why our Project unsafe ?

**Comment by sathishkumarjktech** [comment]
D/BufferQueueProducer(17421): [SurfaceTexture-42-17421-0](this:0x75cd945000,id:0,api:4,p:375,c:17421) cancelBuffer: slot 1

Why this error coming after video preview started

**Comment by LichKing-2234** [comment]
any preblem? you can ignore some logs.

**Comment by sathishkumarjktech** [comment]
mobile getting hang because of D/BufferQueueProducer(17421): SurfaceTexture-42-17421-0 cancelBuffer: slot 1 this error

**Comment by LichKing-2234** [comment]
pls give a detailed description of your problem, we can't know about it just with a single log.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
