### ISSUE TITLE
@MarcelEdward set `io.flutter.embedded_views_preview` to YES in `info.plist`

### ISSUE THREAD

**Issue by jingyu6lu** [AgoraIO-Community/Agora-Flutter-Quickstart#99]
@MarcelEdward set `io.flutter.embedded_views_preview` to YES in `info.plist`

_Originally posted by @LichKing-2234 in https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/53#issuecomment-611856023_

I did not find this config in info.plist? Or can you tell me how to add it?

**Comment by MarcelEdward** [comment]
You can edit info.plist in android studio and add this:

	<key>io.flutter.embedded_views_preview</key>
	<true/>

or in xcode, then you add the plist key 'io.flutter.embedded_views_preview' as a boolean and set it to true

**Comment by jingyu6lu** [comment]
> You can edit info.plist in android studio and add this:
> 
> ```
> <key>io.flutter.embedded_views_preview</key>
> <true/>
> ```
> 
> or in xcode, then you add the plist key 'io.flutter.embedded_views_preview' as a boolean and set it to true
> 
> Flutter does not seem to add plist keys out of the box. And there is no log indicating a key is missing

Thank you so much, it works. Helps a lot
